// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billingAPIKeyCurrentDocument = `-- name: BillingAPIKeyCurrentDocument :one
WITH base AS (
    SELECT id, total_amount, total_tokens
    FROM billing_document
    WHERE billing_type = 'API_KEY'
      AND document_type = 'CHARGE'
      AND status = 'CONFIRMED'
      AND provider_credential_id = $1::bigint
      AND period_start = $2::timestamptz
      AND period_end = $3::timestamptz
      AND currency = $4::text
)
SELECT base.id AS original_document_id,
       (base.total_amount + COALESCE(SUM(adjustment.total_amount), 0::numeric))::numeric AS total_amount,
       (base.total_tokens + COALESCE(SUM(adjustment.total_tokens), 0::numeric))::bigint AS total_tokens
FROM base
LEFT JOIN billing_document adjustment
  ON adjustment.original_document_id = base.id
 AND adjustment.document_type = 'ADJUSTMENT'
 AND adjustment.status = 'CONFIRMED'
GROUP BY base.id, base.total_amount, base.total_tokens
`

type BillingAPIKeyCurrentDocumentParams struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
}

type BillingAPIKeyCurrentDocumentRow struct {
	OriginalDocumentID int64
	TotalAmount        pgtype.Numeric
	TotalTokens        int64
}

func (q *Queries) BillingAPIKeyCurrentDocument(ctx context.Context, arg BillingAPIKeyCurrentDocumentParams) (BillingAPIKeyCurrentDocumentRow, error) {
	row := q.db.QueryRow(ctx, billingAPIKeyCurrentDocument,
		arg.ProviderCredentialID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
	)
	var i BillingAPIKeyCurrentDocumentRow
	err := row.Scan(&i.OriginalDocumentID, &i.TotalAmount, &i.TotalTokens)
	return i, err
}

const billingAPIKeyCurrentItems = `-- name: BillingAPIKeyCurrentItems :many
WITH base AS (
    SELECT id
    FROM billing_document
    WHERE billing_type = 'API_KEY'
      AND document_type = 'CHARGE'
      AND status = 'CONFIRMED'
      AND provider_credential_id = $1::bigint
      AND period_start = $2::timestamptz
      AND period_end = $3::timestamptz
      AND currency = $4::text
), documents AS (
    SELECT document.id
    FROM billing_document document, base
    WHERE document.id = base.id
       OR (document.original_document_id = base.id
           AND document.document_type = 'ADJUSTMENT'
           AND document.status = 'CONFIRMED')
)
SELECT item.principal_id,
       SUM(item.usage_tokens)::bigint AS tokens,
       SUM(item.amount)::numeric AS amount
FROM billing_document_item item
JOIN documents ON documents.id = item.billing_document_id
GROUP BY item.principal_id
ORDER BY item.principal_id
`

type BillingAPIKeyCurrentItemsParams struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
}

type BillingAPIKeyCurrentItemsRow struct {
	PrincipalID int64
	Tokens      int64
	Amount      pgtype.Numeric
}

func (q *Queries) BillingAPIKeyCurrentItems(ctx context.Context, arg BillingAPIKeyCurrentItemsParams) ([]BillingAPIKeyCurrentItemsRow, error) {
	rows, err := q.db.Query(ctx, billingAPIKeyCurrentItems,
		arg.ProviderCredentialID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingAPIKeyCurrentItemsRow{}
	for rows.Next() {
		var i BillingAPIKeyCurrentItemsRow
		if err := rows.Scan(&i.PrincipalID, &i.Tokens, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingAPIKeyPeriods = `-- name: BillingAPIKeyPeriods :many
WITH current_rating AS (
    SELECT DISTINCT ON (usage_record_id)
           provider_credential_id, usage_started_at, currency
    FROM usage_rating
    ORDER BY usage_record_id, revision DESC, id DESC
)
SELECT provider_credential_id,
       date_trunc('month', usage_started_at, 'UTC')::timestamptz AS period_start,
       (date_trunc('month', usage_started_at, 'UTC') + interval '1 month')::timestamptz AS period_end,
       currency
FROM current_rating
WHERE date_trunc('month', usage_started_at, 'UTC') + interval '1 month' <= $1::timestamptz
GROUP BY provider_credential_id, period_start, period_end, currency
ORDER BY period_start, provider_credential_id, currency
`

type BillingAPIKeyPeriodsRow struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
}

func (q *Queries) BillingAPIKeyPeriods(ctx context.Context, cutoff pgtype.Timestamptz) ([]BillingAPIKeyPeriodsRow, error) {
	rows, err := q.db.Query(ctx, billingAPIKeyPeriods, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingAPIKeyPeriodsRow{}
	for rows.Next() {
		var i BillingAPIKeyPeriodsRow
		if err := rows.Scan(
			&i.ProviderCredentialID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingAPIKeyUsage = `-- name: BillingAPIKeyUsage :many
WITH current_rating AS (
    SELECT DISTINCT ON (usage_record_id)
           id, principal_id, provider_credential_id, usage_started_at,
           input_tokens, output_tokens, total_cost, currency
    FROM usage_rating
    ORDER BY usage_record_id, revision DESC, id DESC
)
SELECT id AS usage_rating_id,
       principal_id,
       (input_tokens + output_tokens)::bigint AS tokens,
       total_cost
FROM current_rating
WHERE provider_credential_id = $1::bigint
  AND usage_started_at >= $2::timestamptz
  AND usage_started_at < $3::timestamptz
  AND currency = $4::text
ORDER BY principal_id, id
`

type BillingAPIKeyUsageParams struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
}

type BillingAPIKeyUsageRow struct {
	UsageRatingID int64
	PrincipalID   int64
	Tokens        int64
	TotalCost     pgtype.Numeric
}

func (q *Queries) BillingAPIKeyUsage(ctx context.Context, arg BillingAPIKeyUsageParams) ([]BillingAPIKeyUsageRow, error) {
	rows, err := q.db.Query(ctx, billingAPIKeyUsage,
		arg.ProviderCredentialID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingAPIKeyUsageRow{}
	for rows.Next() {
		var i BillingAPIKeyUsageRow
		if err := rows.Scan(
			&i.UsageRatingID,
			&i.PrincipalID,
			&i.Tokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingChargeExists = `-- name: BillingChargeExists :one
SELECT EXISTS (
    SELECT 1
    FROM billing_document
    WHERE billing_type = $1::text
      AND document_type = 'CHARGE'
      AND status = 'CONFIRMED'
      AND provider_credential_id = $2::bigint
      AND period_start = $3::timestamptz
      AND period_end = $4::timestamptz
      AND ($1::text = 'SUBSCRIPTION' OR currency = $5::text)
)
`

type BillingChargeExistsParams struct {
	BillingType          string
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
}

func (q *Queries) BillingChargeExists(ctx context.Context, arg BillingChargeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, billingChargeExists,
		arg.BillingType,
		arg.ProviderCredentialID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const billingChargePeriods = `-- name: BillingChargePeriods :many
SELECT provider_credential_id, period_start, period_end
FROM billing_document
WHERE billing_type = 'SUBSCRIPTION'
  AND document_type = 'CHARGE'
  AND status = 'CONFIRMED'
ORDER BY provider_credential_id, period_start
`

type BillingChargePeriodsRow struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
}

func (q *Queries) BillingChargePeriods(ctx context.Context) ([]BillingChargePeriodsRow, error) {
	rows, err := q.db.Query(ctx, billingChargePeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingChargePeriodsRow{}
	for rows.Next() {
		var i BillingChargePeriodsRow
		if err := rows.Scan(&i.ProviderCredentialID, &i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingCurrentAPIKeyAttribution = `-- name: BillingCurrentAPIKeyAttribution :many
WITH raw AS (
    SELECT usage.principal_id,
           principal.name AS principal_name,
           principal.principal_type,
           usage.input_tokens,
           usage.cached_input_tokens,
           usage.output_tokens,
           price.id AS effective_price_id,
           price.currency AS effective_currency,
           price.input_price AS effective_input_price,
           price.cached_input_price AS effective_cached_input_price,
           price.output_price AS effective_output_price,
           rating.model_price_id,
           rating.currency AS rating_currency,
           rating.input_price AS rating_input_price,
           rating.cached_input_price AS rating_cached_input_price,
           rating.output_price AS rating_output_price,
           rating.total_cost
    FROM usage_record usage
    JOIN principal ON principal.id = usage.principal_id
    JOIN provider_credential credential
      ON credential.id = usage.provider_credential_id
     AND credential.auth_type = 'API_KEY'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at
        FROM provider_credential_model_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.provider_model_id = usage.provider_model_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC
        LIMIT 1
    ) price ON TRUE
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.usage_record_id, candidate.revision, candidate.supersedes_rating_id, candidate.principal_id, candidate.provider_credential_id, candidate.provider_model_id, candidate.model_price_id, candidate.usage_started_at, candidate.input_tokens, candidate.cached_input_tokens, candidate.output_tokens, candidate.input_price, candidate.cached_input_price, candidate.output_price, candidate.input_cost, candidate.cached_input_cost, candidate.output_cost, candidate.total_cost, candidate.currency, candidate.created_at
        FROM usage_rating candidate
        WHERE candidate.usage_record_id = usage.id
        ORDER BY candidate.revision DESC, candidate.id DESC
        LIMIT 1
    ) rating ON TRUE
    WHERE usage.started_at >= $1::timestamptz
      AND usage.started_at < $2::timestamptz
      AND usage.status = 'SUCCESS'
)
SELECT principal_id,
       principal_name,
       principal_type,
       rating_currency AS currency,
       SUM(total_cost)::numeric AS amount,
       SUM(input_tokens + output_tokens)::bigint AS tokens
FROM raw
WHERE input_tokens IS NOT NULL
  AND cached_input_tokens IS NOT NULL
  AND output_tokens IS NOT NULL
  AND cached_input_tokens <= input_tokens
  AND effective_price_id IS NOT NULL
  AND model_price_id = effective_price_id
  AND rating_currency = effective_currency
  AND rating_input_price = effective_input_price
  AND rating_cached_input_price = effective_cached_input_price
  AND rating_output_price = effective_output_price
GROUP BY principal_id, principal_name, principal_type, rating_currency
ORDER BY tokens DESC, principal_id, rating_currency
`

type BillingCurrentAPIKeyAttributionParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type BillingCurrentAPIKeyAttributionRow struct {
	PrincipalID   int64
	PrincipalName string
	PrincipalType string
	Currency      string
	Amount        pgtype.Numeric
	Tokens        int64
}

func (q *Queries) BillingCurrentAPIKeyAttribution(ctx context.Context, arg BillingCurrentAPIKeyAttributionParams) ([]BillingCurrentAPIKeyAttributionRow, error) {
	rows, err := q.db.Query(ctx, billingCurrentAPIKeyAttribution, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingCurrentAPIKeyAttributionRow{}
	for rows.Next() {
		var i BillingCurrentAPIKeyAttributionRow
		if err := rows.Scan(
			&i.PrincipalID,
			&i.PrincipalName,
			&i.PrincipalType,
			&i.Currency,
			&i.Amount,
			&i.Tokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingDocument = `-- name: BillingDocument :one
SELECT document.id,
       document.billing_type,
       document.document_type,
       document.status,
       document.provider_credential_id,
       credential.resource_name AS credential_name,
       document.original_document_id,
       document.period_start,
       document.period_end,
       document.total_tokens,
       document.total_amount,
       document.currency,
       document.created_at
FROM billing_document document
JOIN provider_credential credential ON credential.id = document.provider_credential_id
WHERE document.id = $1::bigint
`

type BillingDocumentRow struct {
	ID                   int64
	BillingType          string
	DocumentType         string
	Status               string
	ProviderCredentialID int64
	CredentialName       string
	OriginalDocumentID   *int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	TotalTokens          int64
	TotalAmount          pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) BillingDocument(ctx context.Context, id int64) (BillingDocumentRow, error) {
	row := q.db.QueryRow(ctx, billingDocument, id)
	var i BillingDocumentRow
	err := row.Scan(
		&i.ID,
		&i.BillingType,
		&i.DocumentType,
		&i.Status,
		&i.ProviderCredentialID,
		&i.CredentialName,
		&i.OriginalDocumentID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalTokens,
		&i.TotalAmount,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const billingDocumentAdjustments = `-- name: BillingDocumentAdjustments :many
SELECT document.id,
       document.billing_type,
       document.document_type,
       document.status,
       document.provider_credential_id,
       credential.resource_name AS credential_name,
       document.original_document_id,
       document.period_start,
       document.period_end,
       document.total_tokens,
       document.total_amount,
       document.currency,
       document.created_at
FROM billing_document document
JOIN provider_credential credential ON credential.id = document.provider_credential_id
WHERE document.original_document_id = $1::bigint
ORDER BY document.id
`

type BillingDocumentAdjustmentsRow struct {
	ID                   int64
	BillingType          string
	DocumentType         string
	Status               string
	ProviderCredentialID int64
	CredentialName       string
	OriginalDocumentID   *int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	TotalTokens          int64
	TotalAmount          pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) BillingDocumentAdjustments(ctx context.Context, originalDocumentID int64) ([]BillingDocumentAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, billingDocumentAdjustments, originalDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingDocumentAdjustmentsRow{}
	for rows.Next() {
		var i BillingDocumentAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillingType,
			&i.DocumentType,
			&i.Status,
			&i.ProviderCredentialID,
			&i.CredentialName,
			&i.OriginalDocumentID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalTokens,
			&i.TotalAmount,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingDocumentItems = `-- name: BillingDocumentItems :many
SELECT item.id,
       item.principal_id,
       principal.name AS principal_name,
       principal.principal_type,
       item.usage_tokens,
       item.allocation_ratio,
       item.amount
FROM billing_document_item item
JOIN principal ON principal.id = item.principal_id
WHERE item.billing_document_id = $1::bigint
ORDER BY item.amount DESC, item.principal_id
`

type BillingDocumentItemsRow struct {
	ID              int64
	PrincipalID     int64
	PrincipalName   string
	PrincipalType   string
	UsageTokens     int64
	AllocationRatio pgtype.Numeric
	Amount          pgtype.Numeric
}

func (q *Queries) BillingDocumentItems(ctx context.Context, billingDocumentID int64) ([]BillingDocumentItemsRow, error) {
	rows, err := q.db.Query(ctx, billingDocumentItems, billingDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingDocumentItemsRow{}
	for rows.Next() {
		var i BillingDocumentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalName,
			&i.PrincipalType,
			&i.UsageTokens,
			&i.AllocationRatio,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingDocumentNetAmount = `-- name: BillingDocumentNetAmount :one
SELECT (base.total_amount + COALESCE(SUM(adjustment.total_amount), 0::numeric))::numeric AS amount
FROM billing_document base
LEFT JOIN billing_document adjustment
  ON adjustment.original_document_id = base.id
 AND adjustment.document_type = 'ADJUSTMENT'
 AND adjustment.status = 'CONFIRMED'
WHERE base.id = $1::bigint
GROUP BY base.id, base.total_amount
`

func (q *Queries) BillingDocumentNetAmount(ctx context.Context, id int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, billingDocumentNetAmount, id)
	var amount pgtype.Numeric
	err := row.Scan(&amount)
	return amount, err
}

const billingDocumentRatingCount = `-- name: BillingDocumentRatingCount :one
SELECT COUNT(*)::bigint
FROM billing_document_usage_rating
WHERE billing_document_id = $1::bigint
`

func (q *Queries) BillingDocumentRatingCount(ctx context.Context, billingDocumentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, billingDocumentRatingCount, billingDocumentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const billingDocuments = `-- name: BillingDocuments :many
WITH filtered AS (
    SELECT document.id,
           document.billing_type,
           document.document_type,
           document.status,
           document.provider_credential_id,
           credential.resource_name AS credential_name,
           document.original_document_id,
           document.period_start,
           document.period_end,
           document.total_tokens,
           document.total_amount,
           document.currency,
           document.created_at
    FROM billing_document document
    JOIN provider_credential credential ON credential.id = document.provider_credential_id
    WHERE document.period_start >= $3::timestamptz
      AND document.period_start < $4::timestamptz
      AND ($5::text = '' OR document.billing_type = $5::text)
      AND ($6::text = '' OR document.document_type = $6::text)
      AND ($7::text = '' OR document.currency = $7::text)
)
SELECT filtered.id, filtered.billing_type, filtered.document_type, filtered.status, filtered.provider_credential_id, filtered.credential_name, filtered.original_document_id, filtered.period_start, filtered.period_end, filtered.total_tokens, filtered.total_amount, filtered.currency, filtered.created_at,
       (SELECT COUNT(*) FROM filtered)::bigint AS total_count
FROM filtered
WHERE $1::bigint = 0 OR filtered.id < $1::bigint
ORDER BY filtered.id DESC
LIMIT $2::int
`

type BillingDocumentsParams struct {
	AfterID      int64
	PageLimit    int32
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
	BillingType  string
	DocumentType string
	Currency     string
}

type BillingDocumentsRow struct {
	ID                   int64
	BillingType          string
	DocumentType         string
	Status               string
	ProviderCredentialID int64
	CredentialName       string
	OriginalDocumentID   *int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	TotalTokens          int64
	TotalAmount          pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
	TotalCount           int64
}

func (q *Queries) BillingDocuments(ctx context.Context, arg BillingDocumentsParams) ([]BillingDocumentsRow, error) {
	rows, err := q.db.Query(ctx, billingDocuments,
		arg.AfterID,
		arg.PageLimit,
		arg.FromTime,
		arg.ToTime,
		arg.BillingType,
		arg.DocumentType,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingDocumentsRow{}
	for rows.Next() {
		var i BillingDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillingType,
			&i.DocumentType,
			&i.Status,
			&i.ProviderCredentialID,
			&i.CredentialName,
			&i.OriginalDocumentID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalTokens,
			&i.TotalAmount,
			&i.Currency,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingInsertDocument = `-- name: BillingInsertDocument :execrows
INSERT INTO billing_document (
    id, status, billing_type, document_type, provider_credential_id,
    source_type, source_id, original_document_id, period_start, period_end,
    total_tokens, total_amount, currency, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14
)
ON CONFLICT DO NOTHING
`

type BillingInsertDocumentParams struct {
	ID                   int64
	Status               string
	BillingType          string
	DocumentType         string
	ProviderCredentialID int64
	SourceType           string
	SourceID             *int64
	OriginalDocumentID   *int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	TotalTokens          int64
	TotalAmount          pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) BillingInsertDocument(ctx context.Context, arg BillingInsertDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, billingInsertDocument,
		arg.ID,
		arg.Status,
		arg.BillingType,
		arg.DocumentType,
		arg.ProviderCredentialID,
		arg.SourceType,
		arg.SourceID,
		arg.OriginalDocumentID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalTokens,
		arg.TotalAmount,
		arg.Currency,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const billingInsertDocumentItem = `-- name: BillingInsertDocumentItem :exec
INSERT INTO billing_document_item (
    id, billing_document_id, principal_id, usage_tokens,
    allocation_ratio, amount, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type BillingInsertDocumentItemParams struct {
	ID                int64
	BillingDocumentID int64
	PrincipalID       int64
	UsageTokens       int64
	AllocationRatio   pgtype.Numeric
	Amount            pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) BillingInsertDocumentItem(ctx context.Context, arg BillingInsertDocumentItemParams) error {
	_, err := q.db.Exec(ctx, billingInsertDocumentItem,
		arg.ID,
		arg.BillingDocumentID,
		arg.PrincipalID,
		arg.UsageTokens,
		arg.AllocationRatio,
		arg.Amount,
		arg.CreatedAt,
	)
	return err
}

const billingInsertDocumentUsageRating = `-- name: BillingInsertDocumentUsageRating :exec
INSERT INTO billing_document_usage_rating (billing_document_id, usage_rating_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (usage_rating_id) DO NOTHING
`

type BillingInsertDocumentUsageRatingParams struct {
	BillingDocumentID int64
	UsageRatingID     int64
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) BillingInsertDocumentUsageRating(ctx context.Context, arg BillingInsertDocumentUsageRatingParams) error {
	_, err := q.db.Exec(ctx, billingInsertDocumentUsageRating, arg.BillingDocumentID, arg.UsageRatingID, arg.CreatedAt)
	return err
}

const billingInsertUsageRating = `-- name: BillingInsertUsageRating :execrows
INSERT INTO usage_rating (
    id, usage_record_id, revision, supersedes_rating_id, principal_id,
    provider_credential_id, provider_model_id, model_price_id, usage_started_at,
    input_tokens, cached_input_tokens, output_tokens,
    input_price, cached_input_price, output_price,
    input_cost, cached_input_cost, output_cost, total_cost, currency, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21
)
ON CONFLICT (usage_record_id, revision) DO NOTHING
`

type BillingInsertUsageRatingParams struct {
	ID                   int64
	UsageRecordID        int64
	Revision             int32
	SupersedesRatingID   *int64
	PrincipalID          int64
	ProviderCredentialID int64
	ProviderModelID      int64
	ModelPriceID         int64
	UsageStartedAt       pgtype.Timestamptz
	InputTokens          int64
	CachedInputTokens    int64
	OutputTokens         int64
	InputPrice           pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	OutputPrice          pgtype.Numeric
	InputCost            pgtype.Numeric
	CachedInputCost      pgtype.Numeric
	OutputCost           pgtype.Numeric
	TotalCost            pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) BillingInsertUsageRating(ctx context.Context, arg BillingInsertUsageRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, billingInsertUsageRating,
		arg.ID,
		arg.UsageRecordID,
		arg.Revision,
		arg.SupersedesRatingID,
		arg.PrincipalID,
		arg.ProviderCredentialID,
		arg.ProviderModelID,
		arg.ModelPriceID,
		arg.UsageStartedAt,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.InputPrice,
		arg.CachedInputPrice,
		arg.OutputPrice,
		arg.InputCost,
		arg.CachedInputCost,
		arg.OutputCost,
		arg.TotalCost,
		arg.Currency,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const billingLockDocument = `-- name: BillingLockDocument :one
SELECT id
FROM billing_document
WHERE id = $1::bigint
  AND document_type = 'CHARGE'
  AND status = 'CONFIRMED'
FOR UPDATE
`

func (q *Queries) BillingLockDocument(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, billingLockDocument, id)
	err := row.Scan(&id)
	return id, err
}

const billingOriginalUsage = `-- name: BillingOriginalUsage :many
SELECT principal_id, usage_tokens AS tokens
FROM billing_document_item
WHERE billing_document_id = $1::bigint
  AND usage_tokens > 0
ORDER BY usage_tokens DESC, principal_id
`

type BillingOriginalUsageRow struct {
	PrincipalID int64
	Tokens      int64
}

func (q *Queries) BillingOriginalUsage(ctx context.Context, billingDocumentID int64) ([]BillingOriginalUsageRow, error) {
	rows, err := q.db.Query(ctx, billingOriginalUsage, billingDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingOriginalUsageRow{}
	for rows.Next() {
		var i BillingOriginalUsageRow
		if err := rows.Scan(&i.PrincipalID, &i.Tokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingPrincipalIdentities = `-- name: BillingPrincipalIdentities :many
SELECT id, name, principal_type
FROM principal
WHERE id = ANY($1::bigint[])
ORDER BY id
`

type BillingPrincipalIdentitiesRow struct {
	ID            int64
	Name          string
	PrincipalType string
}

func (q *Queries) BillingPrincipalIdentities(ctx context.Context, principalIds []int64) ([]BillingPrincipalIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, billingPrincipalIdentities, principalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingPrincipalIdentitiesRow{}
	for rows.Next() {
		var i BillingPrincipalIdentitiesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PrincipalType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingStatisticsPrincipals = `-- name: BillingStatisticsPrincipals :many
SELECT item.principal_id,
       principal.name AS principal_name,
       principal.principal_type,
       document.billing_type,
       document.currency,
       SUM(item.amount)::numeric AS amount,
       SUM(item.usage_tokens)::bigint AS tokens,
       COUNT(*) OVER ()::bigint AS total_count
FROM billing_document_item item
JOIN billing_document document ON document.id = item.billing_document_id
JOIN principal ON principal.id = item.principal_id
WHERE document.status = 'CONFIRMED'
  AND document.period_start >= $1::timestamptz
  AND document.period_start < $2::timestamptz
  AND ($3::text = '' OR document.billing_type = $3::text)
GROUP BY item.principal_id, principal.name, principal.principal_type, document.billing_type, document.currency
ORDER BY amount DESC, item.principal_id, document.billing_type, document.currency
LIMIT $5::int OFFSET $4::bigint
`

type BillingStatisticsPrincipalsParams struct {
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	BillingType string
	PageOffset  int64
	PageLimit   int32
}

type BillingStatisticsPrincipalsRow struct {
	PrincipalID   int64
	PrincipalName string
	PrincipalType string
	BillingType   string
	Currency      string
	Amount        pgtype.Numeric
	Tokens        int64
	TotalCount    int64
}

func (q *Queries) BillingStatisticsPrincipals(ctx context.Context, arg BillingStatisticsPrincipalsParams) ([]BillingStatisticsPrincipalsRow, error) {
	rows, err := q.db.Query(ctx, billingStatisticsPrincipals,
		arg.FromTime,
		arg.ToTime,
		arg.BillingType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingStatisticsPrincipalsRow{}
	for rows.Next() {
		var i BillingStatisticsPrincipalsRow
		if err := rows.Scan(
			&i.PrincipalID,
			&i.PrincipalName,
			&i.PrincipalType,
			&i.BillingType,
			&i.Currency,
			&i.Amount,
			&i.Tokens,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingStatisticsTotals = `-- name: BillingStatisticsTotals :many
WITH item_total AS (
    SELECT billing_document_id, SUM(amount) AS amount
    FROM billing_document_item
    GROUP BY billing_document_id
)
SELECT document.currency,
       document.billing_type,
       SUM(document.total_amount)::numeric AS total_amount,
       SUM(COALESCE(item_total.amount, 0::numeric))::numeric AS allocated_amount,
       SUM(document.total_amount - COALESCE(item_total.amount, 0::numeric))::numeric AS unallocated_amount,
       SUM(document.total_tokens)::bigint AS total_tokens
FROM billing_document document
LEFT JOIN item_total ON item_total.billing_document_id = document.id
WHERE document.status = 'CONFIRMED'
  AND document.period_start >= $1::timestamptz
  AND document.period_start < $2::timestamptz
  AND ($3::text = '' OR document.billing_type = $3::text)
GROUP BY document.billing_type, document.currency
ORDER BY document.billing_type, document.currency
`

type BillingStatisticsTotalsParams struct {
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	BillingType string
}

type BillingStatisticsTotalsRow struct {
	Currency          string
	BillingType       string
	TotalAmount       pgtype.Numeric
	AllocatedAmount   pgtype.Numeric
	UnallocatedAmount pgtype.Numeric
	TotalTokens       int64
}

func (q *Queries) BillingStatisticsTotals(ctx context.Context, arg BillingStatisticsTotalsParams) ([]BillingStatisticsTotalsRow, error) {
	rows, err := q.db.Query(ctx, billingStatisticsTotals, arg.FromTime, arg.ToTime, arg.BillingType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingStatisticsTotalsRow{}
	for rows.Next() {
		var i BillingStatisticsTotalsRow
		if err := rows.Scan(
			&i.Currency,
			&i.BillingType,
			&i.TotalAmount,
			&i.AllocatedAmount,
			&i.UnallocatedAmount,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingSubscriptionCorrections = `-- name: BillingSubscriptionCorrections :many
WITH adjustment AS (
    SELECT original_document_id, SUM(total_amount) AS amount
    FROM billing_document
    WHERE billing_type = 'SUBSCRIPTION'
      AND document_type = 'ADJUSTMENT'
      AND status = 'CONFIRMED'
    GROUP BY original_document_id
)
SELECT base.id AS original_document_id,
       base.provider_credential_id,
       base.source_id AS source_price_id,
       base.period_start,
       base.period_end,
       base.currency,
       price.currency AS target_currency,
       (base.total_amount + COALESCE(adjustment.amount, 0::numeric))::numeric AS current_amount,
       price.period_amount AS target_amount
FROM billing_document base
JOIN provider_credential_subscription_price price
  ON base.source_type = 'SUBSCRIPTION_PRICE' AND price.id = base.source_id
LEFT JOIN adjustment ON adjustment.original_document_id = base.id
WHERE base.billing_type = 'SUBSCRIPTION'
  AND base.document_type = 'CHARGE'
  AND base.status = 'CONFIRMED'
  AND (
      base.currency <> price.currency
      OR base.total_amount + COALESCE(adjustment.amount, 0::numeric) <> price.period_amount
  )
ORDER BY base.id
`

type BillingSubscriptionCorrectionsRow struct {
	OriginalDocumentID   int64
	ProviderCredentialID int64
	SourcePriceID        *int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
	TargetCurrency       string
	CurrentAmount        pgtype.Numeric
	TargetAmount         pgtype.Numeric
}

func (q *Queries) BillingSubscriptionCorrections(ctx context.Context) ([]BillingSubscriptionCorrectionsRow, error) {
	rows, err := q.db.Query(ctx, billingSubscriptionCorrections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSubscriptionCorrectionsRow{}
	for rows.Next() {
		var i BillingSubscriptionCorrectionsRow
		if err := rows.Scan(
			&i.OriginalDocumentID,
			&i.ProviderCredentialID,
			&i.SourcePriceID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Currency,
			&i.TargetCurrency,
			&i.CurrentAmount,
			&i.TargetAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingSubscriptionPrices = `-- name: BillingSubscriptionPrices :many
SELECT p.id, p.provider_credential_id, p.currency, p.period_amount,
       p.billing_period, p.effective_at,
       COALESCE(c.effective_at, p.effective_at)::timestamptz AS credential_effective_at,
       CASE WHEN c.is_deleted THEN c.updated_at ELSE c.expires_at END::timestamptz AS credential_end_at
FROM provider_credential_subscription_price p
JOIN provider_credential c ON c.id = p.provider_credential_id
WHERE c.auth_type = 'SUBSCRIPTION'
  AND c.subscription_type = 'PERSONAL'
ORDER BY p.provider_credential_id, p.effective_at, p.id
`

type BillingSubscriptionPricesRow struct {
	ID                    int64
	ProviderCredentialID  int64
	Currency              string
	PeriodAmount          pgtype.Numeric
	BillingPeriod         string
	EffectiveAt           pgtype.Timestamptz
	CredentialEffectiveAt pgtype.Timestamptz
	CredentialEndAt       pgtype.Timestamptz
}

func (q *Queries) BillingSubscriptionPrices(ctx context.Context) ([]BillingSubscriptionPricesRow, error) {
	rows, err := q.db.Query(ctx, billingSubscriptionPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSubscriptionPricesRow{}
	for rows.Next() {
		var i BillingSubscriptionPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCredentialID,
			&i.Currency,
			&i.PeriodAmount,
			&i.BillingPeriod,
			&i.EffectiveAt,
			&i.CredentialEffectiveAt,
			&i.CredentialEndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingSubscriptionUsage = `-- name: BillingSubscriptionUsage :many
SELECT principal_id,
       SUM(COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0))::bigint AS tokens
FROM usage_record
WHERE provider_credential_id = $1::bigint
  AND status = 'SUCCESS'
  AND started_at >= $2::timestamptz
  AND started_at < $3::timestamptz
GROUP BY principal_id
HAVING SUM(COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0)) > 0
ORDER BY tokens DESC, principal_id
`

type BillingSubscriptionUsageParams struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
}

type BillingSubscriptionUsageRow struct {
	PrincipalID int64
	Tokens      int64
}

func (q *Queries) BillingSubscriptionUsage(ctx context.Context, arg BillingSubscriptionUsageParams) ([]BillingSubscriptionUsageRow, error) {
	rows, err := q.db.Query(ctx, billingSubscriptionUsage, arg.ProviderCredentialID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSubscriptionUsageRow{}
	for rows.Next() {
		var i BillingSubscriptionUsageRow
		if err := rows.Scan(&i.PrincipalID, &i.Tokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUnratedUsage = `-- name: BillingUnratedUsage :many
WITH candidates AS (
    SELECT usage.id AS usage_record_id,
           usage.principal_id,
           principal.name AS principal_name,
           principal.principal_type,
           usage.provider_credential_id,
           credential.resource_name AS credential_name,
           usage.provider_model_id,
           usage.started_at,
           usage.input_tokens,
           usage.cached_input_tokens,
           usage.output_tokens,
           usage.created_at AS waiting_since,
           CASE
               WHEN usage.input_tokens IS NULL
                 OR usage.cached_input_tokens IS NULL
                 OR usage.output_tokens IS NULL
                 OR usage.cached_input_tokens > usage.input_tokens
                   THEN 'INCOMPLETE_TOKENS'
               WHEN price.id IS NULL THEN 'MISSING_PRICE'
               WHEN latest.id IS NULL
                 OR latest.model_price_id <> price.id
                 OR latest.currency <> price.currency
                 OR latest.input_price <> price.input_price
                 OR latest.cached_input_price <> price.cached_input_price
                 OR latest.output_price <> price.output_price
                   THEN 'PENDING_RATING'
               ELSE NULL
           END::text AS reason
    FROM usage_record usage
    JOIN principal ON principal.id = usage.principal_id
    JOIN provider_credential credential
      ON credential.id = usage.provider_credential_id
     AND credential.auth_type = 'API_KEY'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at
        FROM provider_credential_model_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.provider_model_id = usage.provider_model_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC
        LIMIT 1
    ) price ON TRUE
    LEFT JOIN LATERAL (
        SELECT rating.id, rating.usage_record_id, rating.revision, rating.supersedes_rating_id, rating.principal_id, rating.provider_credential_id, rating.provider_model_id, rating.model_price_id, rating.usage_started_at, rating.input_tokens, rating.cached_input_tokens, rating.output_tokens, rating.input_price, rating.cached_input_price, rating.output_price, rating.input_cost, rating.cached_input_cost, rating.output_cost, rating.total_cost, rating.currency, rating.created_at
        FROM usage_rating rating
        WHERE rating.usage_record_id = usage.id
        ORDER BY rating.revision DESC, rating.id DESC
        LIMIT 1
    ) latest ON TRUE
    WHERE usage.status = 'SUCCESS'
      AND usage.started_at >= $3::timestamptz
      AND usage.started_at < $4::timestamptz
), filtered AS (
    SELECT usage_record_id, principal_id, principal_name, principal_type, provider_credential_id, credential_name, provider_model_id, started_at, input_tokens, cached_input_tokens, output_tokens, waiting_since, reason
    FROM candidates
    WHERE reason IS NOT NULL
      AND ($5::text = '' OR reason = $5::text)
)
SELECT filtered.usage_record_id, filtered.principal_id, filtered.principal_name, filtered.principal_type, filtered.provider_credential_id, filtered.credential_name, filtered.provider_model_id, filtered.started_at, filtered.input_tokens, filtered.cached_input_tokens, filtered.output_tokens, filtered.waiting_since, filtered.reason,
       (SELECT COUNT(*) FROM filtered)::bigint AS total_count
FROM filtered
WHERE filtered.usage_record_id > $1::bigint
ORDER BY filtered.usage_record_id
LIMIT $2::int
`

type BillingUnratedUsageParams struct {
	AfterID   int64
	PageLimit int32
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
	Reason    string
}

type BillingUnratedUsageRow struct {
	UsageRecordID        int64
	PrincipalID          int64
	PrincipalName        string
	PrincipalType        string
	ProviderCredentialID int64
	CredentialName       string
	ProviderModelID      int64
	StartedAt            pgtype.Timestamptz
	InputTokens          *int64
	CachedInputTokens    *int64
	OutputTokens         *int64
	WaitingSince         pgtype.Timestamptz
	Reason               string
	TotalCount           int64
}

func (q *Queries) BillingUnratedUsage(ctx context.Context, arg BillingUnratedUsageParams) ([]BillingUnratedUsageRow, error) {
	rows, err := q.db.Query(ctx, billingUnratedUsage,
		arg.AfterID,
		arg.PageLimit,
		arg.FromTime,
		arg.ToTime,
		arg.Reason,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingUnratedUsageRow{}
	for rows.Next() {
		var i BillingUnratedUsageRow
		if err := rows.Scan(
			&i.UsageRecordID,
			&i.PrincipalID,
			&i.PrincipalName,
			&i.PrincipalType,
			&i.ProviderCredentialID,
			&i.CredentialName,
			&i.ProviderModelID,
			&i.StartedAt,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.WaitingSince,
			&i.Reason,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUsageCost = `-- name: BillingUsageCost :one
WITH raw AS (
    SELECT usage.id,
           usage.request_id,
           usage.attempt_no,
           usage.principal_id,
           principal.name AS principal_name,
           principal.principal_type,
           usage.model_id,
           model.display_name AS model_name,
           usage.provider_id,
           provider.provider_name,
           usage.provider_model_id,
           usage.provider_credential_id AS resource_id,
           credential.resource_name,
           usage.client_protocol,
           usage.status,
           usage.error_type,
           usage.started_at,
           usage.completed_at,
           usage.latency_ms,
           usage.input_tokens,
           usage.cached_input_tokens,
           usage.output_tokens,
           credential.auth_type AS billing_type,
           price.id AS effective_price_id,
           price.currency AS effective_currency,
           price.input_price AS effective_input_price,
           price.cached_input_price AS effective_cached_input_price,
           price.output_price AS effective_output_price,
           subscription.currency AS subscription_currency,
           rating.id AS rating_id,
           rating.revision AS rating_revision,
           rating.model_price_id,
           rating.currency AS rating_currency,
           rating.input_price AS rating_input_price,
           rating.cached_input_price AS rating_cached_input_price,
           rating.output_price AS rating_output_price,
           rating.total_cost,
           rating.created_at AS rated_at
    FROM usage_record usage
    JOIN principal ON principal.id = usage.principal_id
    JOIN model ON model.id = usage.model_id
    JOIN provider ON provider.id = usage.provider_id
    JOIN provider_credential credential ON credential.id = usage.provider_credential_id
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at FROM provider_credential_model_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.provider_model_id = usage.provider_model_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC LIMIT 1
    ) price ON credential.auth_type = 'API_KEY'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.currency, candidate.period_amount, candidate.billing_period, candidate.effective_at, candidate.created_by, candidate.created_at FROM provider_credential_subscription_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC LIMIT 1
    ) subscription ON credential.auth_type = 'SUBSCRIPTION'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.usage_record_id, candidate.revision, candidate.supersedes_rating_id, candidate.principal_id, candidate.provider_credential_id, candidate.provider_model_id, candidate.model_price_id, candidate.usage_started_at, candidate.input_tokens, candidate.cached_input_tokens, candidate.output_tokens, candidate.input_price, candidate.cached_input_price, candidate.output_price, candidate.input_cost, candidate.cached_input_cost, candidate.output_cost, candidate.total_cost, candidate.currency, candidate.created_at FROM usage_rating candidate
        WHERE candidate.usage_record_id = usage.id
        ORDER BY candidate.revision DESC, candidate.id DESC LIMIT 1
    ) rating ON TRUE
    WHERE usage.id = $1::bigint
)
SELECT id,
       request_id,
       attempt_no,
       principal_id,
       principal_name,
       principal_type,
       model_id,
       model_name,
       provider_id,
       provider_name,
       provider_model_id,
       resource_id,
       resource_name,
       client_protocol,
       status,
       error_type,
       started_at,
       completed_at,
       latency_ms,
       input_tokens,
       cached_input_tokens,
       output_tokens,
       billing_type,
       CASE
           WHEN status <> 'SUCCESS' THEN 'NOT_BILLABLE'
           WHEN billing_type = 'SUBSCRIPTION' THEN 'SUBSCRIPTION_SHARED'
           WHEN input_tokens IS NULL OR cached_input_tokens IS NULL OR output_tokens IS NULL
             OR cached_input_tokens > input_tokens THEN 'INCOMPLETE_TOKENS'
           WHEN effective_price_id IS NULL THEN 'MISSING_PRICE'
           WHEN rating_id IS NULL OR model_price_id <> effective_price_id
             OR rating_currency <> effective_currency
             OR rating_input_price <> effective_input_price
             OR rating_cached_input_price <> effective_cached_input_price
             OR rating_output_price <> effective_output_price THEN 'PENDING_RATING'
           ELSE 'RATED'
       END::text AS rating_status,
       COALESCE(rating_id, 0)::bigint AS rating_id,
       COALESCE(rating_revision, 0)::int AS rating_revision,
       COALESCE(CASE WHEN billing_type = 'SUBSCRIPTION' THEN subscription_currency ELSE effective_currency END, '')::text AS currency,
       COALESCE(total_cost, 0::numeric)::numeric AS total_cost,
       COALESCE(rated_at, started_at)::timestamptz AS rated_at
FROM raw
`

type BillingUsageCostRow struct {
	ID                int64
	RequestID         string
	AttemptNo         int64
	PrincipalID       int64
	PrincipalName     string
	PrincipalType     string
	ModelID           int64
	ModelName         string
	ProviderID        int64
	ProviderName      string
	ProviderModelID   int64
	ResourceID        int64
	ResourceName      string
	ClientProtocol    string
	Status            string
	ErrorType         *string
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	LatencyMs         int64
	InputTokens       *int64
	CachedInputTokens *int64
	OutputTokens      *int64
	BillingType       string
	RatingStatus      string
	RatingID          int64
	RatingRevision    int32
	Currency          string
	TotalCost         pgtype.Numeric
	RatedAt           pgtype.Timestamptz
}

func (q *Queries) BillingUsageCost(ctx context.Context, usageRecordID int64) (BillingUsageCostRow, error) {
	row := q.db.QueryRow(ctx, billingUsageCost, usageRecordID)
	var i BillingUsageCostRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.AttemptNo,
		&i.PrincipalID,
		&i.PrincipalName,
		&i.PrincipalType,
		&i.ModelID,
		&i.ModelName,
		&i.ProviderID,
		&i.ProviderName,
		&i.ProviderModelID,
		&i.ResourceID,
		&i.ResourceName,
		&i.ClientProtocol,
		&i.Status,
		&i.ErrorType,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LatencyMs,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.BillingType,
		&i.RatingStatus,
		&i.RatingID,
		&i.RatingRevision,
		&i.Currency,
		&i.TotalCost,
		&i.RatedAt,
	)
	return i, err
}

const billingUsageCostRatings = `-- name: BillingUsageCostRatings :many
SELECT rating.id,
       rating.revision,
       rating.model_price_id,
       price.effective_at AS price_effective_at,
       rating.input_price,
       rating.cached_input_price,
       rating.output_price,
       rating.input_cost,
       rating.cached_input_cost,
       rating.output_cost,
       rating.total_cost,
       rating.currency,
       rating.created_at
FROM usage_rating rating
JOIN provider_credential_model_price price ON price.id = rating.model_price_id
WHERE rating.usage_record_id = $1::bigint
ORDER BY rating.revision DESC, rating.id DESC
`

type BillingUsageCostRatingsRow struct {
	ID               int64
	Revision         int32
	ModelPriceID     int64
	PriceEffectiveAt pgtype.Timestamptz
	InputPrice       pgtype.Numeric
	CachedInputPrice pgtype.Numeric
	OutputPrice      pgtype.Numeric
	InputCost        pgtype.Numeric
	CachedInputCost  pgtype.Numeric
	OutputCost       pgtype.Numeric
	TotalCost        pgtype.Numeric
	Currency         string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) BillingUsageCostRatings(ctx context.Context, usageRecordID int64) ([]BillingUsageCostRatingsRow, error) {
	rows, err := q.db.Query(ctx, billingUsageCostRatings, usageRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingUsageCostRatingsRow{}
	for rows.Next() {
		var i BillingUsageCostRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.ModelPriceID,
			&i.PriceEffectiveAt,
			&i.InputPrice,
			&i.CachedInputPrice,
			&i.OutputPrice,
			&i.InputCost,
			&i.CachedInputCost,
			&i.OutputCost,
			&i.TotalCost,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUsageCostSummary = `-- name: BillingUsageCostSummary :one
WITH raw AS (
    SELECT usage.id,
           usage.request_id,
           usage.status,
           usage.input_tokens,
           usage.cached_input_tokens,
           usage.output_tokens,
           credential.auth_type AS billing_type,
           price.id AS effective_price_id,
           price.currency AS effective_currency,
           price.input_price AS effective_input_price,
           price.cached_input_price AS effective_cached_input_price,
           price.output_price AS effective_output_price,
           subscription.currency AS subscription_currency,
           rating.id AS rating_id,
           rating.model_price_id,
           rating.currency AS rating_currency,
           rating.input_price AS rating_input_price,
           rating.cached_input_price AS rating_cached_input_price,
           rating.output_price AS rating_output_price,
           rating.total_cost
    FROM usage_record usage
    JOIN principal ON principal.id = usage.principal_id
    JOIN provider_credential credential ON credential.id = usage.provider_credential_id
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at
        FROM provider_credential_model_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.provider_model_id = usage.provider_model_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC
        LIMIT 1
    ) price ON credential.auth_type = 'API_KEY'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.currency, candidate.period_amount, candidate.billing_period, candidate.effective_at, candidate.created_by, candidate.created_at
        FROM provider_credential_subscription_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC
        LIMIT 1
    ) subscription ON credential.auth_type = 'SUBSCRIPTION'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.usage_record_id, candidate.revision, candidate.supersedes_rating_id, candidate.principal_id, candidate.provider_credential_id, candidate.provider_model_id, candidate.model_price_id, candidate.usage_started_at, candidate.input_tokens, candidate.cached_input_tokens, candidate.output_tokens, candidate.input_price, candidate.cached_input_price, candidate.output_price, candidate.input_cost, candidate.cached_input_cost, candidate.output_cost, candidate.total_cost, candidate.currency, candidate.created_at
        FROM usage_rating candidate
        WHERE candidate.usage_record_id = usage.id
        ORDER BY candidate.revision DESC, candidate.id DESC
        LIMIT 1
    ) rating ON TRUE
    WHERE usage.started_at >= $1::timestamptz
      AND usage.started_at < $2::timestamptz
      AND ($3::bigint IS NULL OR usage.principal_id = $3)
      AND ($4::text = '' OR principal.principal_type = $4::text)
      AND ($5::bigint IS NULL OR EXISTS (
          SELECT 1 FROM principal_group_membership membership
          WHERE membership.principal_id = usage.principal_id
            AND membership.group_id = $5
            AND membership.is_deleted = false
      ))
      AND ($6::bigint IS NULL OR usage.model_id = $6)
      AND ($7::bigint IS NULL OR usage.provider_id = $7)
      AND ($8::bigint IS NULL OR usage.provider_credential_id = $8)
      AND ($9::text = '' OR usage.client_protocol = $9::text)
      AND ($10::text = '' OR usage.status = $10::text)
), classified AS (
    SELECT raw.id, raw.request_id, raw.status, raw.input_tokens, raw.cached_input_tokens, raw.output_tokens, raw.billing_type, raw.effective_price_id, raw.effective_currency, raw.effective_input_price, raw.effective_cached_input_price, raw.effective_output_price, raw.subscription_currency, raw.rating_id, raw.model_price_id, raw.rating_currency, raw.rating_input_price, raw.rating_cached_input_price, raw.rating_output_price, raw.total_cost,
           CASE
               WHEN status <> 'SUCCESS' THEN 'NOT_BILLABLE'
               WHEN billing_type = 'SUBSCRIPTION' THEN 'SUBSCRIPTION_SHARED'
               WHEN input_tokens IS NULL OR cached_input_tokens IS NULL OR output_tokens IS NULL
                 OR cached_input_tokens > input_tokens THEN 'INCOMPLETE_TOKENS'
               WHEN effective_price_id IS NULL THEN 'MISSING_PRICE'
               WHEN rating_id IS NULL OR model_price_id <> effective_price_id
                 OR rating_currency <> effective_currency
                 OR rating_input_price <> effective_input_price
                 OR rating_cached_input_price <> effective_cached_input_price
                 OR rating_output_price <> effective_output_price THEN 'PENDING_RATING'
               ELSE 'RATED'
           END::text AS rating_status,
           CASE WHEN billing_type = 'SUBSCRIPTION' THEN subscription_currency ELSE effective_currency END AS currency
    FROM raw
), filtered AS (
    SELECT id, request_id, status, input_tokens, cached_input_tokens, output_tokens, billing_type, effective_price_id, effective_currency, effective_input_price, effective_cached_input_price, effective_output_price, subscription_currency, rating_id, model_price_id, rating_currency, rating_input_price, rating_cached_input_price, rating_output_price, total_cost, rating_status, currency FROM classified
    WHERE ($11::text = '' OR rating_status = $11::text)
      AND ($12::text = '' OR billing_type = $12::text)
      AND ($13::text = '' OR currency = $13::text)
)
SELECT COUNT(DISTINCT request_id)::bigint AS requests,
       COUNT(*)::bigint AS attempts,
       COUNT(*) FILTER (WHERE status = 'SUCCESS')::bigint AS successful,
       COALESCE(SUM(input_tokens), 0)::bigint AS input_tokens,
       COALESCE(SUM(cached_input_tokens), 0)::bigint AS cached_input_tokens,
       COALESCE(SUM(output_tokens), 0)::bigint AS output_tokens,
       COUNT(*) FILTER (WHERE rating_status = 'RATED')::bigint AS rated,
       COUNT(*) FILTER (WHERE rating_status = 'SUBSCRIPTION_SHARED')::bigint AS shared,
       COUNT(*) FILTER (WHERE rating_status NOT IN ('RATED', 'SUBSCRIPTION_SHARED', 'NOT_BILLABLE'))::bigint AS unrated
FROM filtered
`

type BillingUsageCostSummaryParams struct {
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PrincipalID    *int64
	PrincipalType  string
	GroupID        *int64
	ModelID        *int64
	ProviderID     *int64
	ResourceID     *int64
	ClientProtocol string
	UsageStatus    string
	RatingStatus   string
	BillingType    string
	Currency       string
}

type BillingUsageCostSummaryRow struct {
	Requests          int64
	Attempts          int64
	Successful        int64
	InputTokens       int64
	CachedInputTokens int64
	OutputTokens      int64
	Rated             int64
	Shared            int64
	Unrated           int64
}

func (q *Queries) BillingUsageCostSummary(ctx context.Context, arg BillingUsageCostSummaryParams) (BillingUsageCostSummaryRow, error) {
	row := q.db.QueryRow(ctx, billingUsageCostSummary,
		arg.FromTime,
		arg.ToTime,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.GroupID,
		arg.ModelID,
		arg.ProviderID,
		arg.ResourceID,
		arg.ClientProtocol,
		arg.UsageStatus,
		arg.RatingStatus,
		arg.BillingType,
		arg.Currency,
	)
	var i BillingUsageCostSummaryRow
	err := row.Scan(
		&i.Requests,
		&i.Attempts,
		&i.Successful,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.Rated,
		&i.Shared,
		&i.Unrated,
	)
	return i, err
}

const billingUsageCostTotals = `-- name: BillingUsageCostTotals :many
WITH raw AS (
    SELECT usage.id,
           usage.status,
           usage.input_tokens,
           usage.cached_input_tokens,
           usage.output_tokens,
           credential.auth_type AS billing_type,
           price.id AS effective_price_id,
           price.currency AS effective_currency,
           price.input_price AS effective_input_price,
           price.cached_input_price AS effective_cached_input_price,
           price.output_price AS effective_output_price,
           subscription.currency AS subscription_currency,
           rating.id AS rating_id,
           rating.model_price_id,
           rating.currency AS rating_currency,
           rating.input_price AS rating_input_price,
           rating.cached_input_price AS rating_cached_input_price,
           rating.output_price AS rating_output_price,
           rating.total_cost
    FROM usage_record usage
    JOIN principal ON principal.id = usage.principal_id
    JOIN provider_credential credential ON credential.id = usage.provider_credential_id
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at FROM provider_credential_model_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.provider_model_id = usage.provider_model_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC LIMIT 1
    ) price ON credential.auth_type = 'API_KEY'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.currency, candidate.period_amount, candidate.billing_period, candidate.effective_at, candidate.created_by, candidate.created_at FROM provider_credential_subscription_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC LIMIT 1
    ) subscription ON credential.auth_type = 'SUBSCRIPTION'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.usage_record_id, candidate.revision, candidate.supersedes_rating_id, candidate.principal_id, candidate.provider_credential_id, candidate.provider_model_id, candidate.model_price_id, candidate.usage_started_at, candidate.input_tokens, candidate.cached_input_tokens, candidate.output_tokens, candidate.input_price, candidate.cached_input_price, candidate.output_price, candidate.input_cost, candidate.cached_input_cost, candidate.output_cost, candidate.total_cost, candidate.currency, candidate.created_at FROM usage_rating candidate
        WHERE candidate.usage_record_id = usage.id
        ORDER BY candidate.revision DESC, candidate.id DESC LIMIT 1
    ) rating ON TRUE
    WHERE usage.started_at >= $1::timestamptz
      AND usage.started_at < $2::timestamptz
      AND ($3::bigint IS NULL OR usage.principal_id = $3)
      AND ($4::text = '' OR principal.principal_type = $4::text)
      AND ($5::bigint IS NULL OR EXISTS (
          SELECT 1 FROM principal_group_membership membership
          WHERE membership.principal_id = usage.principal_id
            AND membership.group_id = $5
            AND membership.is_deleted = false
      ))
      AND ($6::bigint IS NULL OR usage.model_id = $6)
      AND ($7::bigint IS NULL OR usage.provider_id = $7)
      AND ($8::bigint IS NULL OR usage.provider_credential_id = $8)
      AND ($9::text = '' OR usage.client_protocol = $9::text)
      AND ($10::text = '' OR usage.status = $10::text)
), classified AS (
    SELECT raw.id, raw.status, raw.input_tokens, raw.cached_input_tokens, raw.output_tokens, raw.billing_type, raw.effective_price_id, raw.effective_currency, raw.effective_input_price, raw.effective_cached_input_price, raw.effective_output_price, raw.subscription_currency, raw.rating_id, raw.model_price_id, raw.rating_currency, raw.rating_input_price, raw.rating_cached_input_price, raw.rating_output_price, raw.total_cost,
           CASE
               WHEN status <> 'SUCCESS' THEN 'NOT_BILLABLE'
               WHEN billing_type = 'SUBSCRIPTION' THEN 'SUBSCRIPTION_SHARED'
               WHEN input_tokens IS NULL OR cached_input_tokens IS NULL OR output_tokens IS NULL
                 OR cached_input_tokens > input_tokens THEN 'INCOMPLETE_TOKENS'
               WHEN effective_price_id IS NULL THEN 'MISSING_PRICE'
               WHEN rating_id IS NULL OR model_price_id <> effective_price_id
                 OR rating_currency <> effective_currency
                 OR rating_input_price <> effective_input_price
                 OR rating_cached_input_price <> effective_cached_input_price
                 OR rating_output_price <> effective_output_price THEN 'PENDING_RATING'
               ELSE 'RATED'
           END::text AS rating_status,
           CASE WHEN billing_type = 'SUBSCRIPTION' THEN subscription_currency ELSE effective_currency END AS currency
    FROM raw
), filtered AS (
    SELECT id, status, input_tokens, cached_input_tokens, output_tokens, billing_type, effective_price_id, effective_currency, effective_input_price, effective_cached_input_price, effective_output_price, subscription_currency, rating_id, model_price_id, rating_currency, rating_input_price, rating_cached_input_price, rating_output_price, total_cost, rating_status, currency FROM classified
    WHERE ($11::text = '' OR rating_status = $11::text)
      AND ($12::text = '' OR billing_type = $12::text)
      AND ($13::text = '' OR currency = $13::text)
)
SELECT rating_currency AS currency,
       SUM(total_cost)::numeric AS amount,
       COUNT(*)::bigint AS rated
FROM filtered
WHERE rating_status = 'RATED'
GROUP BY rating_currency
ORDER BY rating_currency
`

type BillingUsageCostTotalsParams struct {
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PrincipalID    *int64
	PrincipalType  string
	GroupID        *int64
	ModelID        *int64
	ProviderID     *int64
	ResourceID     *int64
	ClientProtocol string
	UsageStatus    string
	RatingStatus   string
	BillingType    string
	Currency       string
}

type BillingUsageCostTotalsRow struct {
	Currency string
	Amount   pgtype.Numeric
	Rated    int64
}

func (q *Queries) BillingUsageCostTotals(ctx context.Context, arg BillingUsageCostTotalsParams) ([]BillingUsageCostTotalsRow, error) {
	rows, err := q.db.Query(ctx, billingUsageCostTotals,
		arg.FromTime,
		arg.ToTime,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.GroupID,
		arg.ModelID,
		arg.ProviderID,
		arg.ResourceID,
		arg.ClientProtocol,
		arg.UsageStatus,
		arg.RatingStatus,
		arg.BillingType,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingUsageCostTotalsRow{}
	for rows.Next() {
		var i BillingUsageCostTotalsRow
		if err := rows.Scan(&i.Currency, &i.Amount, &i.Rated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUsageCosts = `-- name: BillingUsageCosts :many
WITH raw AS (
    SELECT usage.id,
           usage.request_id,
           usage.attempt_no,
           usage.principal_id,
           principal.name AS principal_name,
           principal.principal_type,
           usage.model_id,
           model.display_name AS model_name,
           usage.provider_id,
           provider.provider_name,
           usage.provider_model_id,
           usage.provider_credential_id AS resource_id,
           credential.resource_name,
           usage.client_protocol,
           usage.status,
           usage.error_type,
           usage.started_at,
           usage.completed_at,
           usage.latency_ms,
           usage.input_tokens,
           usage.cached_input_tokens,
           usage.output_tokens,
           credential.auth_type AS billing_type,
           price.id AS effective_price_id,
           price.currency AS effective_currency,
           price.input_price AS effective_input_price,
           price.cached_input_price AS effective_cached_input_price,
           price.output_price AS effective_output_price,
           subscription.currency AS subscription_currency,
           rating.id AS rating_id,
           rating.revision AS rating_revision,
           rating.model_price_id,
           rating.currency AS rating_currency,
           rating.input_price AS rating_input_price,
           rating.cached_input_price AS rating_cached_input_price,
           rating.output_price AS rating_output_price,
           rating.total_cost,
           rating.created_at AS rated_at
    FROM usage_record usage
    JOIN principal ON principal.id = usage.principal_id
    JOIN model ON model.id = usage.model_id
    JOIN provider ON provider.id = usage.provider_id
    JOIN provider_credential credential ON credential.id = usage.provider_credential_id
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at FROM provider_credential_model_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.provider_model_id = usage.provider_model_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC LIMIT 1
    ) price ON credential.auth_type = 'API_KEY'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.provider_credential_id, candidate.currency, candidate.period_amount, candidate.billing_period, candidate.effective_at, candidate.created_by, candidate.created_at FROM provider_credential_subscription_price candidate
        WHERE candidate.provider_credential_id = usage.provider_credential_id
          AND candidate.effective_at <= usage.started_at
        ORDER BY candidate.effective_at DESC, candidate.id DESC LIMIT 1
    ) subscription ON credential.auth_type = 'SUBSCRIPTION'
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.usage_record_id, candidate.revision, candidate.supersedes_rating_id, candidate.principal_id, candidate.provider_credential_id, candidate.provider_model_id, candidate.model_price_id, candidate.usage_started_at, candidate.input_tokens, candidate.cached_input_tokens, candidate.output_tokens, candidate.input_price, candidate.cached_input_price, candidate.output_price, candidate.input_cost, candidate.cached_input_cost, candidate.output_cost, candidate.total_cost, candidate.currency, candidate.created_at FROM usage_rating candidate
        WHERE candidate.usage_record_id = usage.id
        ORDER BY candidate.revision DESC, candidate.id DESC LIMIT 1
    ) rating ON TRUE
    WHERE usage.started_at >= $5::timestamptz
      AND usage.started_at < $6::timestamptz
      AND ($7::bigint IS NULL OR usage.principal_id = $7)
      AND ($8::text = '' OR principal.principal_type = $8::text)
      AND ($9::bigint IS NULL OR EXISTS (
          SELECT 1 FROM principal_group_membership membership
          WHERE membership.principal_id = usage.principal_id
            AND membership.group_id = $9
            AND membership.is_deleted = false
      ))
      AND ($10::bigint IS NULL OR usage.model_id = $10)
      AND ($11::bigint IS NULL OR usage.provider_id = $11)
      AND ($12::bigint IS NULL OR usage.provider_credential_id = $12)
      AND ($13::text = '' OR usage.client_protocol = $13::text)
      AND ($14::text = '' OR usage.status = $14::text)
), classified AS (
    SELECT raw.id, raw.request_id, raw.attempt_no, raw.principal_id, raw.principal_name, raw.principal_type, raw.model_id, raw.model_name, raw.provider_id, raw.provider_name, raw.provider_model_id, raw.resource_id, raw.resource_name, raw.client_protocol, raw.status, raw.error_type, raw.started_at, raw.completed_at, raw.latency_ms, raw.input_tokens, raw.cached_input_tokens, raw.output_tokens, raw.billing_type, raw.effective_price_id, raw.effective_currency, raw.effective_input_price, raw.effective_cached_input_price, raw.effective_output_price, raw.subscription_currency, raw.rating_id, raw.rating_revision, raw.model_price_id, raw.rating_currency, raw.rating_input_price, raw.rating_cached_input_price, raw.rating_output_price, raw.total_cost, raw.rated_at,
           CASE
               WHEN status <> 'SUCCESS' THEN 'NOT_BILLABLE'
               WHEN billing_type = 'SUBSCRIPTION' THEN 'SUBSCRIPTION_SHARED'
               WHEN input_tokens IS NULL OR cached_input_tokens IS NULL OR output_tokens IS NULL
                 OR cached_input_tokens > input_tokens THEN 'INCOMPLETE_TOKENS'
               WHEN effective_price_id IS NULL THEN 'MISSING_PRICE'
               WHEN rating_id IS NULL OR model_price_id <> effective_price_id
                 OR rating_currency <> effective_currency
                 OR rating_input_price <> effective_input_price
                 OR rating_cached_input_price <> effective_cached_input_price
                 OR rating_output_price <> effective_output_price THEN 'PENDING_RATING'
               ELSE 'RATED'
           END::text AS rating_status,
           CASE WHEN billing_type = 'SUBSCRIPTION' THEN subscription_currency ELSE effective_currency END AS currency
    FROM raw
), filtered AS (
    SELECT id, request_id, attempt_no, principal_id, principal_name, principal_type, model_id, model_name, provider_id, provider_name, provider_model_id, resource_id, resource_name, client_protocol, status, error_type, started_at, completed_at, latency_ms, input_tokens, cached_input_tokens, output_tokens, billing_type, effective_price_id, effective_currency, effective_input_price, effective_cached_input_price, effective_output_price, subscription_currency, rating_id, rating_revision, model_price_id, rating_currency, rating_input_price, rating_cached_input_price, rating_output_price, total_cost, rated_at, rating_status, currency,
           (COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0))::bigint AS total_tokens
    FROM classified
    WHERE ($15::text = '' OR rating_status = $15::text)
      AND ($16::text = '' OR billing_type = $16::text)
      AND ($17::text = '' OR currency = $17::text)
)
SELECT id,
       request_id,
       attempt_no,
       principal_id,
       principal_name,
       principal_type,
       model_id,
       model_name,
       provider_id,
       provider_name,
       provider_model_id,
       resource_id,
       resource_name,
       client_protocol,
       status,
       error_type,
       started_at,
       completed_at,
       latency_ms,
       input_tokens,
       cached_input_tokens,
       output_tokens,
       billing_type,
       rating_status,
       COALESCE(rating_id, 0)::bigint AS rating_id,
       COALESCE(rating_revision, 0)::int AS rating_revision,
       COALESCE(currency, '')::text AS currency,
       COALESCE(total_cost, 0::numeric)::numeric AS total_cost,
       COALESCE(rated_at, started_at)::timestamptz AS rated_at,
       COUNT(*) OVER ()::bigint AS total_count
FROM filtered
ORDER BY
    CASE WHEN $1::text = 'startedAt' AND $2::text = 'asc' THEN started_at END ASC,
    CASE WHEN $1::text = 'startedAt' AND $2::text = 'desc' THEN started_at END DESC,
    CASE WHEN $1::text = 'totalCost' AND $2::text = 'asc' THEN total_cost END ASC NULLS LAST,
    CASE WHEN $1::text = 'totalCost' AND $2::text = 'desc' THEN total_cost END DESC NULLS LAST,
    CASE WHEN $1::text = 'tokens' AND $2::text = 'asc' THEN total_tokens END ASC,
    CASE WHEN $1::text = 'tokens' AND $2::text = 'desc' THEN total_tokens END DESC,
    CASE WHEN $1::text = 'latency' AND $2::text = 'asc' THEN latency_ms END ASC,
    CASE WHEN $1::text = 'latency' AND $2::text = 'desc' THEN latency_ms END DESC,
    id DESC
LIMIT $4::int OFFSET $3::bigint
`

type BillingUsageCostsParams struct {
	SortBy         string
	SortOrder      string
	PageOffset     int64
	PageLimit      int32
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PrincipalID    *int64
	PrincipalType  string
	GroupID        *int64
	ModelID        *int64
	ProviderID     *int64
	ResourceID     *int64
	ClientProtocol string
	UsageStatus    string
	RatingStatus   string
	BillingType    string
	Currency       string
}

type BillingUsageCostsRow struct {
	ID                int64
	RequestID         string
	AttemptNo         int64
	PrincipalID       int64
	PrincipalName     string
	PrincipalType     string
	ModelID           int64
	ModelName         string
	ProviderID        int64
	ProviderName      string
	ProviderModelID   int64
	ResourceID        int64
	ResourceName      string
	ClientProtocol    string
	Status            string
	ErrorType         *string
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	LatencyMs         int64
	InputTokens       *int64
	CachedInputTokens *int64
	OutputTokens      *int64
	BillingType       string
	RatingStatus      string
	RatingID          int64
	RatingRevision    int32
	Currency          string
	TotalCost         pgtype.Numeric
	RatedAt           pgtype.Timestamptz
	TotalCount        int64
}

func (q *Queries) BillingUsageCosts(ctx context.Context, arg BillingUsageCostsParams) ([]BillingUsageCostsRow, error) {
	rows, err := q.db.Query(ctx, billingUsageCosts,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
		arg.FromTime,
		arg.ToTime,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.GroupID,
		arg.ModelID,
		arg.ProviderID,
		arg.ResourceID,
		arg.ClientProtocol,
		arg.UsageStatus,
		arg.RatingStatus,
		arg.BillingType,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingUsageCostsRow{}
	for rows.Next() {
		var i BillingUsageCostsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.AttemptNo,
			&i.PrincipalID,
			&i.PrincipalName,
			&i.PrincipalType,
			&i.ModelID,
			&i.ModelName,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderModelID,
			&i.ResourceID,
			&i.ResourceName,
			&i.ClientProtocol,
			&i.Status,
			&i.ErrorType,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LatencyMs,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.BillingType,
			&i.RatingStatus,
			&i.RatingID,
			&i.RatingRevision,
			&i.Currency,
			&i.TotalCost,
			&i.RatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUsageRatingCandidates = `-- name: BillingUsageRatingCandidates :many
SELECT usage.id AS usage_record_id,
       usage.principal_id,
       usage.provider_credential_id,
       usage.provider_model_id,
       usage.started_at AS usage_started_at,
       usage.input_tokens::bigint AS input_tokens,
       usage.cached_input_tokens::bigint AS cached_input_tokens,
       usage.output_tokens::bigint AS output_tokens,
       price.id AS model_price_id,
       price.currency,
       price.input_price,
       price.cached_input_price,
       price.output_price,
       COALESCE(latest.id, 0)::bigint AS latest_rating_id,
       COALESCE(latest.revision, 0)::int AS latest_revision
FROM usage_record usage
JOIN provider_credential credential
  ON credential.id = usage.provider_credential_id
 AND credential.auth_type = 'API_KEY'
JOIN LATERAL (
    SELECT candidate.id, candidate.provider_credential_id, candidate.provider_model_id, candidate.currency, candidate.input_price, candidate.output_price, candidate.cached_input_price, candidate.effective_at, candidate.created_by, candidate.created_at
    FROM provider_credential_model_price candidate
    WHERE candidate.provider_credential_id = usage.provider_credential_id
      AND candidate.provider_model_id = usage.provider_model_id
      AND candidate.effective_at <= usage.started_at
    ORDER BY candidate.effective_at DESC, candidate.id DESC
    LIMIT 1
) price ON TRUE
LEFT JOIN LATERAL (
    SELECT rating.id, rating.usage_record_id, rating.revision, rating.supersedes_rating_id, rating.principal_id, rating.provider_credential_id, rating.provider_model_id, rating.model_price_id, rating.usage_started_at, rating.input_tokens, rating.cached_input_tokens, rating.output_tokens, rating.input_price, rating.cached_input_price, rating.output_price, rating.input_cost, rating.cached_input_cost, rating.output_cost, rating.total_cost, rating.currency, rating.created_at
    FROM usage_rating rating
    WHERE rating.usage_record_id = usage.id
    ORDER BY rating.revision DESC, rating.id DESC
    LIMIT 1
) latest ON TRUE
WHERE usage.id > $1::bigint
  AND usage.status = 'SUCCESS'
  AND usage.input_tokens IS NOT NULL
  AND usage.cached_input_tokens IS NOT NULL
  AND usage.output_tokens IS NOT NULL
  AND usage.cached_input_tokens <= usage.input_tokens
  AND (
      latest.id IS NULL
      OR latest.model_price_id <> price.id
      OR latest.currency <> price.currency
      OR latest.input_price <> price.input_price
      OR latest.cached_input_price <> price.cached_input_price
      OR latest.output_price <> price.output_price
  )
ORDER BY usage.id
LIMIT $2::int
`

type BillingUsageRatingCandidatesParams struct {
	AfterID   int64
	PageLimit int32
}

type BillingUsageRatingCandidatesRow struct {
	UsageRecordID        int64
	PrincipalID          int64
	ProviderCredentialID int64
	ProviderModelID      int64
	UsageStartedAt       pgtype.Timestamptz
	InputTokens          int64
	CachedInputTokens    int64
	OutputTokens         int64
	ModelPriceID         int64
	Currency             string
	InputPrice           pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	OutputPrice          pgtype.Numeric
	LatestRatingID       int64
	LatestRevision       int32
}

func (q *Queries) BillingUsageRatingCandidates(ctx context.Context, arg BillingUsageRatingCandidatesParams) ([]BillingUsageRatingCandidatesRow, error) {
	rows, err := q.db.Query(ctx, billingUsageRatingCandidates, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingUsageRatingCandidatesRow{}
	for rows.Next() {
		var i BillingUsageRatingCandidatesRow
		if err := rows.Scan(
			&i.UsageRecordID,
			&i.PrincipalID,
			&i.ProviderCredentialID,
			&i.ProviderModelID,
			&i.UsageStartedAt,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ModelPriceID,
			&i.Currency,
			&i.InputPrice,
			&i.CachedInputPrice,
			&i.OutputPrice,
			&i.LatestRatingID,
			&i.LatestRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUsageSubscriptionAllocation = `-- name: BillingUsageSubscriptionAllocation :one
WITH selected AS (
    SELECT usage.principal_id,
           usage.provider_credential_id,
           usage.started_at
    FROM usage_record usage
    JOIN provider_credential credential
      ON credential.id = usage.provider_credential_id
     AND credential.auth_type = 'SUBSCRIPTION'
    WHERE usage.id = $1::bigint
), price AS (
    SELECT candidate.id, candidate.provider_credential_id, candidate.currency, candidate.period_amount, candidate.billing_period, candidate.effective_at, candidate.created_by, candidate.created_at
    FROM selected
    JOIN LATERAL (
        SELECT value.id, value.provider_credential_id, value.currency, value.period_amount, value.billing_period, value.effective_at, value.created_by, value.created_at
        FROM provider_credential_subscription_price value
        WHERE value.provider_credential_id = selected.provider_credential_id
          AND value.effective_at <= selected.started_at
        ORDER BY value.effective_at DESC, value.id DESC
        LIMIT 1
    ) candidate ON TRUE
), base_document AS (
    SELECT document.id, document.period_start, document.period_end
    FROM selected
    JOIN billing_document document
      ON document.provider_credential_id = selected.provider_credential_id
     AND document.billing_type = 'SUBSCRIPTION'
     AND document.document_type = 'CHARGE'
     AND document.status = 'CONFIRMED'
     AND selected.started_at >= document.period_start
     AND selected.started_at < document.period_end
    ORDER BY document.id DESC
    LIMIT 1
), documents AS (
    SELECT id FROM base_document
    UNION ALL
    SELECT adjustment.id
    FROM base_document
    JOIN billing_document adjustment
      ON adjustment.original_document_id = base_document.id
     AND adjustment.document_type = 'ADJUSTMENT'
     AND adjustment.status = 'CONFIRMED'
), allocation AS (
    SELECT SUM(item.amount)::numeric AS principal_amount
    FROM selected
    JOIN billing_document_item item ON item.principal_id = selected.principal_id
    JOIN documents ON documents.id = item.billing_document_id
)
SELECT price.id AS price_id,
       price.currency,
       price.period_amount,
       price.billing_period,
       price.effective_at,
       base_document.id AS document_id,
       base_document.period_start,
       base_document.period_end,
       allocation.principal_amount
FROM price
LEFT JOIN base_document ON TRUE
LEFT JOIN allocation ON TRUE
`

type BillingUsageSubscriptionAllocationRow struct {
	PriceID         int64
	Currency        string
	PeriodAmount    pgtype.Numeric
	BillingPeriod   string
	EffectiveAt     pgtype.Timestamptz
	DocumentID      *int64
	PeriodStart     pgtype.Timestamptz
	PeriodEnd       pgtype.Timestamptz
	PrincipalAmount pgtype.Numeric
}

func (q *Queries) BillingUsageSubscriptionAllocation(ctx context.Context, usageRecordID int64) (BillingUsageSubscriptionAllocationRow, error) {
	row := q.db.QueryRow(ctx, billingUsageSubscriptionAllocation, usageRecordID)
	var i BillingUsageSubscriptionAllocationRow
	err := row.Scan(
		&i.PriceID,
		&i.Currency,
		&i.PeriodAmount,
		&i.BillingPeriod,
		&i.EffectiveAt,
		&i.DocumentID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PrincipalAmount,
	)
	return i, err
}
