// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billingChargePeriods = `-- name: BillingChargePeriods :many
SELECT provider_credential_id, period_start, period_end
FROM billing_document
WHERE billing_type = 'SUBSCRIPTION'
  AND document_type = 'CHARGE'
  AND status = 'CONFIRMED'
ORDER BY provider_credential_id, period_start
`

type BillingChargePeriodsRow struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
}

func (q *Queries) BillingChargePeriods(ctx context.Context) ([]BillingChargePeriodsRow, error) {
	rows, err := q.db.Query(ctx, billingChargePeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingChargePeriodsRow{}
	for rows.Next() {
		var i BillingChargePeriodsRow
		if err := rows.Scan(&i.ProviderCredentialID, &i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingDocumentNetAmount = `-- name: BillingDocumentNetAmount :one
SELECT (base.total_amount + COALESCE(SUM(adjustment.total_amount), 0::numeric))::numeric AS amount
FROM billing_document base
LEFT JOIN billing_document adjustment
  ON adjustment.original_document_id = base.id
 AND adjustment.document_type = 'ADJUSTMENT'
 AND adjustment.status = 'CONFIRMED'
WHERE base.id = $1::bigint
GROUP BY base.id, base.total_amount
`

func (q *Queries) BillingDocumentNetAmount(ctx context.Context, id int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, billingDocumentNetAmount, id)
	var amount pgtype.Numeric
	err := row.Scan(&amount)
	return amount, err
}

const billingInsertDocument = `-- name: BillingInsertDocument :execrows
INSERT INTO billing_document (
    id, status, billing_type, document_type, provider_credential_id,
    source_type, source_id, original_document_id, period_start, period_end,
    total_tokens, total_amount, currency, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14
)
ON CONFLICT (billing_type, provider_credential_id, period_start, period_end)
    WHERE document_type = 'CHARGE' AND status = 'CONFIRMED'
DO NOTHING
`

type BillingInsertDocumentParams struct {
	ID                   int64
	Status               string
	BillingType          string
	DocumentType         string
	ProviderCredentialID int64
	SourceType           string
	SourceID             int64
	OriginalDocumentID   *int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	TotalTokens          int64
	TotalAmount          pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) BillingInsertDocument(ctx context.Context, arg BillingInsertDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, billingInsertDocument,
		arg.ID,
		arg.Status,
		arg.BillingType,
		arg.DocumentType,
		arg.ProviderCredentialID,
		arg.SourceType,
		arg.SourceID,
		arg.OriginalDocumentID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalTokens,
		arg.TotalAmount,
		arg.Currency,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const billingInsertDocumentItem = `-- name: BillingInsertDocumentItem :exec
INSERT INTO billing_document_item (
    id, billing_document_id, principal_id, usage_tokens,
    allocation_ratio, amount, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type BillingInsertDocumentItemParams struct {
	ID                int64
	BillingDocumentID int64
	PrincipalID       int64
	UsageTokens       int64
	AllocationRatio   pgtype.Numeric
	Amount            pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) BillingInsertDocumentItem(ctx context.Context, arg BillingInsertDocumentItemParams) error {
	_, err := q.db.Exec(ctx, billingInsertDocumentItem,
		arg.ID,
		arg.BillingDocumentID,
		arg.PrincipalID,
		arg.UsageTokens,
		arg.AllocationRatio,
		arg.Amount,
		arg.CreatedAt,
	)
	return err
}

const billingLockDocument = `-- name: BillingLockDocument :one
SELECT id
FROM billing_document
WHERE id = $1::bigint
  AND billing_type = 'SUBSCRIPTION'
  AND document_type = 'CHARGE'
  AND status = 'CONFIRMED'
FOR UPDATE
`

func (q *Queries) BillingLockDocument(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, billingLockDocument, id)
	err := row.Scan(&id)
	return id, err
}

const billingOriginalUsage = `-- name: BillingOriginalUsage :many
SELECT principal_id, usage_tokens AS tokens
FROM billing_document_item
WHERE billing_document_id = $1::bigint
  AND usage_tokens > 0
ORDER BY usage_tokens DESC, principal_id
`

type BillingOriginalUsageRow struct {
	PrincipalID int64
	Tokens      int64
}

func (q *Queries) BillingOriginalUsage(ctx context.Context, billingDocumentID int64) ([]BillingOriginalUsageRow, error) {
	rows, err := q.db.Query(ctx, billingOriginalUsage, billingDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingOriginalUsageRow{}
	for rows.Next() {
		var i BillingOriginalUsageRow
		if err := rows.Scan(&i.PrincipalID, &i.Tokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingStatisticsPrincipals = `-- name: BillingStatisticsPrincipals :many
SELECT item.principal_id,
       principal.name AS principal_name,
       principal.principal_type,
       document.billing_type,
       document.currency,
       SUM(item.amount)::numeric AS amount,
       SUM(CASE WHEN document.document_type = 'CHARGE' THEN item.usage_tokens ELSE 0 END)::bigint AS tokens,
       COUNT(*) OVER ()::bigint AS total_count
FROM billing_document_item item
JOIN billing_document document ON document.id = item.billing_document_id
JOIN principal ON principal.id = item.principal_id
WHERE document.status = 'CONFIRMED'
  AND document.period_start >= $1::timestamptz
  AND document.period_start < $2::timestamptz
  AND ($3::text = '' OR document.billing_type = $3::text)
GROUP BY item.principal_id, principal.name, principal.principal_type, document.billing_type, document.currency
ORDER BY amount DESC, item.principal_id, document.billing_type, document.currency
LIMIT $5::int OFFSET $4::bigint
`

type BillingStatisticsPrincipalsParams struct {
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	BillingType string
	PageOffset  int64
	PageLimit   int32
}

type BillingStatisticsPrincipalsRow struct {
	PrincipalID   int64
	PrincipalName string
	PrincipalType string
	BillingType   string
	Currency      string
	Amount        pgtype.Numeric
	Tokens        int64
	TotalCount    int64
}

func (q *Queries) BillingStatisticsPrincipals(ctx context.Context, arg BillingStatisticsPrincipalsParams) ([]BillingStatisticsPrincipalsRow, error) {
	rows, err := q.db.Query(ctx, billingStatisticsPrincipals,
		arg.FromTime,
		arg.ToTime,
		arg.BillingType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingStatisticsPrincipalsRow{}
	for rows.Next() {
		var i BillingStatisticsPrincipalsRow
		if err := rows.Scan(
			&i.PrincipalID,
			&i.PrincipalName,
			&i.PrincipalType,
			&i.BillingType,
			&i.Currency,
			&i.Amount,
			&i.Tokens,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingStatisticsTotals = `-- name: BillingStatisticsTotals :many
WITH item_total AS (
    SELECT billing_document_id, SUM(amount) AS amount
    FROM billing_document_item
    GROUP BY billing_document_id
)
SELECT document.currency,
       document.billing_type,
       SUM(document.total_amount)::numeric AS total_amount,
       SUM(COALESCE(item_total.amount, 0::numeric))::numeric AS allocated_amount,
       SUM(document.total_amount - COALESCE(item_total.amount, 0::numeric))::numeric AS unallocated_amount,
       SUM(CASE WHEN document.document_type = 'CHARGE' THEN document.total_tokens ELSE 0 END)::bigint AS total_tokens
FROM billing_document document
LEFT JOIN item_total ON item_total.billing_document_id = document.id
WHERE document.status = 'CONFIRMED'
  AND document.period_start >= $1::timestamptz
  AND document.period_start < $2::timestamptz
  AND ($3::text = '' OR document.billing_type = $3::text)
GROUP BY document.billing_type, document.currency
ORDER BY document.billing_type, document.currency
`

type BillingStatisticsTotalsParams struct {
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	BillingType string
}

type BillingStatisticsTotalsRow struct {
	Currency          string
	BillingType       string
	TotalAmount       pgtype.Numeric
	AllocatedAmount   pgtype.Numeric
	UnallocatedAmount pgtype.Numeric
	TotalTokens       int64
}

func (q *Queries) BillingStatisticsTotals(ctx context.Context, arg BillingStatisticsTotalsParams) ([]BillingStatisticsTotalsRow, error) {
	rows, err := q.db.Query(ctx, billingStatisticsTotals, arg.FromTime, arg.ToTime, arg.BillingType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingStatisticsTotalsRow{}
	for rows.Next() {
		var i BillingStatisticsTotalsRow
		if err := rows.Scan(
			&i.Currency,
			&i.BillingType,
			&i.TotalAmount,
			&i.AllocatedAmount,
			&i.UnallocatedAmount,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingSubscriptionCorrections = `-- name: BillingSubscriptionCorrections :many
WITH adjustment AS (
    SELECT original_document_id, SUM(total_amount) AS amount
    FROM billing_document
    WHERE billing_type = 'SUBSCRIPTION'
      AND document_type = 'ADJUSTMENT'
      AND status = 'CONFIRMED'
    GROUP BY original_document_id
)
SELECT base.id AS original_document_id,
       base.provider_credential_id,
       base.source_id AS source_price_id,
       base.period_start,
       base.period_end,
       base.currency,
       price.currency AS target_currency,
       (base.total_amount + COALESCE(adjustment.amount, 0::numeric))::numeric AS current_amount,
       price.period_amount AS target_amount
FROM billing_document base
JOIN provider_credential_subscription_price price
  ON base.source_type = 'SUBSCRIPTION_PRICE' AND price.id = base.source_id
LEFT JOIN adjustment ON adjustment.original_document_id = base.id
WHERE base.billing_type = 'SUBSCRIPTION'
  AND base.document_type = 'CHARGE'
  AND base.status = 'CONFIRMED'
  AND (
      base.currency <> price.currency
      OR base.total_amount + COALESCE(adjustment.amount, 0::numeric) <> price.period_amount
  )
ORDER BY base.id
`

type BillingSubscriptionCorrectionsRow struct {
	OriginalDocumentID   int64
	ProviderCredentialID int64
	SourcePriceID        int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
	Currency             string
	TargetCurrency       string
	CurrentAmount        pgtype.Numeric
	TargetAmount         pgtype.Numeric
}

func (q *Queries) BillingSubscriptionCorrections(ctx context.Context) ([]BillingSubscriptionCorrectionsRow, error) {
	rows, err := q.db.Query(ctx, billingSubscriptionCorrections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSubscriptionCorrectionsRow{}
	for rows.Next() {
		var i BillingSubscriptionCorrectionsRow
		if err := rows.Scan(
			&i.OriginalDocumentID,
			&i.ProviderCredentialID,
			&i.SourcePriceID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Currency,
			&i.TargetCurrency,
			&i.CurrentAmount,
			&i.TargetAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingSubscriptionPrices = `-- name: BillingSubscriptionPrices :many
SELECT p.id, p.provider_credential_id, p.currency, p.period_amount,
       p.billing_period, p.effective_at,
       COALESCE(c.effective_at, p.effective_at)::timestamptz AS credential_effective_at,
       CASE WHEN c.is_deleted THEN c.updated_at ELSE c.expires_at END::timestamptz AS credential_end_at
FROM provider_credential_subscription_price p
JOIN provider_credential c ON c.id = p.provider_credential_id
WHERE c.auth_type = 'SUBSCRIPTION'
  AND c.subscription_type = 'PERSONAL'
ORDER BY p.provider_credential_id, p.effective_at, p.id
`

type BillingSubscriptionPricesRow struct {
	ID                    int64
	ProviderCredentialID  int64
	Currency              string
	PeriodAmount          pgtype.Numeric
	BillingPeriod         string
	EffectiveAt           pgtype.Timestamptz
	CredentialEffectiveAt pgtype.Timestamptz
	CredentialEndAt       pgtype.Timestamptz
}

func (q *Queries) BillingSubscriptionPrices(ctx context.Context) ([]BillingSubscriptionPricesRow, error) {
	rows, err := q.db.Query(ctx, billingSubscriptionPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSubscriptionPricesRow{}
	for rows.Next() {
		var i BillingSubscriptionPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCredentialID,
			&i.Currency,
			&i.PeriodAmount,
			&i.BillingPeriod,
			&i.EffectiveAt,
			&i.CredentialEffectiveAt,
			&i.CredentialEndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingSubscriptionUsage = `-- name: BillingSubscriptionUsage :many
SELECT principal_id,
       SUM(COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0))::bigint AS tokens
FROM usage_record
WHERE provider_credential_id = $1::bigint
  AND status = 'SUCCESS'
  AND started_at >= $2::timestamptz
  AND started_at < $3::timestamptz
GROUP BY principal_id
HAVING SUM(COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0)) > 0
ORDER BY tokens DESC, principal_id
`

type BillingSubscriptionUsageParams struct {
	ProviderCredentialID int64
	PeriodStart          pgtype.Timestamptz
	PeriodEnd            pgtype.Timestamptz
}

type BillingSubscriptionUsageRow struct {
	PrincipalID int64
	Tokens      int64
}

func (q *Queries) BillingSubscriptionUsage(ctx context.Context, arg BillingSubscriptionUsageParams) ([]BillingSubscriptionUsageRow, error) {
	rows, err := q.db.Query(ctx, billingSubscriptionUsage, arg.ProviderCredentialID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSubscriptionUsageRow{}
	for rows.Next() {
		var i BillingSubscriptionUsageRow
		if err := rows.Scan(&i.PrincipalID, &i.Tokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
