// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bootstrap.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bootstrapInitialized = `-- name: BootstrapInitialized :one
SELECT EXISTS (SELECT 1 FROM organization WHERE is_deleted = false)
`

// 只检查首次初始化的事实，不恢复已删除的组织。
func (q *Queries) BootstrapInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, bootstrapInitialized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBootstrapOrganization = `-- name: CreateBootstrapOrganization :exec
INSERT INTO organization (id, organization_code, organization_name, status, created_by, updated_by, created_at, updated_at)
VALUES ($1, $2, $3, 'ACTIVE', 'system', 'system', $4, $4)
`

type CreateBootstrapOrganizationParams struct {
	ID               int64
	OrganizationCode string
	OrganizationName string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateBootstrapOrganization(ctx context.Context, arg CreateBootstrapOrganizationParams) error {
	_, err := q.db.Exec(ctx, createBootstrapOrganization,
		arg.ID,
		arg.OrganizationCode,
		arg.OrganizationName,
		arg.CreatedAt,
	)
	return err
}

const createBootstrapProvider = `-- name: CreateBootstrapProvider :exec
INSERT INTO provider (id, provider_code, provider_name, provider_type, status, created_by, updated_by, created_at, updated_at)
VALUES ($1, $2, $3, 'OFFICIAL', 'ACTIVE', 'system', 'system', $4, $4)
`

type CreateBootstrapProviderParams struct {
	ID           int64
	ProviderCode string
	ProviderName string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateBootstrapProvider(ctx context.Context, arg CreateBootstrapProviderParams) error {
	_, err := q.db.Exec(ctx, createBootstrapProvider,
		arg.ID,
		arg.ProviderCode,
		arg.ProviderName,
		arg.CreatedAt,
	)
	return err
}

const createBootstrapProviderEndpoint = `-- name: CreateBootstrapProviderEndpoint :exec
INSERT INTO provider_endpoint(provider_id, protocol_type, base_url, created_by, updated_by, created_at, updated_at)
VALUES($1, $2, $3, 'system', 'system', $4, $4)
`

type CreateBootstrapProviderEndpointParams struct {
	ProviderID   int64
	ProtocolType string
	BaseUrl      string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateBootstrapProviderEndpoint(ctx context.Context, arg CreateBootstrapProviderEndpointParams) error {
	_, err := q.db.Exec(ctx, createBootstrapProviderEndpoint,
		arg.ProviderID,
		arg.ProtocolType,
		arg.BaseUrl,
		arg.CreatedAt,
	)
	return err
}

const hasOrganizationHistory = `-- name: HasOrganizationHistory :one
SELECT EXISTS (SELECT 1 FROM organization)
`

func (q *Queries) HasOrganizationHistory(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrganizationHistory)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
