// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package dbgen

import (
	"context"
)

const getAccessKeyByHash = `-- name: GetAccessKeyByHash :one
SELECT id, is_deleted, organization_id, principal_id, key_hash, masked_key, name, status, expires_at, last_used_at, revoked_at, created_by, updated_by, created_at, updated_at FROM access_key WHERE key_hash = $1 AND is_deleted = false
`

// 这里只定位凭证；完整认证和撤销/过期判断在阶段 2/4 实现。
func (q *Queries) GetAccessKeyByHash(ctx context.Context, keyHash []byte) (AccessKey, error) {
	row := q.db.QueryRow(ctx, getAccessKeyByHash, keyHash)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.PrincipalID,
		&i.KeyHash,
		&i.MaskedKey,
		&i.Name,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, is_deleted, organization_id, username, password_hash, display_name, status, failed_login_count, locked_until, last_login_at, created_by, updated_by, created_at, updated_at, credential_version FROM admin_user WHERE organization_id = $1 AND username = $2 AND is_deleted = false
`

type GetAdminByUsernameParams struct {
	OrganizationID int64
	Username       string
}

func (q *Queries) GetAdminByUsername(ctx context.Context, arg GetAdminByUsernameParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, arg.OrganizationID, arg.Username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, is_deleted, organization_code, organization_name, status, remark, created_by, updated_by, created_at, updated_at FROM organization WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationCode,
		&i.OrganizationName,
		&i.Status,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, is_deleted, organization_id, principal_type, name, remark, status, created_by, updated_by, created_at, updated_at FROM principal WHERE organization_id = $1 AND id = $2 AND is_deleted = false
`

type GetPrincipalParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) GetPrincipal(ctx context.Context, arg GetPrincipalParams) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipal, arg.OrganizationID, arg.ID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.PrincipalType,
		&i.Name,
		&i.Remark,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, is_deleted, provider_code, provider_name, provider_type, status, created_by, updated_by, created_at, updated_at, official_website, proxy_enabled, proxy_url_display, proxy_url_ciphertext, proxy_url_nonce, proxy_url_key_version, proxy_header_names, proxy_headers_ciphertext, proxy_headers_nonce, proxy_headers_key_version FROM ai_provider WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetProvider(ctx context.Context, id int64) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.ProviderCode,
		&i.ProviderName,
		&i.ProviderType,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfficialWebsite,
		&i.ProxyEnabled,
		&i.ProxyUrlDisplay,
		&i.ProxyUrlCiphertext,
		&i.ProxyUrlNonce,
		&i.ProxyUrlKeyVersion,
		&i.ProxyHeaderNames,
		&i.ProxyHeadersCiphertext,
		&i.ProxyHeadersNonce,
		&i.ProxyHeadersKeyVersion,
	)
	return i, err
}

const getProviderModel = `-- name: GetProviderModel :one
SELECT id, is_deleted, provider_id, model_id, upstream_model_code, created_by, updated_by, created_at, updated_at, priority FROM provider_model WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetProviderModel(ctx context.Context, id int64) (ProviderModel, error) {
	row := q.db.QueryRow(ctx, getProviderModel, id)
	var i ProviderModel
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.ProviderID,
		&i.ModelID,
		&i.UpstreamModelCode,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT id, is_deleted, organization_id, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, status, last_active_at, created_by, updated_by, created_at, updated_at FROM ai_resource WHERE organization_id = $1 AND id = $2 AND is_deleted = false
`

type GetResourceParams struct {
	OrganizationID int64
	ID             int64
}

// 包含加密凭证，仅供内部 Repository 使用，禁止直接序列化为 API 响应。
func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (AiResource, error) {
	row := q.db.QueryRow(ctx, getResource, arg.OrganizationID, arg.ID)
	var i AiResource
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.ProviderID,
		&i.ResourceName,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.KeyVersion,
		&i.Status,
		&i.LastActiveAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasGroupModelPermission = `-- name: HasGroupModelPermission :one
SELECT EXISTS (
  SELECT 1 FROM principal p
  JOIN organization o ON o.id = p.organization_id
  JOIN principal_group pg ON pg.principal_id = p.id AND pg.organization_id = p.organization_id
  JOIN ai_group g ON g.id = pg.group_id AND g.organization_id = p.organization_id
  JOIN group_model_permission permission ON permission.group_id = g.id AND permission.organization_id = p.organization_id
  JOIN ai_model m ON m.id = permission.model_id
  WHERE p.organization_id = $1 AND p.id = $2 AND m.id = $3
    AND p.principal_type = 'MEMBER' AND p.status = 'ACTIVE' AND p.is_deleted = false
    AND o.status = 'ACTIVE' AND o.is_deleted = false
    AND pg.is_deleted = false AND g.status = 'ACTIVE' AND g.is_deleted = false
    AND permission.is_deleted = false AND m.status = 'ACTIVE' AND m.is_deleted = false
)
`

type HasGroupModelPermissionParams struct {
	OrganizationID int64
	PrincipalID    int64
	ModelID        int64
}

// Default Deny：没有匹配的显式有效授权即返回 false；多组通过 EXISTS 取并集。
func (q *Queries) HasGroupModelPermission(ctx context.Context, arg HasGroupModelPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasGroupModelPermission, arg.OrganizationID, arg.PrincipalID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupsForPrincipal = `-- name: ListGroupsForPrincipal :many
SELECT g.id, g.is_deleted, g.organization_id, g.group_code, g.group_name, g.remark, g.status, g.created_by, g.updated_by, g.created_at, g.updated_at FROM ai_group g
JOIN principal_group pg ON pg.group_id = g.id AND pg.organization_id = g.organization_id
WHERE pg.organization_id = $1 AND pg.principal_id = $2
  AND pg.is_deleted = false AND g.is_deleted = false AND g.status = 'ACTIVE'
ORDER BY g.id
`

type ListGroupsForPrincipalParams struct {
	OrganizationID int64
	PrincipalID    int64
}

func (q *Queries) ListGroupsForPrincipal(ctx context.Context, arg ListGroupsForPrincipalParams) ([]AiGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForPrincipal, arg.OrganizationID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiGroup{}
	for rows.Next() {
		var i AiGroup
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.OrganizationID,
			&i.GroupCode,
			&i.GroupName,
			&i.Remark,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, is_deleted, model_code, display_name, status, created_by, updated_by, created_at, updated_at, input_modalities, output_modalities, remark FROM ai_model WHERE is_deleted = false ORDER BY id
`

func (q *Queries) ListModels(ctx context.Context) ([]AiModel, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiModel{}
	for rows.Next() {
		var i AiModel
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.ModelCode,
			&i.DisplayName,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InputModalities,
			&i.OutputModalities,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
