// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package dbgen

import (
	"context"
)

const getAccessKeyByHash = `-- name: GetAccessKeyByHash :one
SELECT id, is_deleted, status, principal_id, key_hash, masked_key, name, expires_at, last_used_at, revoked_at, created_by, updated_by, created_at, updated_at FROM principal_access_key WHERE key_hash = $1 AND is_deleted = false
`

// 这里只定位凭证；完整认证和撤销/过期判断在阶段 2/4 实现。
func (q *Queries) GetAccessKeyByHash(ctx context.Context, keyHash []byte) (PrincipalAccessKey, error) {
	row := q.db.QueryRow(ctx, getAccessKeyByHash, keyHash)
	var i PrincipalAccessKey
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.PrincipalID,
		&i.KeyHash,
		&i.MaskedKey,
		&i.Name,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, is_deleted, status, username, password_hash, display_name, failed_login_count, locked_until, last_login_at, credential_version, created_by, updated_by, created_at, updated_at FROM admin_user WHERE username = $1 AND is_deleted = false
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CredentialVersion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, is_deleted, status, principal_type, name, remark, created_by, updated_by, created_at, updated_at FROM principal WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetPrincipal(ctx context.Context, id int64) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.PrincipalType,
		&i.Name,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, is_deleted, status, provider_code, provider_name, provider_type, official_website, proxy_enabled, proxy_url_display, proxy_url_ciphertext, proxy_url_nonce, proxy_url_key_version, proxy_header_names, proxy_headers_ciphertext, proxy_headers_nonce, proxy_headers_key_version, created_by, updated_by, created_at, updated_at FROM provider WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.ProviderCode,
		&i.ProviderName,
		&i.ProviderType,
		&i.OfficialWebsite,
		&i.ProxyEnabled,
		&i.ProxyUrlDisplay,
		&i.ProxyUrlCiphertext,
		&i.ProxyUrlNonce,
		&i.ProxyUrlKeyVersion,
		&i.ProxyHeaderNames,
		&i.ProxyHeadersCiphertext,
		&i.ProxyHeadersNonce,
		&i.ProxyHeadersKeyVersion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderModel = `-- name: GetProviderModel :one
SELECT id, is_deleted, provider_id, model_id, upstream_model_code, created_by, updated_by, created_at, updated_at, priority FROM provider_model WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetProviderModel(ctx context.Context, id int64) (ProviderModel, error) {
	row := q.db.QueryRow(ctx, getProviderModel, id)
	var i ProviderModel
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.ProviderID,
		&i.ModelID,
		&i.UpstreamModelCode,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT id, is_deleted, status, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, created_by, updated_by, created_at, updated_at, runtime_status, blocked_reason, blocked_at, last_error_at, last_http_status, last_error_code FROM provider_credential WHERE id = $1 AND is_deleted = false
`

// 包含加密凭证，仅供内部 Repository 使用，禁止直接序列化为 API 响应。
func (q *Queries) GetResource(ctx context.Context, id int64) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.ProviderID,
		&i.ResourceName,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.KeyVersion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeStatus,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.LastErrorAt,
		&i.LastHttpStatus,
		&i.LastErrorCode,
	)
	return i, err
}

const hasGroupModelPermission = `-- name: HasGroupModelPermission :one
SELECT EXISTS (
  SELECT 1 FROM principal p
  JOIN principal_group_membership pg ON pg.principal_id = p.id
  JOIN principal_group g ON g.id = pg.group_id
  JOIN principal_group_model_permission permission ON permission.group_id = g.id
  JOIN model m ON m.id = permission.model_id
  WHERE p.id = $1 AND m.id = $2
    AND p.principal_type = 'MEMBER' AND p.status = 'ACTIVE' AND p.is_deleted = false
    AND pg.is_deleted = false AND g.status = 'ACTIVE' AND g.is_deleted = false
    AND permission.is_deleted = false AND m.status = 'ACTIVE' AND m.is_deleted = false
)
`

type HasGroupModelPermissionParams struct {
	PrincipalID int64
	ModelID     int64
}

// Default Deny：没有匹配的显式有效授权即返回 false；多组通过 EXISTS 取并集。
func (q *Queries) HasGroupModelPermission(ctx context.Context, arg HasGroupModelPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasGroupModelPermission, arg.PrincipalID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupsForPrincipal = `-- name: ListGroupsForPrincipal :many
SELECT g.id, g.is_deleted, g.status, g.group_code, g.group_name, g.remark, g.created_by, g.updated_by, g.created_at, g.updated_at FROM principal_group g
JOIN principal_group_membership pg ON pg.group_id = g.id
WHERE pg.principal_id = $1
  AND pg.is_deleted = false AND g.is_deleted = false AND g.status = 'ACTIVE'
ORDER BY g.id
`

func (q *Queries) ListGroupsForPrincipal(ctx context.Context, principalID int64) ([]PrincipalGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrincipalGroup{}
	for rows.Next() {
		var i PrincipalGroup
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.GroupCode,
			&i.GroupName,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, is_deleted, status, model_code, display_name, input_modalities, output_modalities, remark, created_by, updated_by, created_at, updated_at, publisher_provider_id FROM model WHERE is_deleted = false ORDER BY id
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.ModelCode,
			&i.DisplayName,
			&i.InputModalities,
			&i.OutputModalities,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublisherProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
