// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deepseek.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogMappingHistory = `-- name: CatalogMappingHistory :many
SELECT provider_id,upstream_model_code,is_deleted FROM provider_model WHERE model_id=$1
`

type CatalogMappingHistoryRow struct {
	ProviderID        int64
	UpstreamModelCode string
	IsDeleted         bool
}

func (q *Queries) CatalogMappingHistory(ctx context.Context, modelID int64) ([]CatalogMappingHistoryRow, error) {
	rows, err := q.db.Query(ctx, catalogMappingHistory, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogMappingHistoryRow{}
	for rows.Next() {
		var i CatalogMappingHistoryRow
		if err := rows.Scan(&i.ProviderID, &i.UpstreamModelCode, &i.IsDeleted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogModelHistory = `-- name: CatalogModelHistory :many
SELECT id FROM ai_model WHERE model_code=$1
`

func (q *Queries) CatalogModelHistory(ctx context.Context, modelCode string) ([]int64, error) {
	rows, err := q.db.Query(ctx, catalogModelHistory, modelCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deepSeekProviderHistory = `-- name: DeepSeekProviderHistory :many
SELECT p.id,p.provider_type,
       coalesce((SELECT base_url FROM provider_endpoint WHERE provider_id=p.id AND protocol_type='ANTHROPIC_MESSAGES'), ''::varchar(2048))::text AS anthropic_base_url,
       coalesce((SELECT base_url FROM provider_endpoint WHERE provider_id=p.id AND protocol_type='OPENAI_CHAT'), ''::varchar(2048))::text AS openai_base_url
FROM ai_provider p WHERE p.provider_code='deepseek-official'
`

type DeepSeekProviderHistoryRow struct {
	ID               int64
	ProviderType     string
	AnthropicBaseUrl string
	OpenaiBaseUrl    string
}

// 包括软删除历史，防止 setup 命令恢复或覆盖管理员的配置。
func (q *Queries) DeepSeekProviderHistory(ctx context.Context) ([]DeepSeekProviderHistoryRow, error) {
	rows, err := q.db.Query(ctx, deepSeekProviderHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeepSeekProviderHistoryRow{}
	for rows.Next() {
		var i DeepSeekProviderHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderType,
			&i.AnthropicBaseUrl,
			&i.OpenaiBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setupDeepSeekOpenAIEndpoint = `-- name: SetupDeepSeekOpenAIEndpoint :exec
INSERT INTO provider_endpoint(provider_id,protocol_type,base_url,created_by,updated_by,created_at,updated_at)
VALUES($1,'OPENAI_CHAT','https://api.deepseek.com','system','system',$2,$2)
ON CONFLICT(provider_id,protocol_type) DO NOTHING
`

type SetupDeepSeekOpenAIEndpointParams struct {
	ProviderID int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) SetupDeepSeekOpenAIEndpoint(ctx context.Context, arg SetupDeepSeekOpenAIEndpointParams) error {
	_, err := q.db.Exec(ctx, setupDeepSeekOpenAIEndpoint, arg.ProviderID, arg.CreatedAt)
	return err
}
