// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deepseek.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogMappingHistory = `-- name: CatalogMappingHistory :many
SELECT provider_id, upstream_model_code, protocol_type,status,is_deleted FROM provider_model WHERE model_id=$1 AND protocol_type=$2
`

type CatalogMappingHistoryParams struct {
	ModelID      int64
	ProtocolType string
}

type CatalogMappingHistoryRow struct {
	ProviderID        int64
	UpstreamModelCode string
	ProtocolType      string
	Status            string
	IsDeleted         bool
}

func (q *Queries) CatalogMappingHistory(ctx context.Context, arg CatalogMappingHistoryParams) ([]CatalogMappingHistoryRow, error) {
	rows, err := q.db.Query(ctx, catalogMappingHistory, arg.ModelID, arg.ProtocolType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogMappingHistoryRow{}
	for rows.Next() {
		var i CatalogMappingHistoryRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.UpstreamModelCode,
			&i.ProtocolType,
			&i.Status,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogModelHistory = `-- name: CatalogModelHistory :many
SELECT id FROM ai_model WHERE model_code=$1
`

func (q *Queries) CatalogModelHistory(ctx context.Context, modelCode string) ([]int64, error) {
	rows, err := q.db.Query(ctx, catalogModelHistory, modelCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDeepSeekOpenAIModel = `-- name: CreateDeepSeekOpenAIModel :exec
INSERT INTO provider_model(id,provider_id,model_id,upstream_model_code,protocol_type,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,'OPENAI',$5,'system','system',$6,$6)
`

type CreateDeepSeekOpenAIModelParams struct {
	ID                int64
	ProviderID        int64
	ModelID           int64
	UpstreamModelCode string
	Status            string
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateDeepSeekOpenAIModel(ctx context.Context, arg CreateDeepSeekOpenAIModelParams) error {
	_, err := q.db.Exec(ctx, createDeepSeekOpenAIModel,
		arg.ID,
		arg.ProviderID,
		arg.ModelID,
		arg.UpstreamModelCode,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const deepSeekProviderHistory = `-- name: DeepSeekProviderHistory :many
SELECT id, provider_type, anthropic_base_url,openai_base_url FROM ai_provider WHERE provider_code='deepseek-official'
`

type DeepSeekProviderHistoryRow struct {
	ID               int64
	ProviderType     string
	AnthropicBaseUrl string
	OpenaiBaseUrl    *string
}

// 包括软删除历史，防止 setup 命令恢复或覆盖管理员的配置。
func (q *Queries) DeepSeekProviderHistory(ctx context.Context) ([]DeepSeekProviderHistoryRow, error) {
	rows, err := q.db.Query(ctx, deepSeekProviderHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeepSeekProviderHistoryRow{}
	for rows.Next() {
		var i DeepSeekProviderHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderType,
			&i.AnthropicBaseUrl,
			&i.OpenaiBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setupDeepSeekOpenAIURL = `-- name: SetupDeepSeekOpenAIURL :exec
UPDATE ai_provider SET openai_base_url='https://api.deepseek.com' WHERE id=$1 AND openai_base_url IS NULL
`

func (q *Queries) SetupDeepSeekOpenAIURL(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setupDeepSeekOpenAIURL, id)
	return err
}
