// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockGatewayResource = `-- name: BlockGatewayResource :execrows
UPDATE provider_credential
SET runtime_status='BLOCKED',blocked_reason=$1,blocked_at=$2,
    last_error_at=$2,last_http_status=$3,
    last_error_code=$4,updated_by='system',updated_at=$2
WHERE id=$5
  AND NOT is_deleted AND status='ACTIVE' AND runtime_status='HEALTHY'
`

type BlockGatewayResourceParams struct {
	BlockedReason *string
	BlockedAt     pgtype.Timestamptz
	HttpStatus    *int32
	ErrorCode     *string
	ResourceID    int64
}

func (q *Queries) BlockGatewayResource(ctx context.Context, arg BlockGatewayResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockGatewayResource,
		arg.BlockedReason,
		arg.BlockedAt,
		arg.HttpStatus,
		arg.ErrorCode,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const gatewayCandidates = `-- name: GatewayCandidates :many
SELECT pm.id AS provider_model_id,pm.provider_id,pm.upstream_model_code,pe.base_url,pe.protocol_type,
       p.proxy_enabled,p.proxy_url_ciphertext,p.proxy_url_nonce,p.proxy_url_key_version,
       p.proxy_headers_ciphertext,p.proxy_headers_nonce,p.proxy_headers_key_version,
       r.id AS resource_id,r.credential_ciphertext,r.credential_nonce,r.key_version
FROM provider_model pm
JOIN provider p ON p.id=pm.provider_id
JOIN provider_endpoint pe ON pe.provider_id=p.id AND pe.protocol_type IN ('OPENAI','ANTHROPIC')
JOIN provider_credential r ON r.provider_id=p.id
    AND NOT r.is_deleted AND r.status='ACTIVE' AND r.runtime_status='HEALTHY'
WHERE pm.model_id=$1 AND NOT pm.is_deleted
  AND NOT p.is_deleted AND p.status='ACTIVE'
ORDER BY pm.priority,
    CASE WHEN pe.protocol_type=$2 THEN 0 ELSE 1 END,
    pm.id,r.id
`

type GatewayCandidatesParams struct {
	ModelID           int64
	PreferredProtocol string
}

type GatewayCandidatesRow struct {
	ProviderModelID        int64
	ProviderID             int64
	UpstreamModelCode      string
	BaseUrl                string
	ProtocolType           string
	ProxyEnabled           bool
	ProxyUrlCiphertext     []byte
	ProxyUrlNonce          []byte
	ProxyUrlKeyVersion     *int32
	ProxyHeadersCiphertext []byte
	ProxyHeadersNonce      []byte
	ProxyHeadersKeyVersion *int32
	ResourceID             int64
	CredentialCiphertext   []byte
	CredentialNonce        []byte
	KeyVersion             int32
}

func (q *Queries) GatewayCandidates(ctx context.Context, arg GatewayCandidatesParams) ([]GatewayCandidatesRow, error) {
	rows, err := q.db.Query(ctx, gatewayCandidates, arg.ModelID, arg.PreferredProtocol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayCandidatesRow{}
	for rows.Next() {
		var i GatewayCandidatesRow
		if err := rows.Scan(
			&i.ProviderModelID,
			&i.ProviderID,
			&i.UpstreamModelCode,
			&i.BaseUrl,
			&i.ProtocolType,
			&i.ProxyEnabled,
			&i.ProxyUrlCiphertext,
			&i.ProxyUrlNonce,
			&i.ProxyUrlKeyVersion,
			&i.ProxyHeadersCiphertext,
			&i.ProxyHeadersNonce,
			&i.ProxyHeadersKeyVersion,
			&i.ResourceID,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gatewayIdentityActive = `-- name: GatewayIdentityActive :one
SELECT EXISTS (SELECT 1 FROM principal_access_key k
JOIN principal p ON p.id=k.principal_id
WHERE k.id=$1 AND k.principal_id=$2
AND NOT k.is_deleted AND k.status='ACTIVE' AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at>now())
AND NOT p.is_deleted AND p.status='ACTIVE' AND p.principal_type='MEMBER')
`

type GatewayIdentityActiveParams struct {
	AccessKeyID int64
	PrincipalID int64
}

func (q *Queries) GatewayIdentityActive(ctx context.Context, arg GatewayIdentityActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, gatewayIdentityActive, arg.AccessKeyID, arg.PrincipalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const gatewayModel = `-- name: GatewayModel :one
SELECT id,status FROM model WHERE model_code=$1 AND NOT is_deleted
`

type GatewayModelRow struct {
	ID     int64
	Status string
}

func (q *Queries) GatewayModel(ctx context.Context, modelCode string) (GatewayModelRow, error) {
	row := q.db.QueryRow(ctx, gatewayModel, modelCode)
	var i GatewayModelRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const gatewayRouteExists = `-- name: GatewayRouteExists :one
SELECT EXISTS(
    SELECT 1
    FROM provider_model pm
    JOIN provider p ON p.id=pm.provider_id
    JOIN provider_endpoint pe ON pe.provider_id=p.id AND pe.protocol_type IN ('OPENAI','ANTHROPIC')
    WHERE pm.model_id=$1 AND NOT pm.is_deleted
      AND NOT p.is_deleted AND p.status='ACTIVE'
)
`

func (q *Queries) GatewayRouteExists(ctx context.Context, modelID int64) (bool, error) {
	row := q.db.QueryRow(ctx, gatewayRouteExists, modelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const openAIModels = `-- name: OpenAIModels :many
SELECT DISTINCT ON (m.model_code) m.model_code,m.created_at,p.provider_code FROM model m
JOIN provider_model pm ON pm.model_id=m.id AND NOT pm.is_deleted
JOIN provider p ON p.id=pm.provider_id AND NOT p.is_deleted AND p.status='ACTIVE'
JOIN provider_endpoint pe ON pe.provider_id=p.id AND pe.protocol_type IN ('OPENAI','ANTHROPIC')
WHERE NOT m.is_deleted AND m.status='ACTIVE'
AND EXISTS(SELECT 1 FROM provider_credential r WHERE r.provider_id=p.id AND NOT r.is_deleted AND r.status='ACTIVE' AND r.runtime_status='HEALTHY')
AND EXISTS(SELECT 1 FROM principal_group_membership pg JOIN principal_group g ON g.id=pg.group_id
JOIN principal_group_model_permission gp ON gp.group_id=g.id
WHERE pg.principal_id=$1
AND NOT pg.is_deleted AND NOT g.is_deleted AND g.status='ACTIVE' AND NOT gp.is_deleted AND gp.model_id=m.id)
ORDER BY m.model_code,CASE pe.protocol_type WHEN 'OPENAI' THEN 0 ELSE 1 END,pm.priority,pm.id
`

type OpenAIModelsRow struct {
	ModelCode    string
	CreatedAt    pgtype.Timestamptz
	ProviderCode string
}

func (q *Queries) OpenAIModels(ctx context.Context, principalID int64) ([]OpenAIModelsRow, error) {
	rows, err := q.db.Query(ctx, openAIModels, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenAIModelsRow{}
	for rows.Next() {
		var i OpenAIModelsRow
		if err := rows.Scan(&i.ModelCode, &i.CreatedAt, &i.ProviderCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
