// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockGatewayResource = `-- name: BlockGatewayResource :execrows
UPDATE provider_credential
SET runtime_status='BLOCKED',blocked_reason=$1,blocked_at=$2,
    last_error_at=$2,last_http_status=$3,
    last_error_code=$4,updated_by='system',updated_at=$2
WHERE id=$5
  AND NOT is_deleted AND runtime_status='HEALTHY'
`

type BlockGatewayResourceParams struct {
	BlockedReason *string
	BlockedAt     pgtype.Timestamptz
	HttpStatus    *int32
	ErrorCode     *string
	ResourceID    int64
}

func (q *Queries) BlockGatewayResource(ctx context.Context, arg BlockGatewayResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockGatewayResource,
		arg.BlockedReason,
		arg.BlockedAt,
		arg.HttpStatus,
		arg.ErrorCode,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const gatewayCandidates = `-- name: GatewayCandidates :many
SELECT pm.id AS provider_model_id,pm.provider_id,p.provider_name,pm.upstream_model_code,pe.base_url,pe.protocol_type,pe.network_scope,
       p.proxy_enabled,p.proxy_url_ciphertext,p.proxy_url_nonce,p.proxy_url_key_version,
       p.proxy_headers_ciphertext,p.proxy_headers_nonce,p.proxy_headers_key_version,
       r.id AS resource_id,r.auth_type,r.auth_adapter,r.subscription_type,r.priority AS resource_priority,r.expires_at,
       r.quota_status,r.quota_checked_at,r.quota_resets_at,r.credential_refreshed_at,r.credential_expires_at,
       r.credential_ciphertext,r.credential_nonce,r.key_version
FROM provider_model pm
JOIN provider p ON p.id=pm.provider_id
JOIN provider_endpoint pe ON pe.provider_id=p.id AND pe.protocol_type IN ('OPENAI','ANTHROPIC')
JOIN provider_credential r ON r.provider_id=p.id
    AND NOT r.is_deleted AND r.runtime_status='HEALTHY'
    AND (r.effective_at IS NULL OR r.effective_at<=now())
    AND (r.expires_at IS NULL OR r.expires_at>now())
    AND (r.auth_type='API_KEY' OR r.quota_status IN ('AVAILABLE','NEAR_LIMIT')
         OR (r.quota_status='EXHAUSTED' AND r.quota_resets_at IS NOT NULL AND r.quota_resets_at<=now()))
WHERE pm.model_id=$1 AND NOT pm.is_deleted
  AND NOT p.is_deleted AND p.status='ACTIVE'
ORDER BY pm.priority,
    CASE WHEN pe.protocol_type=$2 THEN 0 ELSE 1 END,
    CASE WHEN r.auth_type='SUBSCRIPTION' THEN 0 ELSE 1 END,
    r.priority,pm.id,r.id
`

type GatewayCandidatesParams struct {
	ModelID           int64
	PreferredProtocol string
}

type GatewayCandidatesRow struct {
	ProviderModelID        int64
	ProviderID             int64
	ProviderName           string
	UpstreamModelCode      string
	BaseUrl                string
	ProtocolType           string
	NetworkScope           string
	ProxyEnabled           bool
	ProxyUrlCiphertext     []byte
	ProxyUrlNonce          []byte
	ProxyUrlKeyVersion     *int32
	ProxyHeadersCiphertext []byte
	ProxyHeadersNonce      []byte
	ProxyHeadersKeyVersion *int32
	ResourceID             int64
	AuthType               string
	AuthAdapter            string
	SubscriptionType       *string
	ResourcePriority       int32
	ExpiresAt              pgtype.Timestamptz
	QuotaStatus            string
	QuotaCheckedAt         pgtype.Timestamptz
	QuotaResetsAt          pgtype.Timestamptz
	CredentialRefreshedAt  pgtype.Timestamptz
	CredentialExpiresAt    pgtype.Timestamptz
	CredentialCiphertext   []byte
	CredentialNonce        []byte
	KeyVersion             int32
}

func (q *Queries) GatewayCandidates(ctx context.Context, arg GatewayCandidatesParams) ([]GatewayCandidatesRow, error) {
	rows, err := q.db.Query(ctx, gatewayCandidates, arg.ModelID, arg.PreferredProtocol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayCandidatesRow{}
	for rows.Next() {
		var i GatewayCandidatesRow
		if err := rows.Scan(
			&i.ProviderModelID,
			&i.ProviderID,
			&i.ProviderName,
			&i.UpstreamModelCode,
			&i.BaseUrl,
			&i.ProtocolType,
			&i.NetworkScope,
			&i.ProxyEnabled,
			&i.ProxyUrlCiphertext,
			&i.ProxyUrlNonce,
			&i.ProxyUrlKeyVersion,
			&i.ProxyHeadersCiphertext,
			&i.ProxyHeadersNonce,
			&i.ProxyHeadersKeyVersion,
			&i.ResourceID,
			&i.AuthType,
			&i.AuthAdapter,
			&i.SubscriptionType,
			&i.ResourcePriority,
			&i.ExpiresAt,
			&i.QuotaStatus,
			&i.QuotaCheckedAt,
			&i.QuotaResetsAt,
			&i.CredentialRefreshedAt,
			&i.CredentialExpiresAt,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gatewayIdentityActive = `-- name: GatewayIdentityActive :one
SELECT EXISTS (SELECT 1 FROM principal_access_key k
JOIN principal p ON p.id=k.principal_id
WHERE k.id=$1 AND k.principal_id=$2
AND NOT k.is_deleted AND k.status='ACTIVE' AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at>now())
AND NOT p.is_deleted AND p.status='ACTIVE' AND p.principal_type='MEMBER')
`

type GatewayIdentityActiveParams struct {
	AccessKeyID int64
	PrincipalID int64
}

func (q *Queries) GatewayIdentityActive(ctx context.Context, arg GatewayIdentityActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, gatewayIdentityActive, arg.AccessKeyID, arg.PrincipalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const gatewayModel = `-- name: GatewayModel :one
SELECT id,model_code,display_name,status FROM model WHERE model_code=$1 AND NOT is_deleted
`

type GatewayModelRow struct {
	ID          int64
	ModelCode   string
	DisplayName string
	Status      string
}

func (q *Queries) GatewayModel(ctx context.Context, modelCode string) (GatewayModelRow, error) {
	row := q.db.QueryRow(ctx, gatewayModel, modelCode)
	var i GatewayModelRow
	err := row.Scan(
		&i.ID,
		&i.ModelCode,
		&i.DisplayName,
		&i.Status,
	)
	return i, err
}

const gatewayResourceCredential = `-- name: GatewayResourceCredential :one
SELECT credential_ciphertext,credential_nonce,key_version
FROM provider_credential
WHERE id=$1 AND provider_id=$2
  AND NOT is_deleted AND auth_type='SUBSCRIPTION'
`

type GatewayResourceCredentialParams struct {
	ResourceID int64
	ProviderID int64
}

type GatewayResourceCredentialRow struct {
	CredentialCiphertext []byte
	CredentialNonce      []byte
	KeyVersion           int32
}

func (q *Queries) GatewayResourceCredential(ctx context.Context, arg GatewayResourceCredentialParams) (GatewayResourceCredentialRow, error) {
	row := q.db.QueryRow(ctx, gatewayResourceCredential, arg.ResourceID, arg.ProviderID)
	var i GatewayResourceCredentialRow
	err := row.Scan(&i.CredentialCiphertext, &i.CredentialNonce, &i.KeyVersion)
	return i, err
}

const gatewayRouteExists = `-- name: GatewayRouteExists :one
SELECT EXISTS(
    SELECT 1
    FROM provider_model pm
    JOIN provider p ON p.id=pm.provider_id
    JOIN provider_endpoint pe ON pe.provider_id=p.id AND pe.protocol_type IN ('OPENAI','ANTHROPIC')
    WHERE pm.model_id=$1 AND NOT pm.is_deleted
      AND NOT p.is_deleted AND p.status='ACTIVE'
)
`

func (q *Queries) GatewayRouteExists(ctx context.Context, modelID int64) (bool, error) {
	row := q.db.QueryRow(ctx, gatewayRouteExists, modelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGatewaySubscriptionCredentials = `-- name: ListGatewaySubscriptionCredentials :many
SELECT r.id AS resource_id,r.provider_id,r.auth_adapter,r.credential_refreshed_at,r.credential_expires_at,
       p.proxy_enabled,p.proxy_url_ciphertext,p.proxy_url_nonce,p.proxy_url_key_version,
       p.proxy_headers_ciphertext,p.proxy_headers_nonce,p.proxy_headers_key_version,
       r.credential_ciphertext,r.credential_nonce,r.key_version
FROM provider_credential r
JOIN provider p ON p.id=r.provider_id
WHERE r.id>$1
  AND NOT r.is_deleted AND r.auth_type='SUBSCRIPTION' AND r.subscription_type='PERSONAL'
  AND r.runtime_status='HEALTHY'
  AND (r.effective_at IS NULL OR r.effective_at<=now())
  AND (r.expires_at IS NULL OR r.expires_at>now())
  AND (r.credential_expires_at IS NULL OR r.credential_expires_at<=$2::timestamptz)
  AND NOT p.is_deleted AND p.status='ACTIVE'
ORDER BY r.id
LIMIT $3
`

type ListGatewaySubscriptionCredentialsParams struct {
	AfterID       int64
	RefreshBefore pgtype.Timestamptz
	PageLimit     int32
}

type ListGatewaySubscriptionCredentialsRow struct {
	ResourceID             int64
	ProviderID             int64
	AuthAdapter            string
	CredentialRefreshedAt  pgtype.Timestamptz
	CredentialExpiresAt    pgtype.Timestamptz
	ProxyEnabled           bool
	ProxyUrlCiphertext     []byte
	ProxyUrlNonce          []byte
	ProxyUrlKeyVersion     *int32
	ProxyHeadersCiphertext []byte
	ProxyHeadersNonce      []byte
	ProxyHeadersKeyVersion *int32
	CredentialCiphertext   []byte
	CredentialNonce        []byte
	KeyVersion             int32
}

func (q *Queries) ListGatewaySubscriptionCredentials(ctx context.Context, arg ListGatewaySubscriptionCredentialsParams) ([]ListGatewaySubscriptionCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listGatewaySubscriptionCredentials, arg.AfterID, arg.RefreshBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewaySubscriptionCredentialsRow{}
	for rows.Next() {
		var i ListGatewaySubscriptionCredentialsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ProviderID,
			&i.AuthAdapter,
			&i.CredentialRefreshedAt,
			&i.CredentialExpiresAt,
			&i.ProxyEnabled,
			&i.ProxyUrlCiphertext,
			&i.ProxyUrlNonce,
			&i.ProxyUrlKeyVersion,
			&i.ProxyHeadersCiphertext,
			&i.ProxyHeadersNonce,
			&i.ProxyHeadersKeyVersion,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGatewaySubscriptionRefresh = `-- name: LockGatewaySubscriptionRefresh :one
SELECT pg_advisory_lock(-($1::bigint))
`

func (q *Queries) LockGatewaySubscriptionRefresh(ctx context.Context, resourceID int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockGatewaySubscriptionRefresh, resourceID)
	var pg_advisory_lock interface{}
	err := row.Scan(&pg_advisory_lock)
	return pg_advisory_lock, err
}

const openAIModels = `-- name: OpenAIModels :many
SELECT DISTINCT ON (m.model_code) m.model_code,m.created_at,p.provider_code FROM model m
JOIN provider_model pm ON pm.model_id=m.id AND NOT pm.is_deleted
JOIN provider p ON p.id=pm.provider_id AND NOT p.is_deleted AND p.status='ACTIVE'
JOIN provider_endpoint pe ON pe.provider_id=p.id AND pe.protocol_type IN ('OPENAI','ANTHROPIC')
WHERE NOT m.is_deleted AND m.status='ACTIVE'
AND EXISTS(SELECT 1 FROM provider_credential r WHERE r.provider_id=p.id AND NOT r.is_deleted AND r.runtime_status='HEALTHY'
    AND (r.effective_at IS NULL OR r.effective_at<=now()) AND (r.expires_at IS NULL OR r.expires_at>now())
    AND (r.auth_type='API_KEY' OR r.quota_status IN ('AVAILABLE','NEAR_LIMIT')
         OR (r.quota_status='EXHAUSTED' AND r.quota_resets_at IS NOT NULL AND r.quota_resets_at<=now())))
AND EXISTS(SELECT 1 FROM principal_group_membership pg JOIN principal_group g ON g.id=pg.group_id
JOIN principal_group_model_permission gp ON gp.group_id=g.id
WHERE pg.principal_id=$1
AND NOT pg.is_deleted AND NOT g.is_deleted AND g.status='ACTIVE' AND NOT gp.is_deleted AND gp.model_id=m.id)
ORDER BY m.model_code,CASE pe.protocol_type WHEN 'OPENAI' THEN 0 ELSE 1 END,pm.priority,pm.id
`

type OpenAIModelsRow struct {
	ModelCode    string
	CreatedAt    pgtype.Timestamptz
	ProviderCode string
}

func (q *Queries) OpenAIModels(ctx context.Context, principalID int64) ([]OpenAIModelsRow, error) {
	rows, err := q.db.Query(ctx, openAIModels, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenAIModelsRow{}
	for rows.Next() {
		var i OpenAIModelsRow
		if err := rows.Scan(&i.ModelCode, &i.CreatedAt, &i.ProviderCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockGatewaySubscriptionRefresh = `-- name: UnlockGatewaySubscriptionRefresh :one
SELECT pg_advisory_unlock(-($1::bigint))
`

func (q *Queries) UnlockGatewaySubscriptionRefresh(ctx context.Context, resourceID int64) (bool, error) {
	row := q.db.QueryRow(ctx, unlockGatewaySubscriptionRefresh, resourceID)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const updateGatewayResourceCredential = `-- name: UpdateGatewayResourceCredential :execrows
UPDATE provider_credential
SET credential_ciphertext=$1,credential_nonce=$2,
    key_version=$3,credential_refreshed_at=$4,
    credential_expires_at=$5,updated_by='system',updated_at=$6
WHERE id=$7 AND provider_id=$8 AND NOT is_deleted
`

type UpdateGatewayResourceCredentialParams struct {
	CredentialCiphertext  []byte
	CredentialNonce       []byte
	KeyVersion            int32
	CredentialRefreshedAt pgtype.Timestamptz
	CredentialExpiresAt   pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ResourceID            int64
	ProviderID            int64
}

func (q *Queries) UpdateGatewayResourceCredential(ctx context.Context, arg UpdateGatewayResourceCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGatewayResourceCredential,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyVersion,
		arg.CredentialRefreshedAt,
		arg.CredentialExpiresAt,
		arg.UpdatedAt,
		arg.ResourceID,
		arg.ProviderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGatewayResourceCredentialRefreshMetadata = `-- name: UpdateGatewayResourceCredentialRefreshMetadata :execrows
UPDATE provider_credential
SET credential_refreshed_at=$1,
    credential_expires_at=$2,updated_by='system',updated_at=$3
WHERE id=$4 AND provider_id=$5 AND NOT is_deleted
  AND credential_expires_at IS NULL
`

type UpdateGatewayResourceCredentialRefreshMetadataParams struct {
	CredentialRefreshedAt pgtype.Timestamptz
	CredentialExpiresAt   pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ResourceID            int64
	ProviderID            int64
}

func (q *Queries) UpdateGatewayResourceCredentialRefreshMetadata(ctx context.Context, arg UpdateGatewayResourceCredentialRefreshMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGatewayResourceCredentialRefreshMetadata,
		arg.CredentialRefreshedAt,
		arg.CredentialExpiresAt,
		arg.UpdatedAt,
		arg.ResourceID,
		arg.ProviderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
