// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gatewayIdentityActive = `-- name: GatewayIdentityActive :one
SELECT EXISTS (SELECT 1 FROM access_key k
JOIN principal p ON p.id=k.principal_id AND p.organization_id=k.organization_id
JOIN organization o ON o.id=k.organization_id
WHERE k.id=$1 AND k.organization_id=$2 AND k.principal_id=$3
AND NOT k.is_deleted AND k.status='ACTIVE' AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at>now())
AND NOT p.is_deleted AND p.status='ACTIVE' AND p.principal_type='MEMBER' AND NOT o.is_deleted AND o.status='ACTIVE')
`

type GatewayIdentityActiveParams struct {
	AccessKeyID    int64
	OrganizationID int64
	PrincipalID    int64
}

func (q *Queries) GatewayIdentityActive(ctx context.Context, arg GatewayIdentityActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, gatewayIdentityActive, arg.AccessKeyID, arg.OrganizationID, arg.PrincipalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const gatewayMappings = `-- name: GatewayMappings :many
SELECT pm.id,pm.provider_id,pm.upstream_model_code,p.anthropic_base_url,p.openai_base_url,
       p.proxy_enabled,p.proxy_url_ciphertext,p.proxy_url_nonce,p.proxy_url_key_version,
       p.proxy_headers_ciphertext,p.proxy_headers_nonce,p.proxy_headers_key_version
FROM provider_model pm
JOIN ai_provider p ON p.id=pm.provider_id
WHERE pm.model_id=$1 AND NOT pm.is_deleted AND pm.status='ACTIVE' AND pm.protocol_type=$2
AND NOT p.is_deleted AND p.status='ACTIVE'
ORDER BY pm.id LIMIT 2
`

type GatewayMappingsParams struct {
	ModelID      int64
	ProtocolType string
}

type GatewayMappingsRow struct {
	ID                     int64
	ProviderID             int64
	UpstreamModelCode      string
	AnthropicBaseUrl       *string
	OpenaiBaseUrl          *string
	ProxyEnabled           bool
	ProxyUrlCiphertext     []byte
	ProxyUrlNonce          []byte
	ProxyUrlKeyVersion     *int32
	ProxyHeadersCiphertext []byte
	ProxyHeadersNonce      []byte
	ProxyHeadersKeyVersion *int32
}

func (q *Queries) GatewayMappings(ctx context.Context, arg GatewayMappingsParams) ([]GatewayMappingsRow, error) {
	rows, err := q.db.Query(ctx, gatewayMappings, arg.ModelID, arg.ProtocolType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayMappingsRow{}
	for rows.Next() {
		var i GatewayMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.UpstreamModelCode,
			&i.AnthropicBaseUrl,
			&i.OpenaiBaseUrl,
			&i.ProxyEnabled,
			&i.ProxyUrlCiphertext,
			&i.ProxyUrlNonce,
			&i.ProxyUrlKeyVersion,
			&i.ProxyHeadersCiphertext,
			&i.ProxyHeadersNonce,
			&i.ProxyHeadersKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gatewayModel = `-- name: GatewayModel :one
SELECT id,status FROM ai_model WHERE model_code=$1 AND NOT is_deleted
`

type GatewayModelRow struct {
	ID     int64
	Status string
}

func (q *Queries) GatewayModel(ctx context.Context, modelCode string) (GatewayModelRow, error) {
	row := q.db.QueryRow(ctx, gatewayModel, modelCode)
	var i GatewayModelRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const gatewayResources = `-- name: GatewayResources :many
SELECT id, is_deleted, organization_id, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, status, last_active_at, created_by, updated_by, created_at, updated_at FROM ai_resource WHERE organization_id=$1 AND provider_id=$2 AND NOT is_deleted AND status='ACTIVE' ORDER BY id LIMIT 2
`

type GatewayResourcesParams struct {
	OrganizationID int64
	ProviderID     int64
}

func (q *Queries) GatewayResources(ctx context.Context, arg GatewayResourcesParams) ([]AiResource, error) {
	rows, err := q.db.Query(ctx, gatewayResources, arg.OrganizationID, arg.ProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiResource{}
	for rows.Next() {
		var i AiResource
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.OrganizationID,
			&i.ProviderID,
			&i.ResourceName,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.KeyVersion,
			&i.Status,
			&i.LastActiveAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAIModels = `-- name: OpenAIModels :many
SELECT m.model_code,m.created_at,p.provider_code FROM ai_model m
JOIN provider_model pm ON pm.model_id=m.id AND NOT pm.is_deleted AND pm.status='ACTIVE' AND pm.protocol_type='OPENAI'
JOIN ai_provider p ON p.id=pm.provider_id AND NOT p.is_deleted AND p.status='ACTIVE' AND p.openai_base_url IS NOT NULL
WHERE NOT m.is_deleted AND m.status='ACTIVE'
AND EXISTS(SELECT 1 FROM ai_resource r WHERE r.provider_id=p.id AND r.organization_id=$1 AND NOT r.is_deleted AND r.status='ACTIVE')
AND EXISTS(SELECT 1 FROM principal_group pg JOIN ai_group g ON g.id=pg.group_id AND g.organization_id=pg.organization_id
JOIN group_model_permission gp ON gp.group_id=g.id AND gp.organization_id=g.organization_id
WHERE pg.principal_id=$2 AND pg.organization_id=$1
AND NOT pg.is_deleted AND NOT g.is_deleted AND g.status='ACTIVE' AND NOT gp.is_deleted AND gp.model_id=m.id)
ORDER BY m.model_code
`

type OpenAIModelsParams struct {
	OrganizationID int64
	PrincipalID    int64
}

type OpenAIModelsRow struct {
	ModelCode    string
	CreatedAt    pgtype.Timestamptz
	ProviderCode string
}

func (q *Queries) OpenAIModels(ctx context.Context, arg OpenAIModelsParams) ([]OpenAIModelsRow, error) {
	rows, err := q.db.Query(ctx, openAIModels, arg.OrganizationID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenAIModelsRow{}
	for rows.Next() {
		var i OpenAIModelsRow
		if err := rows.Scan(&i.ModelCode, &i.CreatedAt, &i.ProviderCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
