// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: management.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockManagementOrganization = `-- name: LockManagementOrganization :one
SELECT o.id FROM organization o JOIN admin_user a ON a.organization_id=o.id
WHERE o.id=$1 AND a.id=$2 AND o.is_deleted=false AND o.status='ACTIVE'
AND a.is_deleted=false AND a.status='ACTIVE' FOR UPDATE OF o FOR SHARE OF a
`

type LockManagementOrganizationParams struct {
	ID   int64
	ID_2 int64
}

func (q *Queries) LockManagementOrganization(ctx context.Context, arg LockManagementOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockManagementOrganization, arg.ID, arg.ID_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const manageAddMember = `-- name: ManageAddMember :exec
INSERT INTO principal_group(id,organization_id,group_id,principal_id,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$5,$6,$6)
`

type ManageAddMemberParams struct {
	ID             int64
	OrganizationID int64
	GroupID        int64
	PrincipalID    int64
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageAddMember(ctx context.Context, arg ManageAddMemberParams) error {
	_, err := q.db.Exec(ctx, manageAddMember,
		arg.ID,
		arg.OrganizationID,
		arg.GroupID,
		arg.PrincipalID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateGroup = `-- name: ManageCreateGroup :exec
INSERT INTO ai_group(id,organization_id,group_code,group_name,remark,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,'ACTIVE',$6,$6,$7,$7)
`

type ManageCreateGroupParams struct {
	ID             int64
	OrganizationID int64
	GroupCode      string
	GroupName      string
	Remark         *string
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageCreateGroup(ctx context.Context, arg ManageCreateGroupParams) error {
	_, err := q.db.Exec(ctx, manageCreateGroup,
		arg.ID,
		arg.OrganizationID,
		arg.GroupCode,
		arg.GroupName,
		arg.Remark,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateMember = `-- name: ManageCreateMember :exec
INSERT INTO principal(id,organization_id,principal_type,name,remark,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,'MEMBER',$3,$4,'ACTIVE',$5,$5,$6,$6)
`

type ManageCreateMemberParams struct {
	ID             int64
	OrganizationID int64
	Name           string
	Remark         *string
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageCreateMember(ctx context.Context, arg ManageCreateMemberParams) error {
	_, err := q.db.Exec(ctx, manageCreateMember,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Remark,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateModel = `-- name: ManageCreateModel :exec
INSERT INTO ai_model(id,model_code,display_name,input_modalities,output_modalities,remark,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,'DISABLED',$7,$7,$8,$8)
`

type ManageCreateModelParams struct {
	ID               int64
	ModelCode        string
	DisplayName      string
	InputModalities  []byte
	OutputModalities []byte
	Remark           string
	CreatedBy        string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ManageCreateModel(ctx context.Context, arg ManageCreateModelParams) error {
	_, err := q.db.Exec(ctx, manageCreateModel,
		arg.ID,
		arg.ModelCode,
		arg.DisplayName,
		arg.InputModalities,
		arg.OutputModalities,
		arg.Remark,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateResource = `-- name: ManageCreateResource :exec
INSERT INTO ai_resource(id,organization_id,provider_id,resource_name,credential_ciphertext,credential_nonce,key_version,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,$10,$10)
`

type ManageCreateResourceParams struct {
	ID                   int64
	OrganizationID       int64
	ProviderID           int64
	ResourceName         string
	CredentialCiphertext []byte
	CredentialNonce      []byte
	KeyVersion           int32
	Status               string
	CreatedBy            string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ManageCreateResource(ctx context.Context, arg ManageCreateResourceParams) error {
	_, err := q.db.Exec(ctx, manageCreateResource,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderID,
		arg.ResourceName,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyVersion,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageDeleteMember = `-- name: ManageDeleteMember :exec
UPDATE principal SET is_deleted=true,status='DISABLED',updated_by=$3,updated_at=$4
WHERE organization_id=$1 AND id=$2 AND is_deleted=false AND principal_type='MEMBER'
`

type ManageDeleteMemberParams struct {
	OrganizationID int64
	ID             int64
	UpdatedBy      string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageDeleteMember(ctx context.Context, arg ManageDeleteMemberParams) error {
	_, err := q.db.Exec(ctx, manageDeleteMember,
		arg.OrganizationID,
		arg.ID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageDeleteMemberGroups = `-- name: ManageDeleteMemberGroups :exec
UPDATE principal_group SET is_deleted=true,updated_by=$3,updated_at=$4
WHERE organization_id=$1 AND principal_id=$2 AND is_deleted=false
`

type ManageDeleteMemberGroupsParams struct {
	OrganizationID int64
	PrincipalID    int64
	UpdatedBy      string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageDeleteMemberGroups(ctx context.Context, arg ManageDeleteMemberGroupsParams) error {
	_, err := q.db.Exec(ctx, manageDeleteMemberGroups,
		arg.OrganizationID,
		arg.PrincipalID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageGrantModel = `-- name: ManageGrantModel :exec
INSERT INTO group_model_permission(id,organization_id,group_id,model_id,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$5,$6,$6)
`

type ManageGrantModelParams struct {
	ID             int64
	OrganizationID int64
	GroupID        int64
	ModelID        int64
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageGrantModel(ctx context.Context, arg ManageGrantModelParams) error {
	_, err := q.db.Exec(ctx, manageGrantModel,
		arg.ID,
		arg.OrganizationID,
		arg.GroupID,
		arg.ModelID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageGroup = `-- name: ManageGroup :one
SELECT id, is_deleted, organization_id, group_code, group_name, remark, status, created_by, updated_by, created_at, updated_at FROM ai_group WHERE organization_id=$1 AND id=$2 AND is_deleted=false
`

type ManageGroupParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) ManageGroup(ctx context.Context, arg ManageGroupParams) (AiGroup, error) {
	row := q.db.QueryRow(ctx, manageGroup, arg.OrganizationID, arg.ID)
	var i AiGroup
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.GroupCode,
		&i.GroupName,
		&i.Remark,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const manageGroupMembers = `-- name: ManageGroupMembers :many
SELECT p.id, p.is_deleted, p.organization_id, p.principal_type, p.name, p.remark, p.status, p.created_by, p.updated_by, p.created_at, p.updated_at FROM principal p JOIN principal_group g ON g.principal_id=p.id AND g.organization_id=p.organization_id
WHERE p.organization_id=$1 AND g.group_id=$2 AND g.is_deleted=false AND p.is_deleted=false AND p.principal_type='MEMBER' AND p.id>$3 ORDER BY p.id LIMIT $4
`

type ManageGroupMembersParams struct {
	OrganizationID int64
	GroupID        int64
	ID             int64
	Limit          int32
}

func (q *Queries) ManageGroupMembers(ctx context.Context, arg ManageGroupMembersParams) ([]Principal, error) {
	rows, err := q.db.Query(ctx, manageGroupMembers,
		arg.OrganizationID,
		arg.GroupID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.OrganizationID,
			&i.PrincipalType,
			&i.Name,
			&i.Remark,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageGroupModels = `-- name: ManageGroupModels :many
SELECT m.id, m.is_deleted, m.model_code, m.display_name, m.status, m.created_by, m.updated_by, m.created_at, m.updated_at, m.input_modalities, m.output_modalities, m.remark FROM ai_model m JOIN group_model_permission g ON g.model_id=m.id
WHERE g.organization_id=$1 AND g.group_id=$2 AND g.is_deleted=false AND m.is_deleted=false AND m.id>$3 ORDER BY m.id LIMIT $4
`

type ManageGroupModelsParams struct {
	OrganizationID int64
	GroupID        int64
	ID             int64
	Limit          int32
}

func (q *Queries) ManageGroupModels(ctx context.Context, arg ManageGroupModelsParams) ([]AiModel, error) {
	rows, err := q.db.Query(ctx, manageGroupModels,
		arg.OrganizationID,
		arg.GroupID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiModel{}
	for rows.Next() {
		var i AiModel
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.ModelCode,
			&i.DisplayName,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InputModalities,
			&i.OutputModalities,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageGroups = `-- name: ManageGroups :many
SELECT id, is_deleted, organization_id, group_code, group_name, remark, status, created_by, updated_by, created_at, updated_at FROM ai_group WHERE organization_id=$1 AND is_deleted=false AND id>$2 ORDER BY id LIMIT $3
`

type ManageGroupsParams struct {
	OrganizationID int64
	ID             int64
	Limit          int32
}

func (q *Queries) ManageGroups(ctx context.Context, arg ManageGroupsParams) ([]AiGroup, error) {
	rows, err := q.db.Query(ctx, manageGroups, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiGroup{}
	for rows.Next() {
		var i AiGroup
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.OrganizationID,
			&i.GroupCode,
			&i.GroupName,
			&i.Remark,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageKeys = `-- name: ManageKeys :many
SELECT id,name,key_prefix,status,expires_at,revoked_at,created_at FROM access_key
WHERE organization_id=$1 AND principal_id=$2 AND is_deleted=false AND (id<$3 OR $3=0) ORDER BY id DESC LIMIT $4
`

type ManageKeysParams struct {
	OrganizationID int64
	PrincipalID    int64
	ID             int64
	Limit          int32
}

type ManageKeysRow struct {
	ID        int64
	Name      string
	KeyPrefix string
	Status    string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ManageKeys(ctx context.Context, arg ManageKeysParams) ([]ManageKeysRow, error) {
	rows, err := q.db.Query(ctx, manageKeys,
		arg.OrganizationID,
		arg.PrincipalID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageKeysRow{}
	for rows.Next() {
		var i ManageKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.Status,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageMember = `-- name: ManageMember :one
SELECT id, is_deleted, organization_id, principal_type, name, remark, status, created_by, updated_by, created_at, updated_at FROM principal WHERE organization_id=$1 AND id=$2 AND is_deleted=false AND principal_type='MEMBER'
`

type ManageMemberParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) ManageMember(ctx context.Context, arg ManageMemberParams) (Principal, error) {
	row := q.db.QueryRow(ctx, manageMember, arg.OrganizationID, arg.ID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.PrincipalType,
		&i.Name,
		&i.Remark,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const manageMemberStatus = `-- name: ManageMemberStatus :exec
UPDATE principal SET status=$3,updated_by=$4,updated_at=$5 WHERE organization_id=$1 AND id=$2 AND is_deleted=false AND principal_type='MEMBER'
`

type ManageMemberStatusParams struct {
	OrganizationID int64
	ID             int64
	Status         string
	UpdatedBy      string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageMemberStatus(ctx context.Context, arg ManageMemberStatusParams) error {
	_, err := q.db.Exec(ctx, manageMemberStatus,
		arg.OrganizationID,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageMembers = `-- name: ManageMembers :many
SELECT id, is_deleted, organization_id, principal_type, name, remark, status, created_by, updated_by, created_at, updated_at FROM principal WHERE organization_id=$1 AND is_deleted=false AND principal_type='MEMBER' AND (id<$2 OR $2=0) ORDER BY id DESC LIMIT $3
`

type ManageMembersParams struct {
	OrganizationID int64
	ID             int64
	Limit          int32
}

func (q *Queries) ManageMembers(ctx context.Context, arg ManageMembersParams) ([]Principal, error) {
	rows, err := q.db.Query(ctx, manageMembers, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.OrganizationID,
			&i.PrincipalType,
			&i.Name,
			&i.Remark,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageMembershipExists = `-- name: ManageMembershipExists :one
SELECT EXISTS(SELECT 1 FROM principal_group WHERE organization_id=$1 AND group_id=$2 AND principal_id=$3 AND is_deleted=false)
`

type ManageMembershipExistsParams struct {
	OrganizationID int64
	GroupID        int64
	PrincipalID    int64
}

func (q *Queries) ManageMembershipExists(ctx context.Context, arg ManageMembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, manageMembershipExists, arg.OrganizationID, arg.GroupID, arg.PrincipalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const manageModel = `-- name: ManageModel :one
SELECT id, is_deleted, model_code, display_name, status, created_by, updated_by, created_at, updated_at, input_modalities, output_modalities, remark FROM ai_model WHERE id=$1 AND is_deleted=false
`

func (q *Queries) ManageModel(ctx context.Context, id int64) (AiModel, error) {
	row := q.db.QueryRow(ctx, manageModel, id)
	var i AiModel
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.ModelCode,
		&i.DisplayName,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InputModalities,
		&i.OutputModalities,
		&i.Remark,
	)
	return i, err
}

const manageModelStatus = `-- name: ManageModelStatus :exec
UPDATE ai_model SET status=$2,updated_by=$3,updated_at=$4 WHERE id=$1 AND is_deleted=false
`

type ManageModelStatusParams struct {
	ID        int64
	Status    string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageModelStatus(ctx context.Context, arg ManageModelStatusParams) error {
	_, err := q.db.Exec(ctx, manageModelStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageModels = `-- name: ManageModels :many
SELECT id, is_deleted, model_code, display_name, status, created_by, updated_by, created_at, updated_at, input_modalities, output_modalities, remark FROM ai_model WHERE is_deleted=false AND id>$1 ORDER BY id LIMIT $2
`

type ManageModelsParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ManageModels(ctx context.Context, arg ManageModelsParams) ([]AiModel, error) {
	rows, err := q.db.Query(ctx, manageModels, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiModel{}
	for rows.Next() {
		var i AiModel
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.ModelCode,
			&i.DisplayName,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InputModalities,
			&i.OutputModalities,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageOperations = `-- name: ManageOperations :many
SELECT id,operator_name,operation_type,target_type,target_id,request_id,result,error_code,before_data,after_data,created_at
FROM operation_log WHERE organization_id=$1 AND id>$2 ORDER BY id LIMIT $3
`

type ManageOperationsParams struct {
	OrganizationID int64
	ID             int64
	Limit          int32
}

type ManageOperationsRow struct {
	ID            int64
	OperatorName  string
	OperationType string
	TargetType    string
	TargetID      *int64
	RequestID     *string
	Result        string
	ErrorCode     *string
	BeforeData    []byte
	AfterData     []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ManageOperations(ctx context.Context, arg ManageOperationsParams) ([]ManageOperationsRow, error) {
	rows, err := q.db.Query(ctx, manageOperations, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageOperationsRow{}
	for rows.Next() {
		var i ManageOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorName,
			&i.OperationType,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.Result,
			&i.ErrorCode,
			&i.BeforeData,
			&i.AfterData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managePermissionExists = `-- name: ManagePermissionExists :one
SELECT EXISTS(SELECT 1 FROM group_model_permission WHERE organization_id=$1 AND group_id=$2 AND model_id=$3 AND is_deleted=false)
`

type ManagePermissionExistsParams struct {
	OrganizationID int64
	GroupID        int64
	ModelID        int64
}

func (q *Queries) ManagePermissionExists(ctx context.Context, arg ManagePermissionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, managePermissionExists, arg.OrganizationID, arg.GroupID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const manageProvider = `-- name: ManageProvider :one
SELECT id, is_deleted, provider_code, provider_name, provider_type, anthropic_base_url, status, created_by, updated_by, created_at, updated_at, openai_base_url FROM ai_provider WHERE id=$1 AND is_deleted=false AND provider_code IN ('anthropic-official','deepseek-official') AND provider_type='OFFICIAL'
`

func (q *Queries) ManageProvider(ctx context.Context, id int64) (AiProvider, error) {
	row := q.db.QueryRow(ctx, manageProvider, id)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.ProviderCode,
		&i.ProviderName,
		&i.ProviderType,
		&i.AnthropicBaseUrl,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenaiBaseUrl,
	)
	return i, err
}

const manageProviders = `-- name: ManageProviders :many
SELECT id, is_deleted, provider_code, provider_name, provider_type, anthropic_base_url, status, created_by, updated_by, created_at, updated_at, openai_base_url FROM ai_provider WHERE is_deleted=false AND provider_code IN ('anthropic-official','deepseek-official') AND provider_type='OFFICIAL' AND id>$1 ORDER BY id LIMIT $2
`

type ManageProvidersParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ManageProviders(ctx context.Context, arg ManageProvidersParams) ([]AiProvider, error) {
	rows, err := q.db.Query(ctx, manageProviders, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiProvider{}
	for rows.Next() {
		var i AiProvider
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.ProviderCode,
			&i.ProviderName,
			&i.ProviderType,
			&i.AnthropicBaseUrl,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OpenaiBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageRemoveMember = `-- name: ManageRemoveMember :exec
UPDATE principal_group SET is_deleted=true,updated_by=$4,updated_at=$5 WHERE organization_id=$1 AND group_id=$2 AND principal_id=$3 AND is_deleted=false
`

type ManageRemoveMemberParams struct {
	OrganizationID int64
	GroupID        int64
	PrincipalID    int64
	UpdatedBy      string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageRemoveMember(ctx context.Context, arg ManageRemoveMemberParams) error {
	_, err := q.db.Exec(ctx, manageRemoveMember,
		arg.OrganizationID,
		arg.GroupID,
		arg.PrincipalID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageResource = `-- name: ManageResource :one
SELECT id, is_deleted, organization_id, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, status, last_active_at, created_by, updated_by, created_at, updated_at FROM ai_resource WHERE organization_id=$1 AND id=$2 AND is_deleted=false
`

type ManageResourceParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) ManageResource(ctx context.Context, arg ManageResourceParams) (AiResource, error) {
	row := q.db.QueryRow(ctx, manageResource, arg.OrganizationID, arg.ID)
	var i AiResource
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.ProviderID,
		&i.ResourceName,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.KeyVersion,
		&i.Status,
		&i.LastActiveAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const manageResources = `-- name: ManageResources :many
SELECT id,provider_id,resource_name,status,created_at,updated_at FROM ai_resource
WHERE organization_id=$1 AND is_deleted=false AND id>$2 ORDER BY id LIMIT $3
`

type ManageResourcesParams struct {
	OrganizationID int64
	ID             int64
	Limit          int32
}

type ManageResourcesRow struct {
	ID           int64
	ProviderID   int64
	ResourceName string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ManageResources(ctx context.Context, arg ManageResourcesParams) ([]ManageResourcesRow, error) {
	rows, err := q.db.Query(ctx, manageResources, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageResourcesRow{}
	for rows.Next() {
		var i ManageResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ResourceName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageRevokeMemberKeys = `-- name: ManageRevokeMemberKeys :exec
UPDATE access_key SET status='REVOKED',revoked_at=$4,updated_by=$3,updated_at=$4
WHERE organization_id=$1 AND principal_id=$2 AND is_deleted=false AND status<>'REVOKED'
`

type ManageRevokeMemberKeysParams struct {
	OrganizationID int64
	PrincipalID    int64
	UpdatedBy      string
	RevokedAt      pgtype.Timestamptz
}

func (q *Queries) ManageRevokeMemberKeys(ctx context.Context, arg ManageRevokeMemberKeysParams) error {
	_, err := q.db.Exec(ctx, manageRevokeMemberKeys,
		arg.OrganizationID,
		arg.PrincipalID,
		arg.UpdatedBy,
		arg.RevokedAt,
	)
	return err
}

const manageRevokeModel = `-- name: ManageRevokeModel :exec
UPDATE group_model_permission SET is_deleted=true,updated_by=$4,updated_at=$5 WHERE organization_id=$1 AND group_id=$2 AND model_id=$3 AND is_deleted=false
`

type ManageRevokeModelParams struct {
	OrganizationID int64
	GroupID        int64
	ModelID        int64
	UpdatedBy      string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ManageRevokeModel(ctx context.Context, arg ManageRevokeModelParams) error {
	_, err := q.db.Exec(ctx, manageRevokeModel,
		arg.OrganizationID,
		arg.GroupID,
		arg.ModelID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateModel = `-- name: ManageUpdateModel :exec
UPDATE ai_model SET model_code=$2,display_name=$3,input_modalities=$4,output_modalities=$5,remark=$6,updated_by=$7,updated_at=$8
WHERE id=$1 AND is_deleted=false
`

type ManageUpdateModelParams struct {
	ID               int64
	ModelCode        string
	DisplayName      string
	InputModalities  []byte
	OutputModalities []byte
	Remark           string
	UpdatedBy        string
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ManageUpdateModel(ctx context.Context, arg ManageUpdateModelParams) error {
	_, err := q.db.Exec(ctx, manageUpdateModel,
		arg.ID,
		arg.ModelCode,
		arg.DisplayName,
		arg.InputModalities,
		arg.OutputModalities,
		arg.Remark,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateResource = `-- name: ManageUpdateResource :exec
UPDATE ai_resource SET resource_name=$3,credential_ciphertext=$4,credential_nonce=$5,key_version=$6,status=$7,updated_by=$8,updated_at=$9
WHERE organization_id=$1 AND id=$2 AND is_deleted=false
`

type ManageUpdateResourceParams struct {
	OrganizationID       int64
	ID                   int64
	ResourceName         string
	CredentialCiphertext []byte
	CredentialNonce      []byte
	KeyVersion           int32
	Status               string
	UpdatedBy            string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ManageUpdateResource(ctx context.Context, arg ManageUpdateResourceParams) error {
	_, err := q.db.Exec(ctx, manageUpdateResource,
		arg.OrganizationID,
		arg.ID,
		arg.ResourceName,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyVersion,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
