// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: management.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countManageGroupMembers = `-- name: CountManageGroupMembers :one
SELECT COUNT(*)::bigint
FROM principal p
JOIN principal_group_membership g
  ON g.principal_id=p.id
WHERE g.group_id=$1 AND g.is_deleted=false
  AND p.is_deleted=false AND p.principal_type='MEMBER'
`

func (q *Queries) CountManageGroupMembers(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countManageGroupMembers, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageGroupModels = `-- name: CountManageGroupModels :one
SELECT COUNT(*)::bigint
FROM model m
JOIN principal_group_model_permission g ON g.model_id=m.id
WHERE g.group_id=$1
  AND g.is_deleted=false AND m.is_deleted=false
`

func (q *Queries) CountManageGroupModels(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countManageGroupModels, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageGroups = `-- name: CountManageGroups :one
SELECT COUNT(*)::bigint FROM principal_group
WHERE is_deleted=false
  AND ($1::text = '' OR status = $1::text)
`

func (q *Queries) CountManageGroups(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countManageGroups, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageKeys = `-- name: CountManageKeys :one
SELECT COUNT(*)::bigint FROM principal_access_key
WHERE principal_id=$1 AND is_deleted=false
`

func (q *Queries) CountManageKeys(ctx context.Context, principalID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countManageKeys, principalID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageMemberGroups = `-- name: CountManageMemberGroups :one
SELECT COUNT(*)::bigint
FROM principal_group g
JOIN principal_group_membership pg
  ON pg.group_id=g.id
WHERE pg.principal_id=$1
  AND pg.is_deleted=false AND g.is_deleted=false
`

func (q *Queries) CountManageMemberGroups(ctx context.Context, principalID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countManageMemberGroups, principalID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageMemberSuggestions = `-- name: CountManageMemberSuggestions :one
SELECT COUNT(*)::bigint FROM principal
WHERE is_deleted=false
  AND principal_type='MEMBER'
  AND strpos(lower(name), lower($1::text)) > 0
`

func (q *Queries) CountManageMemberSuggestions(ctx context.Context, memberName string) (int64, error) {
	row := q.db.QueryRow(ctx, countManageMemberSuggestions, memberName)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageMembers = `-- name: CountManageMembers :one
SELECT COUNT(*)::bigint FROM principal
WHERE is_deleted=false AND principal_type='MEMBER'
`

// 分页总数不受 after cursor 影响；过滤口径必须与对应列表查询保持一致。
func (q *Queries) CountManageMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countManageMembers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageModels = `-- name: CountManageModels :one
SELECT COUNT(*)::bigint FROM model
WHERE is_deleted=false
  AND ($1::text = '' OR status = $1::text)
`

func (q *Queries) CountManageModels(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countManageModels, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageOperations = `-- name: CountManageOperations :one
SELECT COUNT(*)::bigint FROM operation_log
`

func (q *Queries) CountManageOperations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countManageOperations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageProviders = `-- name: CountManageProviders :one
SELECT COUNT(*)::bigint FROM provider
WHERE is_deleted=false
  AND ($1::text = '' OR provider_type = $1::text)
`

func (q *Queries) CountManageProviders(ctx context.Context, providerType string) (int64, error) {
	row := q.db.QueryRow(ctx, countManageProviders, providerType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManageResources = `-- name: CountManageResources :one
SELECT COUNT(*)::bigint FROM provider_credential
WHERE is_deleted=false
`

func (q *Queries) CountManageResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countManageResources)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const manageAddMember = `-- name: ManageAddMember :exec
INSERT INTO principal_group_membership(id,group_id,principal_id,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$4,$5,$5)
`

type ManageAddMemberParams struct {
	ID          int64
	GroupID     int64
	PrincipalID int64
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ManageAddMember(ctx context.Context, arg ManageAddMemberParams) error {
	_, err := q.db.Exec(ctx, manageAddMember,
		arg.ID,
		arg.GroupID,
		arg.PrincipalID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageBlockResourceRuntime = `-- name: ManageBlockResourceRuntime :exec
UPDATE provider_credential
SET runtime_status='BLOCKED',blocked_reason=$2,blocked_at=$3,last_error_at=$3,
    last_http_status=$4,last_error_code=$5,updated_by=$6,updated_at=$3
WHERE id=$1 AND is_deleted=false
`

type ManageBlockResourceRuntimeParams struct {
	ID             int64
	BlockedReason  *string
	BlockedAt      pgtype.Timestamptz
	LastHttpStatus *int32
	LastErrorCode  *string
	UpdatedBy      string
}

func (q *Queries) ManageBlockResourceRuntime(ctx context.Context, arg ManageBlockResourceRuntimeParams) error {
	_, err := q.db.Exec(ctx, manageBlockResourceRuntime,
		arg.ID,
		arg.BlockedReason,
		arg.BlockedAt,
		arg.LastHttpStatus,
		arg.LastErrorCode,
		arg.UpdatedBy,
	)
	return err
}

const manageCreateGroup = `-- name: ManageCreateGroup :exec
INSERT INTO principal_group(id,group_code,group_name,remark,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,'ACTIVE',$5,$5,$6,$6)
`

type ManageCreateGroupParams struct {
	ID        int64
	GroupCode string
	GroupName string
	Remark    *string
	CreatedBy string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ManageCreateGroup(ctx context.Context, arg ManageCreateGroupParams) error {
	_, err := q.db.Exec(ctx, manageCreateGroup,
		arg.ID,
		arg.GroupCode,
		arg.GroupName,
		arg.Remark,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateMember = `-- name: ManageCreateMember :exec
INSERT INTO principal(id,principal_type,name,remark,status,created_by,updated_by,created_at,updated_at)
VALUES($1,'MEMBER',$2,$3,'DISABLED',$4,$4,$5,$5)
`

type ManageCreateMemberParams struct {
	ID        int64
	Name      string
	Remark    *string
	CreatedBy string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ManageCreateMember(ctx context.Context, arg ManageCreateMemberParams) error {
	_, err := q.db.Exec(ctx, manageCreateMember,
		arg.ID,
		arg.Name,
		arg.Remark,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateModel = `-- name: ManageCreateModel :exec
INSERT INTO model(id,model_code,display_name,input_modalities,output_modalities,remark,status,publisher_provider_id,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,$10,$10)
`

type ManageCreateModelParams struct {
	ID                  int64
	ModelCode           string
	DisplayName         string
	InputModalities     []byte
	OutputModalities    []byte
	Remark              string
	Status              string
	PublisherProviderID *int64
	CreatedBy           string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ManageCreateModel(ctx context.Context, arg ManageCreateModelParams) error {
	_, err := q.db.Exec(ctx, manageCreateModel,
		arg.ID,
		arg.ModelCode,
		arg.DisplayName,
		arg.InputModalities,
		arg.OutputModalities,
		arg.Remark,
		arg.Status,
		arg.PublisherProviderID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateProvider = `-- name: ManageCreateProvider :exec
INSERT INTO provider(id,provider_code,provider_name,provider_type,official_website,proxy_enabled,proxy_url_display,proxy_url_ciphertext,proxy_url_nonce,proxy_url_key_version,proxy_header_names,proxy_headers_ciphertext,proxy_headers_nonce,proxy_headers_key_version,status,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16,$17,$17)
`

type ManageCreateProviderParams struct {
	ID                     int64
	ProviderCode           string
	ProviderName           string
	ProviderType           string
	OfficialWebsite        *string
	ProxyEnabled           bool
	ProxyUrlDisplay        *string
	ProxyUrlCiphertext     []byte
	ProxyUrlNonce          []byte
	ProxyUrlKeyVersion     *int32
	ProxyHeaderNames       []byte
	ProxyHeadersCiphertext []byte
	ProxyHeadersNonce      []byte
	ProxyHeadersKeyVersion *int32
	Status                 string
	CreatedBy              string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) ManageCreateProvider(ctx context.Context, arg ManageCreateProviderParams) error {
	_, err := q.db.Exec(ctx, manageCreateProvider,
		arg.ID,
		arg.ProviderCode,
		arg.ProviderName,
		arg.ProviderType,
		arg.OfficialWebsite,
		arg.ProxyEnabled,
		arg.ProxyUrlDisplay,
		arg.ProxyUrlCiphertext,
		arg.ProxyUrlNonce,
		arg.ProxyUrlKeyVersion,
		arg.ProxyHeaderNames,
		arg.ProxyHeadersCiphertext,
		arg.ProxyHeadersNonce,
		arg.ProxyHeadersKeyVersion,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateProviderMapping = `-- name: ManageCreateProviderMapping :exec
INSERT INTO provider_model(id,provider_id,model_id,upstream_model_code,priority,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$6,$7,$7)
`

type ManageCreateProviderMappingParams struct {
	ID                int64
	ProviderID        int64
	ModelID           int64
	UpstreamModelCode string
	Priority          int32
	CreatedBy         string
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ManageCreateProviderMapping(ctx context.Context, arg ManageCreateProviderMappingParams) error {
	_, err := q.db.Exec(ctx, manageCreateProviderMapping,
		arg.ID,
		arg.ProviderID,
		arg.ModelID,
		arg.UpstreamModelCode,
		arg.Priority,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateResource = `-- name: ManageCreateResource :exec
INSERT INTO provider_credential(
    id,provider_id,resource_name,auth_type,auth_adapter,subscription_type,plan_code,
    external_account_ref,priority,effective_at,expires_at,quota_status,quota_checked_at,
    quota_resets_at,credential_refreshed_at,credential_expires_at,
    credential_ciphertext,credential_nonce,key_version,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$20,$21,$21)
`

type ManageCreateResourceParams struct {
	ID                    int64
	ProviderID            int64
	ResourceName          string
	AuthType              string
	AuthAdapter           string
	SubscriptionType      *string
	PlanCode              *string
	ExternalAccountRef    *string
	Priority              int32
	EffectiveAt           pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	QuotaStatus           string
	QuotaCheckedAt        pgtype.Timestamptz
	QuotaResetsAt         pgtype.Timestamptz
	CredentialRefreshedAt pgtype.Timestamptz
	CredentialExpiresAt   pgtype.Timestamptz
	CredentialCiphertext  []byte
	CredentialNonce       []byte
	KeyVersion            int32
	CreatedBy             string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ManageCreateResource(ctx context.Context, arg ManageCreateResourceParams) error {
	_, err := q.db.Exec(ctx, manageCreateResource,
		arg.ID,
		arg.ProviderID,
		arg.ResourceName,
		arg.AuthType,
		arg.AuthAdapter,
		arg.SubscriptionType,
		arg.PlanCode,
		arg.ExternalAccountRef,
		arg.Priority,
		arg.EffectiveAt,
		arg.ExpiresAt,
		arg.QuotaStatus,
		arg.QuotaCheckedAt,
		arg.QuotaResetsAt,
		arg.CredentialRefreshedAt,
		arg.CredentialExpiresAt,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyVersion,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageCreateResourceQuota = `-- name: ManageCreateResourceQuota :exec
INSERT INTO provider_credential_quota(
    provider_credential_id,quota_code,quota_name,quota_status,quota_unit,limit_value,
    used_value,remaining_value,used_percent,window_duration_seconds,resets_at,reached_type,
    observed_at,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13,$13)
`

type ManageCreateResourceQuotaParams struct {
	ProviderCredentialID  int64
	QuotaCode             string
	QuotaName             *string
	QuotaStatus           string
	QuotaUnit             *string
	LimitValue            pgtype.Numeric
	UsedValue             pgtype.Numeric
	RemainingValue        pgtype.Numeric
	UsedPercent           pgtype.Numeric
	WindowDurationSeconds *int64
	ResetsAt              pgtype.Timestamptz
	ReachedType           *string
	ObservedAt            pgtype.Timestamptz
}

func (q *Queries) ManageCreateResourceQuota(ctx context.Context, arg ManageCreateResourceQuotaParams) error {
	_, err := q.db.Exec(ctx, manageCreateResourceQuota,
		arg.ProviderCredentialID,
		arg.QuotaCode,
		arg.QuotaName,
		arg.QuotaStatus,
		arg.QuotaUnit,
		arg.LimitValue,
		arg.UsedValue,
		arg.RemainingValue,
		arg.UsedPercent,
		arg.WindowDurationSeconds,
		arg.ResetsAt,
		arg.ReachedType,
		arg.ObservedAt,
	)
	return err
}

const manageDeleteGroup = `-- name: ManageDeleteGroup :exec
UPDATE principal_group SET is_deleted=true,status='DISABLED',updated_by=$2,updated_at=$3
WHERE id=$1 AND is_deleted=false
`

type ManageDeleteGroupParams struct {
	ID        int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteGroup(ctx context.Context, arg ManageDeleteGroupParams) error {
	_, err := q.db.Exec(ctx, manageDeleteGroup, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteGroupMembers = `-- name: ManageDeleteGroupMembers :exec
UPDATE principal_group_membership SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE group_id=$1 AND is_deleted=false
`

type ManageDeleteGroupMembersParams struct {
	GroupID   int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteGroupMembers(ctx context.Context, arg ManageDeleteGroupMembersParams) error {
	_, err := q.db.Exec(ctx, manageDeleteGroupMembers, arg.GroupID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteGroupModels = `-- name: ManageDeleteGroupModels :exec
UPDATE principal_group_model_permission SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE group_id=$1 AND is_deleted=false
`

type ManageDeleteGroupModelsParams struct {
	GroupID   int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteGroupModels(ctx context.Context, arg ManageDeleteGroupModelsParams) error {
	_, err := q.db.Exec(ctx, manageDeleteGroupModels, arg.GroupID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteMember = `-- name: ManageDeleteMember :exec
UPDATE principal SET is_deleted=true,status='DISABLED',updated_by=$2,updated_at=$3
WHERE id=$1 AND is_deleted=false AND principal_type='MEMBER'
`

type ManageDeleteMemberParams struct {
	ID        int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteMember(ctx context.Context, arg ManageDeleteMemberParams) error {
	_, err := q.db.Exec(ctx, manageDeleteMember, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteMemberGroups = `-- name: ManageDeleteMemberGroups :exec
UPDATE principal_group_membership SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE principal_id=$1 AND is_deleted=false
`

type ManageDeleteMemberGroupsParams struct {
	PrincipalID int64
	UpdatedBy   string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ManageDeleteMemberGroups(ctx context.Context, arg ManageDeleteMemberGroupsParams) error {
	_, err := q.db.Exec(ctx, manageDeleteMemberGroups, arg.PrincipalID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteModel = `-- name: ManageDeleteModel :exec
UPDATE model SET is_deleted=true,status='DISABLED',updated_by=$2,updated_at=$3
WHERE id=$1 AND is_deleted=false
`

type ManageDeleteModelParams struct {
	ID        int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteModel(ctx context.Context, arg ManageDeleteModelParams) error {
	_, err := q.db.Exec(ctx, manageDeleteModel, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteModelMappings = `-- name: ManageDeleteModelMappings :exec
UPDATE provider_model SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE model_id=$1 AND is_deleted=false
`

type ManageDeleteModelMappingsParams struct {
	ModelID   int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteModelMappings(ctx context.Context, arg ManageDeleteModelMappingsParams) error {
	_, err := q.db.Exec(ctx, manageDeleteModelMappings, arg.ModelID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteModelPermissions = `-- name: ManageDeleteModelPermissions :exec
UPDATE principal_group_model_permission SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE model_id=$1 AND is_deleted=false
`

type ManageDeleteModelPermissionsParams struct {
	ModelID   int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteModelPermissions(ctx context.Context, arg ManageDeleteModelPermissionsParams) error {
	_, err := q.db.Exec(ctx, manageDeleteModelPermissions, arg.ModelID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteProvider = `-- name: ManageDeleteProvider :exec
UPDATE provider
SET status='DISABLED',is_deleted=true,proxy_enabled=false,proxy_url_display=NULL,
    proxy_url_ciphertext=NULL,proxy_url_nonce=NULL,proxy_url_key_version=NULL,
    proxy_header_names='[]'::jsonb,proxy_headers_ciphertext=NULL,proxy_headers_nonce=NULL,
    proxy_headers_key_version=NULL,updated_by=$2,updated_at=$3
WHERE id=$1 AND is_deleted=false
`

type ManageDeleteProviderParams struct {
	ID        int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteProvider(ctx context.Context, arg ManageDeleteProviderParams) error {
	_, err := q.db.Exec(ctx, manageDeleteProvider, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteProviderEndpoint = `-- name: ManageDeleteProviderEndpoint :exec
DELETE FROM provider_endpoint WHERE provider_id=$1 AND protocol_type=$2
`

type ManageDeleteProviderEndpointParams struct {
	ProviderID   int64
	ProtocolType string
}

func (q *Queries) ManageDeleteProviderEndpoint(ctx context.Context, arg ManageDeleteProviderEndpointParams) error {
	_, err := q.db.Exec(ctx, manageDeleteProviderEndpoint, arg.ProviderID, arg.ProtocolType)
	return err
}

const manageDeleteProviderMapping = `-- name: ManageDeleteProviderMapping :exec
UPDATE provider_model
SET is_deleted=true,updated_by=$3,updated_at=$4
WHERE id=$1 AND provider_id=$2 AND is_deleted=false
`

type ManageDeleteProviderMappingParams struct {
	ID         int64
	ProviderID int64
	UpdatedBy  string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ManageDeleteProviderMapping(ctx context.Context, arg ManageDeleteProviderMappingParams) error {
	_, err := q.db.Exec(ctx, manageDeleteProviderMapping,
		arg.ID,
		arg.ProviderID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageDeleteProviderMappings = `-- name: ManageDeleteProviderMappings :exec
UPDATE provider_model
SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE provider_id=$1 AND is_deleted=false
`

type ManageDeleteProviderMappingsParams struct {
	ProviderID int64
	UpdatedBy  string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ManageDeleteProviderMappings(ctx context.Context, arg ManageDeleteProviderMappingsParams) error {
	_, err := q.db.Exec(ctx, manageDeleteProviderMappings, arg.ProviderID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteProviderResources = `-- name: ManageDeleteProviderResources :exec
UPDATE provider_credential
SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE provider_id=$1 AND is_deleted=false
`

type ManageDeleteProviderResourcesParams struct {
	ProviderID int64
	UpdatedBy  string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ManageDeleteProviderResources(ctx context.Context, arg ManageDeleteProviderResourcesParams) error {
	_, err := q.db.Exec(ctx, manageDeleteProviderResources, arg.ProviderID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const manageDeleteResource = `-- name: ManageDeleteResource :execrows
UPDATE provider_credential
SET is_deleted=true,updated_by=$2,updated_at=$3
WHERE id=$1 AND is_deleted=false
`

type ManageDeleteResourceParams struct {
	ID        int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageDeleteResource(ctx context.Context, arg ManageDeleteResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, manageDeleteResource, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const manageDeleteResourceQuotas = `-- name: ManageDeleteResourceQuotas :exec
DELETE FROM provider_credential_quota WHERE provider_credential_id=$1
`

func (q *Queries) ManageDeleteResourceQuotas(ctx context.Context, providerCredentialID int64) error {
	_, err := q.db.Exec(ctx, manageDeleteResourceQuotas, providerCredentialID)
	return err
}

const manageGrantModel = `-- name: ManageGrantModel :exec
INSERT INTO principal_group_model_permission(id,group_id,model_id,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$4,$5,$5)
`

type ManageGrantModelParams struct {
	ID        int64
	GroupID   int64
	ModelID   int64
	CreatedBy string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ManageGrantModel(ctx context.Context, arg ManageGrantModelParams) error {
	_, err := q.db.Exec(ctx, manageGrantModel,
		arg.ID,
		arg.GroupID,
		arg.ModelID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageGroup = `-- name: ManageGroup :one
SELECT id, is_deleted, status, group_code, group_name, remark, created_by, updated_by, created_at, updated_at FROM principal_group WHERE id=$1 AND is_deleted=false
`

func (q *Queries) ManageGroup(ctx context.Context, id int64) (PrincipalGroup, error) {
	row := q.db.QueryRow(ctx, manageGroup, id)
	var i PrincipalGroup
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.GroupCode,
		&i.GroupName,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const manageGroupMembers = `-- name: ManageGroupMembers :many
SELECT p.id, p.is_deleted, p.status, p.principal_type, p.name, p.remark, p.created_by, p.updated_by, p.created_at, p.updated_at FROM principal p JOIN principal_group_membership g ON g.principal_id=p.id
WHERE g.group_id=$1 AND g.is_deleted=false AND p.is_deleted=false AND p.principal_type='MEMBER' AND (p.id<$2 OR $2=0) ORDER BY p.id DESC LIMIT $3
`

type ManageGroupMembersParams struct {
	GroupID int64
	ID      int64
	Limit   int32
}

func (q *Queries) ManageGroupMembers(ctx context.Context, arg ManageGroupMembersParams) ([]Principal, error) {
	rows, err := q.db.Query(ctx, manageGroupMembers, arg.GroupID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.PrincipalType,
			&i.Name,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageGroupModels = `-- name: ManageGroupModels :many
SELECT m.id, m.is_deleted, m.status, m.model_code, m.display_name, m.input_modalities, m.output_modalities, m.remark, m.created_by, m.updated_by, m.created_at, m.updated_at, m.publisher_provider_id,p.provider_name AS publisher_provider_name
FROM model m
JOIN principal_group_model_permission g ON g.model_id=m.id
LEFT JOIN provider p ON p.id=m.publisher_provider_id
WHERE g.group_id=$1 AND g.is_deleted=false AND m.is_deleted=false AND (m.id<$2 OR $2=0) ORDER BY m.id DESC LIMIT $3
`

type ManageGroupModelsParams struct {
	GroupID int64
	ID      int64
	Limit   int32
}

type ManageGroupModelsRow struct {
	ID                    int64
	IsDeleted             bool
	Status                string
	ModelCode             string
	DisplayName           string
	InputModalities       []byte
	OutputModalities      []byte
	Remark                string
	CreatedBy             string
	UpdatedBy             string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PublisherProviderID   *int64
	PublisherProviderName *string
}

func (q *Queries) ManageGroupModels(ctx context.Context, arg ManageGroupModelsParams) ([]ManageGroupModelsRow, error) {
	rows, err := q.db.Query(ctx, manageGroupModels, arg.GroupID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageGroupModelsRow{}
	for rows.Next() {
		var i ManageGroupModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.ModelCode,
			&i.DisplayName,
			&i.InputModalities,
			&i.OutputModalities,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublisherProviderID,
			&i.PublisherProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageGroupStatus = `-- name: ManageGroupStatus :exec
UPDATE principal_group SET status=$2,updated_by=$3,updated_at=$4
WHERE id=$1 AND is_deleted=false
`

type ManageGroupStatusParams struct {
	ID        int64
	Status    string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageGroupStatus(ctx context.Context, arg ManageGroupStatusParams) error {
	_, err := q.db.Exec(ctx, manageGroupStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageGroups = `-- name: ManageGroups :many
SELECT id, is_deleted, status, group_code, group_name, remark, created_by, updated_by, created_at, updated_at FROM principal_group
WHERE is_deleted=false
  AND ($1::text = '' OR status = $1::text)
  AND (id<$2 OR $2=0)
ORDER BY id DESC
LIMIT $3
`

type ManageGroupsParams struct {
	Status    string
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ManageGroups(ctx context.Context, arg ManageGroupsParams) ([]PrincipalGroup, error) {
	rows, err := q.db.Query(ctx, manageGroups, arg.Status, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrincipalGroup{}
	for rows.Next() {
		var i PrincipalGroup
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.GroupCode,
			&i.GroupName,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageKeys = `-- name: ManageKeys :many
SELECT id,name,masked_key,status,expires_at,revoked_at,created_at FROM principal_access_key
WHERE principal_id=$1 AND is_deleted=false AND (id<$2 OR $2=0) ORDER BY id DESC LIMIT $3
`

type ManageKeysParams struct {
	PrincipalID int64
	ID          int64
	Limit       int32
}

type ManageKeysRow struct {
	ID        int64
	Name      string
	MaskedKey string
	Status    string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ManageKeys(ctx context.Context, arg ManageKeysParams) ([]ManageKeysRow, error) {
	rows, err := q.db.Query(ctx, manageKeys, arg.PrincipalID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageKeysRow{}
	for rows.Next() {
		var i ManageKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaskedKey,
			&i.Status,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageMember = `-- name: ManageMember :one
SELECT id, is_deleted, status, principal_type, name, remark, created_by, updated_by, created_at, updated_at FROM principal WHERE id=$1 AND is_deleted=false AND principal_type='MEMBER'
`

func (q *Queries) ManageMember(ctx context.Context, id int64) (Principal, error) {
	row := q.db.QueryRow(ctx, manageMember, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.PrincipalType,
		&i.Name,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const manageMemberGroups = `-- name: ManageMemberGroups :many
SELECT g.id, g.is_deleted, g.status, g.group_code, g.group_name, g.remark, g.created_by, g.updated_by, g.created_at, g.updated_at FROM principal_group g JOIN principal_group_membership pg ON pg.group_id=g.id
WHERE pg.principal_id=$1 AND pg.is_deleted=false AND g.is_deleted=false AND (g.id<$2 OR $2=0) ORDER BY g.id DESC LIMIT $3
`

type ManageMemberGroupsParams struct {
	PrincipalID int64
	ID          int64
	Limit       int32
}

func (q *Queries) ManageMemberGroups(ctx context.Context, arg ManageMemberGroupsParams) ([]PrincipalGroup, error) {
	rows, err := q.db.Query(ctx, manageMemberGroups, arg.PrincipalID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrincipalGroup{}
	for rows.Next() {
		var i PrincipalGroup
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.GroupCode,
			&i.GroupName,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageMemberStatus = `-- name: ManageMemberStatus :exec
UPDATE principal SET status=$2,updated_by=$3,updated_at=$4 WHERE id=$1 AND is_deleted=false AND principal_type='MEMBER'
`

type ManageMemberStatusParams struct {
	ID        int64
	Status    string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageMemberStatus(ctx context.Context, arg ManageMemberStatusParams) error {
	_, err := q.db.Exec(ctx, manageMemberStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageMemberSuggestions = `-- name: ManageMemberSuggestions :many
SELECT id, is_deleted, status, principal_type, name, remark, created_by, updated_by, created_at, updated_at FROM principal
WHERE is_deleted=false
  AND principal_type='MEMBER'
  AND strpos(lower(name), lower($1::text)) > 0
  AND (id<$2 OR $2=0)
ORDER BY id DESC
LIMIT $3
`

type ManageMemberSuggestionsParams struct {
	MemberName string
	AfterID    int64
	PageLimit  int32
}

func (q *Queries) ManageMemberSuggestions(ctx context.Context, arg ManageMemberSuggestionsParams) ([]Principal, error) {
	rows, err := q.db.Query(ctx, manageMemberSuggestions, arg.MemberName, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.PrincipalType,
			&i.Name,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageMembers = `-- name: ManageMembers :many
SELECT id, is_deleted, status, principal_type, name, remark, created_by, updated_by, created_at, updated_at FROM principal WHERE is_deleted=false AND principal_type='MEMBER' AND (id<$1 OR $1=0) ORDER BY id DESC LIMIT $2
`

type ManageMembersParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ManageMembers(ctx context.Context, arg ManageMembersParams) ([]Principal, error) {
	rows, err := q.db.Query(ctx, manageMembers, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.PrincipalType,
			&i.Name,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageMembershipExists = `-- name: ManageMembershipExists :one
SELECT EXISTS(SELECT 1 FROM principal_group_membership WHERE group_id=$1 AND principal_id=$2 AND is_deleted=false)
`

type ManageMembershipExistsParams struct {
	GroupID     int64
	PrincipalID int64
}

func (q *Queries) ManageMembershipExists(ctx context.Context, arg ManageMembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, manageMembershipExists, arg.GroupID, arg.PrincipalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const manageModel = `-- name: ManageModel :one
SELECT m.id, m.is_deleted, m.status, m.model_code, m.display_name, m.input_modalities, m.output_modalities, m.remark, m.created_by, m.updated_by, m.created_at, m.updated_at, m.publisher_provider_id,p.provider_name AS publisher_provider_name
FROM model m
LEFT JOIN provider p ON p.id=m.publisher_provider_id
WHERE m.id=$1 AND m.is_deleted=false
`

type ManageModelRow struct {
	ID                    int64
	IsDeleted             bool
	Status                string
	ModelCode             string
	DisplayName           string
	InputModalities       []byte
	OutputModalities      []byte
	Remark                string
	CreatedBy             string
	UpdatedBy             string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PublisherProviderID   *int64
	PublisherProviderName *string
}

func (q *Queries) ManageModel(ctx context.Context, id int64) (ManageModelRow, error) {
	row := q.db.QueryRow(ctx, manageModel, id)
	var i ManageModelRow
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.ModelCode,
		&i.DisplayName,
		&i.InputModalities,
		&i.OutputModalities,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublisherProviderID,
		&i.PublisherProviderName,
	)
	return i, err
}

const manageModelStatus = `-- name: ManageModelStatus :exec
UPDATE model SET status=$2,updated_by=$3,updated_at=$4 WHERE id=$1 AND is_deleted=false
`

type ManageModelStatusParams struct {
	ID        int64
	Status    string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageModelStatus(ctx context.Context, arg ManageModelStatusParams) error {
	_, err := q.db.Exec(ctx, manageModelStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageModels = `-- name: ManageModels :many
SELECT m.id, m.is_deleted, m.status, m.model_code, m.display_name, m.input_modalities, m.output_modalities, m.remark, m.created_by, m.updated_by, m.created_at, m.updated_at, m.publisher_provider_id,p.provider_name AS publisher_provider_name
FROM model m
LEFT JOIN provider p ON p.id=m.publisher_provider_id
WHERE m.is_deleted=false
  AND ($1::text = '' OR m.status = $1::text)
  AND (m.id<$2 OR $2=0)
ORDER BY m.id DESC
LIMIT $3
`

type ManageModelsParams struct {
	Status    string
	AfterID   int64
	PageLimit int32
}

type ManageModelsRow struct {
	ID                    int64
	IsDeleted             bool
	Status                string
	ModelCode             string
	DisplayName           string
	InputModalities       []byte
	OutputModalities      []byte
	Remark                string
	CreatedBy             string
	UpdatedBy             string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PublisherProviderID   *int64
	PublisherProviderName *string
}

func (q *Queries) ManageModels(ctx context.Context, arg ManageModelsParams) ([]ManageModelsRow, error) {
	rows, err := q.db.Query(ctx, manageModels, arg.Status, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageModelsRow{}
	for rows.Next() {
		var i ManageModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.ModelCode,
			&i.DisplayName,
			&i.InputModalities,
			&i.OutputModalities,
			&i.Remark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublisherProviderID,
			&i.PublisherProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageOperations = `-- name: ManageOperations :many
SELECT id,operator_name,operation_type,target_type,target_id,request_id,result,error_code,before_data,after_data,created_at
FROM operation_log WHERE (id<$1 OR $1=0) ORDER BY id DESC LIMIT $2
`

type ManageOperationsParams struct {
	ID    int64
	Limit int32
}

type ManageOperationsRow struct {
	ID            int64
	OperatorName  string
	OperationType string
	TargetType    string
	TargetID      *int64
	RequestID     *string
	Result        string
	ErrorCode     *string
	BeforeData    []byte
	AfterData     []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ManageOperations(ctx context.Context, arg ManageOperationsParams) ([]ManageOperationsRow, error) {
	rows, err := q.db.Query(ctx, manageOperations, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageOperationsRow{}
	for rows.Next() {
		var i ManageOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorName,
			&i.OperationType,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.Result,
			&i.ErrorCode,
			&i.BeforeData,
			&i.AfterData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managePermissionExists = `-- name: ManagePermissionExists :one
SELECT EXISTS(SELECT 1 FROM principal_group_model_permission WHERE group_id=$1 AND model_id=$2 AND is_deleted=false)
`

type ManagePermissionExistsParams struct {
	GroupID int64
	ModelID int64
}

func (q *Queries) ManagePermissionExists(ctx context.Context, arg ManagePermissionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, managePermissionExists, arg.GroupID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const manageProvider = `-- name: ManageProvider :one
SELECT id, is_deleted, status, provider_code, provider_name, provider_type, official_website, proxy_enabled, proxy_url_display, proxy_url_ciphertext, proxy_url_nonce, proxy_url_key_version, proxy_header_names, proxy_headers_ciphertext, proxy_headers_nonce, proxy_headers_key_version, created_by, updated_by, created_at, updated_at FROM provider WHERE id=$1 AND is_deleted=false
`

func (q *Queries) ManageProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, manageProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.ProviderCode,
		&i.ProviderName,
		&i.ProviderType,
		&i.OfficialWebsite,
		&i.ProxyEnabled,
		&i.ProxyUrlDisplay,
		&i.ProxyUrlCiphertext,
		&i.ProxyUrlNonce,
		&i.ProxyUrlKeyVersion,
		&i.ProxyHeaderNames,
		&i.ProxyHeadersCiphertext,
		&i.ProxyHeadersNonce,
		&i.ProxyHeadersKeyVersion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const manageProviderCredentialConfigured = `-- name: ManageProviderCredentialConfigured :one
SELECT EXISTS(
    SELECT 1 FROM provider_credential
    WHERE provider_id=$1 AND is_deleted=false
)
`

func (q *Queries) ManageProviderCredentialConfigured(ctx context.Context, providerID int64) (bool, error) {
	row := q.db.QueryRow(ctx, manageProviderCredentialConfigured, providerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const manageProviderEndpoints = `-- name: ManageProviderEndpoints :many
SELECT provider_id, protocol_type, base_url, created_by, updated_by, created_at, updated_at FROM provider_endpoint WHERE provider_id=$1 ORDER BY protocol_type
`

func (q *Queries) ManageProviderEndpoints(ctx context.Context, providerID int64) ([]ProviderEndpoint, error) {
	rows, err := q.db.Query(ctx, manageProviderEndpoints, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderEndpoint{}
	for rows.Next() {
		var i ProviderEndpoint
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProtocolType,
			&i.BaseUrl,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageProviderMappings = `-- name: ManageProviderMappings :many
SELECT id, is_deleted, provider_id, model_id, upstream_model_code, created_by, updated_by, created_at, updated_at, priority FROM provider_model
WHERE provider_id=$1 AND is_deleted=false
ORDER BY priority,id
`

func (q *Queries) ManageProviderMappings(ctx context.Context, providerID int64) ([]ProviderModel, error) {
	rows, err := q.db.Query(ctx, manageProviderMappings, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderModel{}
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.ProviderID,
			&i.ModelID,
			&i.UpstreamModelCode,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageProviderModelCounts = `-- name: ManageProviderModelCounts :many
SELECT pm.provider_id, COUNT(*)::bigint AS model_count
FROM provider_model pm
JOIN model m ON m.id=pm.model_id
WHERE pm.provider_id=ANY($1::bigint[])
  AND pm.is_deleted=false
  AND m.is_deleted=false
  AND m.status='ACTIVE'
GROUP BY pm.provider_id
ORDER BY pm.provider_id
`

type ManageProviderModelCountsRow struct {
	ProviderID int64
	ModelCount int64
}

func (q *Queries) ManageProviderModelCounts(ctx context.Context, providerIds []int64) ([]ManageProviderModelCountsRow, error) {
	rows, err := q.db.Query(ctx, manageProviderModelCounts, providerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageProviderModelCountsRow{}
	for rows.Next() {
		var i ManageProviderModelCountsRow
		if err := rows.Scan(&i.ProviderID, &i.ModelCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageProviderStatus = `-- name: ManageProviderStatus :exec
UPDATE provider SET status=$2,updated_by=$3,updated_at=$4 WHERE id=$1 AND is_deleted=false
`

type ManageProviderStatusParams struct {
	ID        int64
	Status    string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageProviderStatus(ctx context.Context, arg ManageProviderStatusParams) error {
	_, err := q.db.Exec(ctx, manageProviderStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageProviders = `-- name: ManageProviders :many
SELECT id, is_deleted, status, provider_code, provider_name, provider_type, official_website, proxy_enabled, proxy_url_display, proxy_url_ciphertext, proxy_url_nonce, proxy_url_key_version, proxy_header_names, proxy_headers_ciphertext, proxy_headers_nonce, proxy_headers_key_version, created_by, updated_by, created_at, updated_at FROM provider
WHERE is_deleted=false
  AND ($1::text = '' OR provider_type = $1::text)
  AND (id < $2 OR $2 = 0)
ORDER BY id DESC
LIMIT $3
`

type ManageProvidersParams struct {
	ProviderType string
	AfterID      int64
	PageLimit    int32
}

func (q *Queries) ManageProviders(ctx context.Context, arg ManageProvidersParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, manageProviders, arg.ProviderType, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.Status,
			&i.ProviderCode,
			&i.ProviderName,
			&i.ProviderType,
			&i.OfficialWebsite,
			&i.ProxyEnabled,
			&i.ProxyUrlDisplay,
			&i.ProxyUrlCiphertext,
			&i.ProxyUrlNonce,
			&i.ProxyUrlKeyVersion,
			&i.ProxyHeaderNames,
			&i.ProxyHeadersCiphertext,
			&i.ProxyHeadersNonce,
			&i.ProxyHeadersKeyVersion,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageRemoveMember = `-- name: ManageRemoveMember :exec
UPDATE principal_group_membership SET is_deleted=true,updated_by=$3,updated_at=$4 WHERE group_id=$1 AND principal_id=$2 AND is_deleted=false
`

type ManageRemoveMemberParams struct {
	GroupID     int64
	PrincipalID int64
	UpdatedBy   string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ManageRemoveMember(ctx context.Context, arg ManageRemoveMemberParams) error {
	_, err := q.db.Exec(ctx, manageRemoveMember,
		arg.GroupID,
		arg.PrincipalID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageResource = `-- name: ManageResource :one
SELECT id, is_deleted, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, created_by, updated_by, created_at, updated_at, runtime_status, blocked_reason, blocked_at, last_error_at, last_http_status, last_error_code, auth_type, auth_adapter, subscription_type, plan_code, external_account_ref, priority, effective_at, expires_at, quota_status, quota_checked_at, quota_resets_at, credential_refreshed_at, credential_expires_at FROM provider_credential WHERE id=$1 AND is_deleted=false
`

func (q *Queries) ManageResource(ctx context.Context, id int64) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, manageResource, id)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.ProviderID,
		&i.ResourceName,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.KeyVersion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeStatus,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.LastErrorAt,
		&i.LastHttpStatus,
		&i.LastErrorCode,
		&i.AuthType,
		&i.AuthAdapter,
		&i.SubscriptionType,
		&i.PlanCode,
		&i.ExternalAccountRef,
		&i.Priority,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.QuotaStatus,
		&i.QuotaCheckedAt,
		&i.QuotaResetsAt,
		&i.CredentialRefreshedAt,
		&i.CredentialExpiresAt,
	)
	return i, err
}

const manageResourceQuotas = `-- name: ManageResourceQuotas :many
SELECT provider_credential_id, quota_code, quota_name, quota_status, quota_unit, limit_value, used_value, remaining_value, used_percent, window_duration_seconds, resets_at, reached_type, observed_at, created_at, updated_at FROM provider_credential_quota
WHERE provider_credential_id=$1 ORDER BY quota_code
`

func (q *Queries) ManageResourceQuotas(ctx context.Context, providerCredentialID int64) ([]ProviderCredentialQuotum, error) {
	rows, err := q.db.Query(ctx, manageResourceQuotas, providerCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCredentialQuotum{}
	for rows.Next() {
		var i ProviderCredentialQuotum
		if err := rows.Scan(
			&i.ProviderCredentialID,
			&i.QuotaCode,
			&i.QuotaName,
			&i.QuotaStatus,
			&i.QuotaUnit,
			&i.LimitValue,
			&i.UsedValue,
			&i.RemainingValue,
			&i.UsedPercent,
			&i.WindowDurationSeconds,
			&i.ResetsAt,
			&i.ReachedType,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageResources = `-- name: ManageResources :many
SELECT id,provider_id,resource_name,auth_type,auth_adapter,subscription_type,plan_code,
       external_account_ref,priority,effective_at,expires_at,quota_status,quota_checked_at,
       quota_resets_at,credential_refreshed_at,credential_expires_at,
       runtime_status,blocked_reason,blocked_at,last_error_at,last_http_status,
       last_error_code,created_at,updated_at FROM provider_credential
WHERE is_deleted=false AND (id<$1 OR $1=0) ORDER BY id DESC LIMIT $2
`

type ManageResourcesParams struct {
	ID    int64
	Limit int32
}

type ManageResourcesRow struct {
	ID                    int64
	ProviderID            int64
	ResourceName          string
	AuthType              string
	AuthAdapter           string
	SubscriptionType      *string
	PlanCode              *string
	ExternalAccountRef    *string
	Priority              int32
	EffectiveAt           pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	QuotaStatus           string
	QuotaCheckedAt        pgtype.Timestamptz
	QuotaResetsAt         pgtype.Timestamptz
	CredentialRefreshedAt pgtype.Timestamptz
	CredentialExpiresAt   pgtype.Timestamptz
	RuntimeStatus         string
	BlockedReason         *string
	BlockedAt             pgtype.Timestamptz
	LastErrorAt           pgtype.Timestamptz
	LastHttpStatus        *int32
	LastErrorCode         *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) ManageResources(ctx context.Context, arg ManageResourcesParams) ([]ManageResourcesRow, error) {
	rows, err := q.db.Query(ctx, manageResources, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageResourcesRow{}
	for rows.Next() {
		var i ManageResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ResourceName,
			&i.AuthType,
			&i.AuthAdapter,
			&i.SubscriptionType,
			&i.PlanCode,
			&i.ExternalAccountRef,
			&i.Priority,
			&i.EffectiveAt,
			&i.ExpiresAt,
			&i.QuotaStatus,
			&i.QuotaCheckedAt,
			&i.QuotaResetsAt,
			&i.CredentialRefreshedAt,
			&i.CredentialExpiresAt,
			&i.RuntimeStatus,
			&i.BlockedReason,
			&i.BlockedAt,
			&i.LastErrorAt,
			&i.LastHttpStatus,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageRestoreResourceRuntime = `-- name: ManageRestoreResourceRuntime :execrows
UPDATE provider_credential
SET runtime_status='HEALTHY',blocked_reason=NULL,blocked_at=NULL,last_error_at=NULL,
    last_http_status=NULL,last_error_code=NULL,updated_by=$2,updated_at=$3
WHERE id=$1 AND is_deleted=false AND runtime_status='BLOCKED'
`

type ManageRestoreResourceRuntimeParams struct {
	ID        int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageRestoreResourceRuntime(ctx context.Context, arg ManageRestoreResourceRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, manageRestoreResourceRuntime, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const manageRevokeMemberKeys = `-- name: ManageRevokeMemberKeys :exec
UPDATE principal_access_key SET status='REVOKED',revoked_at=$3,updated_by=$2,updated_at=$3
WHERE principal_id=$1 AND is_deleted=false AND status<>'REVOKED'
`

type ManageRevokeMemberKeysParams struct {
	PrincipalID int64
	UpdatedBy   string
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) ManageRevokeMemberKeys(ctx context.Context, arg ManageRevokeMemberKeysParams) error {
	_, err := q.db.Exec(ctx, manageRevokeMemberKeys, arg.PrincipalID, arg.UpdatedBy, arg.RevokedAt)
	return err
}

const manageRevokeModel = `-- name: ManageRevokeModel :exec
UPDATE principal_group_model_permission SET is_deleted=true,updated_by=$3,updated_at=$4 WHERE group_id=$1 AND model_id=$2 AND is_deleted=false
`

type ManageRevokeModelParams struct {
	GroupID   int64
	ModelID   int64
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageRevokeModel(ctx context.Context, arg ManageRevokeModelParams) error {
	_, err := q.db.Exec(ctx, manageRevokeModel,
		arg.GroupID,
		arg.ModelID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateGroup = `-- name: ManageUpdateGroup :exec
UPDATE principal_group SET group_name=$2,remark=$3,updated_by=$4,updated_at=$5
WHERE id=$1 AND is_deleted=false
`

type ManageUpdateGroupParams struct {
	ID        int64
	GroupName string
	Remark    *string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageUpdateGroup(ctx context.Context, arg ManageUpdateGroupParams) error {
	_, err := q.db.Exec(ctx, manageUpdateGroup,
		arg.ID,
		arg.GroupName,
		arg.Remark,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateMember = `-- name: ManageUpdateMember :exec
UPDATE principal SET name=$2,remark=$3,updated_by=$4,updated_at=$5
WHERE id=$1 AND is_deleted=false AND principal_type='MEMBER'
`

type ManageUpdateMemberParams struct {
	ID        int64
	Name      string
	Remark    *string
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ManageUpdateMember(ctx context.Context, arg ManageUpdateMemberParams) error {
	_, err := q.db.Exec(ctx, manageUpdateMember,
		arg.ID,
		arg.Name,
		arg.Remark,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateModel = `-- name: ManageUpdateModel :exec
UPDATE model SET model_code=$2,display_name=$3,input_modalities=$4,output_modalities=$5,remark=$6,publisher_provider_id=$7,updated_by=$8,updated_at=$9
WHERE id=$1 AND is_deleted=false
`

type ManageUpdateModelParams struct {
	ID                  int64
	ModelCode           string
	DisplayName         string
	InputModalities     []byte
	OutputModalities    []byte
	Remark              string
	PublisherProviderID *int64
	UpdatedBy           string
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) ManageUpdateModel(ctx context.Context, arg ManageUpdateModelParams) error {
	_, err := q.db.Exec(ctx, manageUpdateModel,
		arg.ID,
		arg.ModelCode,
		arg.DisplayName,
		arg.InputModalities,
		arg.OutputModalities,
		arg.Remark,
		arg.PublisherProviderID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateProvider = `-- name: ManageUpdateProvider :exec
UPDATE provider SET provider_name=$2,official_website=$3,proxy_enabled=$4,proxy_url_display=$5,proxy_url_ciphertext=$6,proxy_url_nonce=$7,proxy_url_key_version=$8,proxy_header_names=$9,proxy_headers_ciphertext=$10,proxy_headers_nonce=$11,proxy_headers_key_version=$12,updated_by=$13,updated_at=$14
WHERE id=$1 AND is_deleted=false
`

type ManageUpdateProviderParams struct {
	ID                     int64
	ProviderName           string
	OfficialWebsite        *string
	ProxyEnabled           bool
	ProxyUrlDisplay        *string
	ProxyUrlCiphertext     []byte
	ProxyUrlNonce          []byte
	ProxyUrlKeyVersion     *int32
	ProxyHeaderNames       []byte
	ProxyHeadersCiphertext []byte
	ProxyHeadersNonce      []byte
	ProxyHeadersKeyVersion *int32
	UpdatedBy              string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) ManageUpdateProvider(ctx context.Context, arg ManageUpdateProviderParams) error {
	_, err := q.db.Exec(ctx, manageUpdateProvider,
		arg.ID,
		arg.ProviderName,
		arg.OfficialWebsite,
		arg.ProxyEnabled,
		arg.ProxyUrlDisplay,
		arg.ProxyUrlCiphertext,
		arg.ProxyUrlNonce,
		arg.ProxyUrlKeyVersion,
		arg.ProxyHeaderNames,
		arg.ProxyHeadersCiphertext,
		arg.ProxyHeadersNonce,
		arg.ProxyHeadersKeyVersion,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateProviderMapping = `-- name: ManageUpdateProviderMapping :exec
UPDATE provider_model
SET upstream_model_code=$3,priority=$4,updated_by=$5,updated_at=$6
WHERE id=$1 AND provider_id=$2 AND is_deleted=false
`

type ManageUpdateProviderMappingParams struct {
	ID                int64
	ProviderID        int64
	UpstreamModelCode string
	Priority          int32
	UpdatedBy         string
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ManageUpdateProviderMapping(ctx context.Context, arg ManageUpdateProviderMappingParams) error {
	_, err := q.db.Exec(ctx, manageUpdateProviderMapping,
		arg.ID,
		arg.ProviderID,
		arg.UpstreamModelCode,
		arg.Priority,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpdateResource = `-- name: ManageUpdateResource :exec
UPDATE provider_credential SET resource_name=$2,auth_type=$3,auth_adapter=$4,subscription_type=$5,
plan_code=$6,external_account_ref=$7,priority=$8,effective_at=$9,expires_at=$10,
quota_status=$11,quota_checked_at=$12,quota_resets_at=$13,
credential_refreshed_at=$14,credential_expires_at=$15,
credential_ciphertext=$16,credential_nonce=$17,key_version=$18,
runtime_status=CASE WHEN credential_ciphertext IS DISTINCT FROM $16 THEN 'HEALTHY' ELSE runtime_status END,
blocked_reason=CASE WHEN credential_ciphertext IS DISTINCT FROM $16 THEN NULL ELSE blocked_reason END,
blocked_at=CASE WHEN credential_ciphertext IS DISTINCT FROM $16 THEN NULL ELSE blocked_at END,
last_error_at=CASE WHEN credential_ciphertext IS DISTINCT FROM $16 THEN NULL ELSE last_error_at END,
last_http_status=CASE WHEN credential_ciphertext IS DISTINCT FROM $16 THEN NULL ELSE last_http_status END,
last_error_code=CASE WHEN credential_ciphertext IS DISTINCT FROM $16 THEN NULL ELSE last_error_code END,
updated_by=$19,updated_at=$20
WHERE id=$1 AND is_deleted=false
`

type ManageUpdateResourceParams struct {
	ID                    int64
	ResourceName          string
	AuthType              string
	AuthAdapter           string
	SubscriptionType      *string
	PlanCode              *string
	ExternalAccountRef    *string
	Priority              int32
	EffectiveAt           pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	QuotaStatus           string
	QuotaCheckedAt        pgtype.Timestamptz
	QuotaResetsAt         pgtype.Timestamptz
	CredentialRefreshedAt pgtype.Timestamptz
	CredentialExpiresAt   pgtype.Timestamptz
	CredentialCiphertext  []byte
	CredentialNonce       []byte
	KeyVersion            int32
	UpdatedBy             string
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) ManageUpdateResource(ctx context.Context, arg ManageUpdateResourceParams) error {
	_, err := q.db.Exec(ctx, manageUpdateResource,
		arg.ID,
		arg.ResourceName,
		arg.AuthType,
		arg.AuthAdapter,
		arg.SubscriptionType,
		arg.PlanCode,
		arg.ExternalAccountRef,
		arg.Priority,
		arg.EffectiveAt,
		arg.ExpiresAt,
		arg.QuotaStatus,
		arg.QuotaCheckedAt,
		arg.QuotaResetsAt,
		arg.CredentialRefreshedAt,
		arg.CredentialExpiresAt,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyVersion,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const manageUpsertProviderEndpoint = `-- name: ManageUpsertProviderEndpoint :exec
INSERT INTO provider_endpoint(provider_id,protocol_type,base_url,created_by,updated_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$4,$5,$5)
ON CONFLICT(provider_id,protocol_type) DO UPDATE
SET base_url=excluded.base_url,updated_by=excluded.updated_by,updated_at=excluded.updated_at
`

type ManageUpsertProviderEndpointParams struct {
	ProviderID   int64
	ProtocolType string
	BaseUrl      string
	CreatedBy    string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ManageUpsertProviderEndpoint(ctx context.Context, arg ManageUpsertProviderEndpointParams) error {
	_, err := q.db.Exec(ctx, manageUpsertProviderEndpoint,
		arg.ProviderID,
		arg.ProtocolType,
		arg.BaseUrl,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}
