// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// 调用凭证；仅识别主体，不存储权限或完整 Key
type AccessKey struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 所属治理主体 ID
	PrincipalID int64
	// 完整 Access Key 的 SHA-256 摘要，32 bytes
	KeyHash []byte
	// 仅用于识别的 Key 前缀，不能用于认证
	KeyPrefix string
	// 凭证名称
	Name string
	// 凭证状态：ACTIVE=启用；DISABLED=停用；REVOKED=已撤销
	Status string
	// 到期时间；NULL=永不过期
	ExpiresAt pgtype.Timestamptz
	// 最后使用时间；NULL=从未使用
	LastUsedAt pgtype.Timestamptz
	// 撤销时间；NULL=未撤销
	RevokedAt pgtype.Timestamptz
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 管理面管理员；与调用面 Principal 分离
type AdminUser struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 管理员用户名
	Username string
	// 密码慢 Hash；不保存明文
	PasswordHash string
	// 管理员显示名称
	DisplayName string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 连续登录失败次数
	FailedLoginCount int64
	// 锁定截止时间；NULL=未锁定
	LockedUntil pgtype.Timestamptz
	// 最后登录时间；NULL=从未登录
	LastLoginAt pgtype.Timestamptz
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
	// 凭证版本；重置密码递增，使旧管理员 JWT 失效
	CredentialVersion int64
}

// AI 使用治理分组
type AiGroup struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 分组业务编码
	GroupCode string
	// 分组名称
	GroupName string
	// 备注；NULL=未设置
	Remark *string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 官方模型目录；已有逻辑编码兼容保留，管理员可显式修正
type AiModel struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 官方标准模型编码；已有客户端编码仅由管理员显式修改
	ModelCode string
	// 官方模型名称
	DisplayName string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
	// 输入类型 JSON 数组：TEXT、IMAGE、AUDIO、VIDEO，非空且无重复
	InputModalities []byte
	// 输出类型 JSON 数组：TEXT、IMAGE、AUDIO、VIDEO，非空且无重复
	OutputModalities []byte
	// 模型用途、限制等备注，空字符串表示未填写
	Remark string
}

// 模型服务供应方；不保存调用凭证
type AiProvider struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 供应方业务编码
	ProviderCode string
	// 供应方名称
	ProviderName string
	// 供应方类型：OFFICIAL=官方供应方
	ProviderType string
	// Anthropic 兼容协议上游基础地址；NULL=未配置
	AnthropicBaseUrl *string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
	// OpenAI 兼容协议上游基础地址；NULL=未配置
	OpenaiBaseUrl *string
	// 服务商官方网站；NULL=未填写
	OfficialWebsite *string
	// 是否通过服务商专属出站代理访问上游
	ProxyEnabled bool
	// 脱敏后的代理 URL，仅用于管理端展示
	ProxyUrlDisplay *string
	// 完整代理 URL 的 AES-256-GCM 密文，可包含用户名和密码
	ProxyUrlCiphertext []byte
	// 代理 URL 密文的 AES-GCM 随机 Nonce
	ProxyUrlNonce []byte
	// 代理 URL 密文的根密钥版本
	ProxyUrlKeyVersion *int32
	// 代理 Header 名称列表，不含 Header Value
	ProxyHeaderNames []byte
	// 代理 Header Key/Value 对象的 AES-256-GCM 密文
	ProxyHeadersCiphertext []byte
	// 代理 Header 密文的 AES-GCM 随机 Nonce
	ProxyHeadersNonce []byte
	// 代理 Header 密文的根密钥版本
	ProxyHeadersKeyVersion *int32
}

// 主体视角的一次 AI 请求事实；无逻辑删除
type AiRequest struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 所属组织 ID
	OrganizationID int64
	// 全链路请求标识
	RequestID string
	// 已识别的治理主体 ID
	PrincipalID int64
	// 已识别的逻辑模型 ID；NULL=模型未识别
	ModelID *int64
	// 使用场景：MODEL_GATEWAY=模型网关调用
	UsageScene string
	// 客户端协议：ANTHROPIC=Messages；OPENAI=Chat Completions
	ClientProtocol string
	// 请求开始时间，UTC
	RequestAt pgtype.Timestamptz
	// 请求结束时间，UTC
	CompletedAt pgtype.Timestamptz
	// 请求耗时，毫秒
	LatencyMs int64
	// 调用最终状态：SUCCESS=成功；FAILED=失败；CANCELLED=客户端取消
	Status string
	// 稳定大写错误码；NULL=无错误
	ErrorType *string
	// 事实记录创建时间，UTC
	CreatedAt pgtype.Timestamptz
}

// 组织持有的供应方调用资源；归属于 Provider
type AiResource struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 资源所属供应方 ID，不归属于 Provider Model
	ProviderID int64
	// 资源名称
	ResourceName string
	// AES-256-GCM 密文，包含 16-byte 认证标签；禁止明文
	CredentialCiphertext []byte
	// AES-GCM 随机 Nonce，12 bytes；每次加密重新生成
	CredentialNonce []byte
	// 加密根密钥版本，不含 Master Key 本身
	KeyVersion int32
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 最后调用时间；NULL=从未使用
	LastActiveAt pgtype.Timestamptz
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 分组模型显式授权；默认拒绝，多组授权取并集
type GroupModelPermission struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 被授权分组 ID
	GroupID int64
	// 被授权逻辑模型 ID
	ModelID int64
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 管理员与系统操作日志；Append Only，普通操作禁止更新和删除
type OperationLog struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 所属组织 ID
	OrganizationID int64
	// 操作人类型：ADMIN=管理员；SYSTEM=系统
	OperatorType string
	// 管理员 ID；NULL=系统操作
	OperatorID *int64
	// 操作人名称快照
	OperatorName string
	// 业务模块：MEMBER=成员；ACCESS_KEY=调用凭证；GROUP=分组；MODEL=模型；PROVIDER=服务商；RESOURCE=服务商凭证；AUTH=认证
	Module string
	// ADMIN_INITIALIZE=初始化首位管理员；操作类型：MEMBER_CREATE=创建成员；MEMBER_STATUS_CHANGE=成员状态变更；ACCESS_KEY_CREATE=创建调用凭证；ACCESS_KEY_REVOKE=撤销调用凭证；GROUP_CREATE=创建分组；GROUP_MEMBER_ADD=成员加入分组；GROUP_MEMBER_REMOVE=成员移出分组；GROUP_MODEL_GRANT=分组模型授权；GROUP_MODEL_REVOKE=撤销分组模型授权；MODEL_STATUS_CHANGE=模型状态变更；RESOURCE_CREATE=创建资源；RESOURCE_CREDENTIAL_UPDATE=更新资源凭证；RESOURCE_STATUS_CHANGE=资源状态变更；RESOURCE_CONNECTION_TEST=测试资源连接；LOGIN_SUCCESS=登录成功；LOGIN_FAILED=登录失败；LOGIN_LOCKED=登录锁定
	OperationType string
	// 目标类型：PRINCIPAL=治理主体；ACCESS_KEY=调用凭证；GROUP=分组；MODEL=模型；PROVIDER=服务商；RESOURCE=服务商凭证；ADMIN_USER=管理员
	TargetType string
	// 目标 ID；NULL=失败操作尚未创建对象
	TargetID *int64
	// 目标名称快照；NULL=未设置
	TargetName *string
	// 关联 HTTP 请求标识；系统操作无请求时为空；NULL=未设置
	RequestID *string
	// HTTP 请求方法；系统操作无请求时为空；NULL=未设置
	RequestMethod *string
	// HTTP 路径，不包含 Query String；系统操作时可为空；NULL=未设置
	RequestPath *string
	// 调用者 IP；NULL=无 HTTP 来源
	IpAddress *netip.Addr
	// 客户端 User Agent；NULL=无此信息；NULL=未设置
	UserAgent *string
	// 操作结果：SUCCESS=成功；FAILED=失败
	Result string
	// 稳定大写错误码；NULL=无错误
	ErrorCode *string
	// 变更前安全快照；NULL=不适用；禁止密码、Hash、Credential、JWT、完整 Key
	BeforeData []byte
	// 变更后安全快照；NULL=不适用；禁止密码、Hash、Credential、JWT、完整 Key
	AfterData []byte
	// 备注；NULL=未设置
	Remark *string
	// 事实记录创建时间，UTC
	CreatedAt pgtype.Timestamptz
}

// 组织；P0-MVP 仅支持单组织
type Organization struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 组织业务编码
	OrganizationCode string
	// 组织名称
	OrganizationName string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 备注；NULL=未设置
	Remark *string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 统一治理主体；MVP 仅建设 MEMBER 流程
type Principal struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 主体类型：MEMBER=成员；APPLICATION=应用，仅预留类型
	PrincipalType string
	// 主体名称
	Name string
	// 备注；NULL=未设置
	Remark *string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 主体与分组的多对多关系
type PrincipalGroup struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 所属组织 ID
	OrganizationID int64
	// 治理主体 ID
	PrincipalID int64
	// 分组 ID
	GroupID int64
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 供应方与逻辑模型的多对多映射
type ProviderModel struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 供应方 ID
	ProviderID int64
	// 逻辑模型 ID
	ModelID int64
	// 实际发送到上游的模型编码
	UpstreamModelCode string
	// 上游协议：ANTHROPIC=Messages；OPENAI=Chat Completions
	ProtocolType string
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 一次真实上游调用 Attempt 的用量事实；无逻辑删除
type UsageRecord struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 所属组织 ID
	OrganizationID int64
	// 所属请求标识
	RequestID string
	// 上游调用序号；MVP 固定为 1，不重试或 Failover
	AttemptNo int64
	// 治理主体 ID
	PrincipalID int64
	// 实际供应方 ID
	ProviderID int64
	// 实际供应方模型映射 ID
	ProviderModelID int64
	// 实际调用资源 ID
	ResourceID int64
	// 逻辑模型 ID
	ModelID int64
	// 使用场景：MODEL_GATEWAY=模型网关调用
	UsageScene string
	// 输入 Token 数；NULL=上游未返回可靠值，0=已确认零用量
	InputTokens *int64
	// 输出 Token 数；NULL=上游未返回可靠值，0=已确认零用量
	OutputTokens *int64
	// 缓存读取 Token 数；NULL=上游未返回可靠值，0=已确认零用量
	CachedInputTokens *int64
	// 计量单位：TOKEN=Token；CALL=调用次数；IMAGE=图像数量；SECOND=秒数
	BillingUnit string
	// 计量数量；NULL=无法可靠确认；非客户销售金额
	BillingQuantity pgtype.Numeric
	// 上游成本快照；NULL=未计算，MVP 不实现成本计算
	CostAmount pgtype.Numeric
	// 成本币种；NULL=未计算成本
	CostCurrency *string
	// 真实上游调用开始时间，UTC
	StartedAt pgtype.Timestamptz
	// 上游调用结束时间，UTC
	CompletedAt pgtype.Timestamptz
	// 上游耗时，毫秒
	LatencyMs int64
	// 调用最终状态：SUCCESS=成功；FAILED=失败；CANCELLED=客户端取消
	Status string
	// 稳定大写错误码；NULL=无错误
	ErrorType *string
	// 事实记录创建时间，UTC
	CreatedAt pgtype.Timestamptz
}
