// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// 管理面管理员；与调用面 Principal 分离
type AdminUser struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 管理员用户名
	Username string
	// 密码慢 Hash；不保存明文
	PasswordHash string
	// 管理员显示名称
	DisplayName string
	// 连续登录失败次数
	FailedLoginCount int64
	// 锁定截止时间；NULL=未锁定
	LockedUntil pgtype.Timestamptz
	// 最后登录时间；NULL=从未登录
	LastLoginAt pgtype.Timestamptz
	// 凭证版本；重置密码递增，使旧管理员 JWT 失效
	CredentialVersion int64
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 平台稳定逻辑模型；发布厂商仅用于归属展示，与调用供应方映射解耦
type Model struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 官方标准模型编码；已有客户端编码仅由管理员显式修改
	ModelCode string
	// 官方模型名称
	DisplayName string
	// 模型发布厂商对应的服务商 ID；手工创建且尚未由官方目录同步时为空
	PublisherProviderID *int64
	// 输入类型 JSON 数组：TEXT、IMAGE、AUDIO、VIDEO，非空且无重复
	InputModalities []byte
	// 输出类型 JSON 数组：TEXT、IMAGE、AUDIO、VIDEO，非空且无重复
	OutputModalities []byte
	// 模型用途、限制等备注，空字符串表示未填写
	Remark string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 管理员与系统操作日志；Append Only，普通操作禁止更新和删除
type OperationLog struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 操作人类型：ADMIN=管理员；SYSTEM=系统
	OperatorType string
	// 管理员 ID；NULL=系统操作
	OperatorID *int64
	// 操作人名称快照
	OperatorName string
	// 业务模块：MEMBER=成员；ACCESS_KEY=调用凭证；GROUP=分组；MODEL=模型；PROVIDER=服务商；RESOURCE=服务商凭证；AUTH=认证
	Module string
	// ADMIN_INITIALIZE=初始化首位管理员；操作类型：MEMBER_CREATE=创建成员；MEMBER_STATUS_CHANGE=成员状态变更；ACCESS_KEY_CREATE=创建调用凭证；ACCESS_KEY_REVOKE=撤销调用凭证；GROUP_CREATE=创建分组；GROUP_MEMBER_ADD=成员加入分组；GROUP_MEMBER_REMOVE=成员移出分组；GROUP_MODEL_GRANT=分组模型授权；GROUP_MODEL_REVOKE=撤销分组模型授权；MODEL_STATUS_CHANGE=模型状态变更；RESOURCE_CREATE=创建资源；RESOURCE_CREDENTIAL_UPDATE=更新资源凭证；RESOURCE_STATUS_CHANGE=资源状态变更；RESOURCE_CONNECTION_TEST=测试资源连接；LOGIN_SUCCESS=登录成功；LOGIN_FAILED=登录失败；LOGIN_LOCKED=登录锁定
	OperationType string
	// 目标类型：PRINCIPAL=治理主体；ACCESS_KEY=调用凭证；GROUP=分组；MODEL=模型；PROVIDER=服务商；RESOURCE=服务商凭证；ADMIN_USER=管理员
	TargetType string
	// 目标 ID；NULL=失败操作尚未创建对象
	TargetID *int64
	// 目标名称快照；NULL=未设置
	TargetName *string
	// 关联 HTTP 请求标识；系统操作无请求时为空；NULL=未设置
	RequestID *string
	// HTTP 请求方法；系统操作无请求时为空；NULL=未设置
	RequestMethod *string
	// HTTP 路径，不包含 Query String；系统操作时可为空；NULL=未设置
	RequestPath *string
	// 调用者 IP；NULL=无 HTTP 来源
	IpAddress *netip.Addr
	// 客户端 User Agent；NULL=无此信息；NULL=未设置
	UserAgent *string
	// 操作结果：SUCCESS=成功；FAILED=失败
	Result string
	// 稳定大写错误码；NULL=无错误
	ErrorCode *string
	// 变更前安全快照；NULL=不适用；禁止密码、Hash、Credential、JWT、完整 Key
	BeforeData []byte
	// 变更后安全快照；NULL=不适用；禁止密码、Hash、Credential、JWT、完整 Key
	AfterData []byte
	// 备注；NULL=未设置
	Remark *string
	// 事实记录创建时间，UTC
	CreatedAt pgtype.Timestamptz
}

// 统一治理主体；MVP 仅建设 MEMBER 流程
type Principal struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 主体类型：MEMBER=成员；APPLICATION=应用，仅预留类型
	PrincipalType string
	// 主体名称
	Name string
	// 备注；NULL=未设置
	Remark *string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 调用主体访问凭证；仅识别主体，不存储权限或完整 Key
type PrincipalAccessKey struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 凭证状态：ACTIVE=启用；DISABLED=停用；REVOKED=已撤销
	Status string
	// 所属治理主体 ID
	PrincipalID int64
	// 完整 Access Key 的 SHA-256 摘要，32 bytes
	KeyHash []byte
	// 脱敏后的 Access Key，仅用于识别和展示，不能用于认证
	MaskedKey string
	// 凭证名称
	Name string
	// 到期时间；NULL=永不过期
	ExpiresAt pgtype.Timestamptz
	// 最后使用时间；NULL=从未使用
	LastUsedAt pgtype.Timestamptz
	// 撤销时间；NULL=未撤销
	RevokedAt pgtype.Timestamptz
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 调用主体的 AI 使用治理分组
type PrincipalGroup struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 分组业务编码
	GroupCode string
	// 分组名称
	GroupName string
	// 备注；NULL=未设置
	Remark *string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 调用主体与治理分组的多对多关系
type PrincipalGroupMembership struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 治理主体 ID
	PrincipalID int64
	// 分组 ID
	GroupID int64
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 主体分组的模型显式授权；默认拒绝，多组授权取并集
type PrincipalGroupModelPermission struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 被授权分组 ID
	GroupID int64
	// 被授权逻辑模型 ID
	ModelID int64
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 模型服务供应方；不保存企业调用凭证
type Provider struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 状态：ACTIVE=启用；DISABLED=停用
	Status string
	// 供应方业务编码
	ProviderCode string
	// 供应方名称
	ProviderName string
	// 供应方类型：OFFICIAL=官方供应方
	ProviderType string
	// 服务商官方网站；NULL=未填写
	OfficialWebsite *string
	// 是否通过服务商专属出站代理访问上游
	ProxyEnabled bool
	// 脱敏后的代理 URL，仅用于管理端展示
	ProxyUrlDisplay *string
	// 完整代理 URL 的 AES-256-GCM 密文，可包含用户名和密码
	ProxyUrlCiphertext []byte
	// 代理 URL 密文的 AES-GCM 随机 Nonce
	ProxyUrlNonce []byte
	// 代理 URL 密文的根密钥版本
	ProxyUrlKeyVersion *int32
	// 代理 Header 名称列表，不含 Header Value
	ProxyHeaderNames []byte
	// 代理 Header Key/Value 对象的 AES-256-GCM 密文
	ProxyHeadersCiphertext []byte
	// 代理 Header 密文的 AES-GCM 随机 Nonce
	ProxyHeadersNonce []byte
	// 代理 Header 密文的根密钥版本
	ProxyHeadersKeyVersion *int32
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// Provider 认证资源；可使用 API Key 或订阅认证参与上游调用
type ProviderCredential struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 资源所属供应方 ID，不归属于 Provider Model
	ProviderID int64
	// 资源名称
	ResourceName string
	// AES-256-GCM 认证材料密文，包含 16-byte 认证标签；内容格式由 auth_adapter 解释，禁止明文
	CredentialCiphertext []byte
	// 认证材料 AES-GCM 随机 Nonce，12 bytes；每次加密重新生成
	CredentialNonce []byte
	// 系统检测的运行状态：HEALTHY=可参与路由；BLOCKED=长期故障，等待管理员恢复
	RuntimeStatus string
	// 长期阻断原因；NULL=未阻断
	BlockedReason *string
	// 系统检测到长期阻断的时间；NULL=未阻断
	BlockedAt pgtype.Timestamptz
	// 最近一次导致长期阻断的上游错误时间
	LastErrorAt pgtype.Timestamptz
	// 最近一次导致长期阻断的上游 HTTP 状态；网络或本地错误为 NULL
	LastHttpStatus *int32
	// 最近一次导致长期阻断的规范化错误编码，不保存上游响应正文
	LastErrorCode *string
	// 认证资源类型：API_KEY=按量 API；SUBSCRIPTION=订阅
	AuthType string
	// 认证与调用适配器编码；由应用注册表解释，不绑定具体 Provider 枚举
	AuthAdapter string
	// 订阅形态：PERSONAL=个人订阅；SEAT=席位订阅；API Key 为 NULL
	SubscriptionType *string
	// 服务商套餐编码；仅订阅使用，具体值由对应适配器解释
	PlanCode *string
	// 服务商侧账号或订阅引用；不得保存密码、Token 等秘密
	ExternalAccountRef *string
	// 同类型认证资源的路由优先级；数值越小优先级越高
	Priority int32
	// 认证资源生效时间；NULL=立即生效
	EffectiveAt pgtype.Timestamptz
	// 认证资源到期时间；NULL=未知或不限制
	ExpiresAt pgtype.Timestamptz
	// 最近观测的额度状态；适用于订阅，也预留给存在额度限制的按量 API
	QuotaStatus string
	// 最近一次额度检查时间；NULL=尚未检查
	QuotaCheckedAt pgtype.Timestamptz
	// 额度预计重置时间；NULL=上游未提供或不适用
	QuotaResetsAt pgtype.Timestamptz
	// 订阅认证文件的最近刷新时间；OpenAI Codex 取自 auth.json.last_refresh，缺失时取 access token iat
	CredentialRefreshedAt pgtype.Timestamptz
	// 订阅短期访问凭据到期时间；OpenAI Codex 取自 access token exp，用于 SQL 筛选待刷新凭据
	CredentialExpiresAt pgtype.Timestamptz
	// 认证材料密文格式版本，不含 Master Key 本身
	KeyVersion int32
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
	// 乐观锁版本；每次资源状态、凭据或配置更新后递增
	Version int64
}

// Provider 认证资源最近观测到的额度窗口；只保存当前状态，不作为 Usage 事实
type ProviderCredentialQuotum struct {
	// 所属 Provider 认证资源 ID
	ProviderCredentialID int64
	// 适配器提供的稳定额度窗口编码
	QuotaCode string
	// 服务商返回的额度窗口显示名称
	QuotaName *string
	// 额度窗口状态：AVAILABLE、NEAR_LIMIT、EXHAUSTED 或 UNKNOWN
	QuotaStatus string
	// 额度单位，如 TOKEN、REQUEST、CREDIT、COST 或 CONCURRENCY；允许适配器扩展
	QuotaUnit *string
	// 额度上限；NULL=上游未提供绝对值
	LimitValue pgtype.Numeric
	// 已使用额度；NULL=上游未提供绝对值
	UsedValue pgtype.Numeric
	// 剩余额度；NULL=上游未提供绝对值
	RemainingValue pgtype.Numeric
	// 已使用百分比，范围 0～100；NULL=上游未提供
	UsedPercent pgtype.Numeric
	// 额度窗口长度，单位秒；NULL=上游未提供或非周期额度
	WindowDurationSeconds *int64
	// 额度窗口预计重置时间；NULL=上游未提供或不重置
	ResetsAt pgtype.Timestamptz
	// 服务商返回或适配器归一化的额度耗尽类型
	ReachedType *string
	// 本额度状态从服务商观测到的时间
	ObservedAt pgtype.Timestamptz
	// 额度窗口首次写入时间，UTC
	CreatedAt pgtype.Timestamptz
	// 额度窗口最近更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 服务商支持的协议及对应上游基础地址
type ProviderEndpoint struct {
	// 所属服务商 ID
	ProviderID int64
	// 上游协议族：OPENAI=Chat Completions/Responses；ANTHROPIC=Messages
	ProtocolType string
	// 该协议对应的上游基础地址
	BaseUrl string
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
	// 上游网络范围：PUBLIC=仅公网地址；PRIVATE=管理员显式允许私网地址
	NetworkScope string
}

// 供应方与逻辑模型的多对多映射
type ProviderModel struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 逻辑删除标识；删除后不可恢复
	IsDeleted bool
	// 供应方 ID
	ProviderID int64
	// 逻辑模型 ID
	ModelID int64
	// 服务商模型编码覆盖；空字符串表示调用时使用系统模型编码
	UpstreamModelCode string
	// 路由优先级，数值越小越优先
	Priority int32
	// 创建者引用：system、admin:<id> 或 principal:<id>
	CreatedBy string
	// 更新者引用：system、admin:<id> 或 principal:<id>
	UpdatedBy string
	// 创建时间，UTC
	CreatedAt pgtype.Timestamptz
	// 更新时间，UTC
	UpdatedAt pgtype.Timestamptz
}

// 一次真实上游调用 Attempt 的原始用量事实；不保存价格与成本，无逻辑删除
type UsageRecord struct {
	// 主键，由应用侧生成的正数 64-bit ID
	ID int64
	// 调用最终状态：SUCCESS=成功；FAILED=失败；CANCELLED=客户端取消
	Status string
	// 所属请求标识
	RequestID string
	// 同一客户端请求的上游调用序号，从 1 开始；Failover 时逐次递增
	AttemptNo int64
	// 治理主体 ID
	PrincipalID int64
	// 实际供应方 ID
	ProviderID int64
	// 实际供应方模型映射 ID
	ProviderModelID int64
	// 实际调用的供应方凭证 ID
	ProviderCredentialID int64
	// 逻辑模型 ID
	ModelID int64
	// 使用场景：MODEL_GATEWAY=模型网关调用
	UsageScene string
	// 客户端协议：OPENAI_CHAT=Chat Completions；OPENAI_RESPONSES=Responses；OPENAI_IMAGES=Images；ANTHROPIC_MESSAGES=Messages
	ClientProtocol string
	// 输入 Token 数；NULL=上游未返回可靠值，0=已确认零用量
	InputTokens *int64
	// 输出 Token 数；NULL=上游未返回可靠值，0=已确认零用量
	OutputTokens *int64
	// 缓存读取 Token 数；NULL=上游未返回可靠值，0=已确认零用量
	CachedInputTokens *int64
	// 真实上游调用开始时间，UTC
	StartedAt pgtype.Timestamptz
	// 上游调用结束时间，UTC
	CompletedAt pgtype.Timestamptz
	// 上游耗时，毫秒
	LatencyMs int64
	// 稳定大写错误码；NULL=无错误
	ErrorType *string
	// 事实记录创建时间，UTC
	CreatedAt pgtype.Timestamptz
}
