// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const manageDeleteModelPrice = `-- name: ManageDeleteModelPrice :execrows
DELETE FROM provider_credential_model_price
WHERE id = $1
  AND provider_credential_id = $2
  AND provider_model_id = $3
`

type ManageDeleteModelPriceParams struct {
	ID                   int64
	ProviderCredentialID int64
	ProviderModelID      int64
}

func (q *Queries) ManageDeleteModelPrice(ctx context.Context, arg ManageDeleteModelPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, manageDeleteModelPrice, arg.ID, arg.ProviderCredentialID, arg.ProviderModelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const manageDeleteSubscriptionPrice = `-- name: ManageDeleteSubscriptionPrice :execrows
DELETE FROM provider_credential_subscription_price
WHERE id = $1 AND provider_credential_id = $2
`

type ManageDeleteSubscriptionPriceParams struct {
	ID                   int64
	ProviderCredentialID int64
}

func (q *Queries) ManageDeleteSubscriptionPrice(ctx context.Context, arg ManageDeleteSubscriptionPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, manageDeleteSubscriptionPrice, arg.ID, arg.ProviderCredentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const manageInsertModelPrice = `-- name: ManageInsertModelPrice :exec
INSERT INTO provider_credential_model_price (
    id, provider_credential_id, provider_model_id, currency,
    input_price, output_price, cached_input_price, effective_at,
    created_by, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10
)
`

type ManageInsertModelPriceParams struct {
	ID                   int64
	ProviderCredentialID int64
	ProviderModelID      int64
	Currency             string
	InputPrice           pgtype.Numeric
	OutputPrice          pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	EffectiveAt          pgtype.Timestamptz
	CreatedBy            string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ManageInsertModelPrice(ctx context.Context, arg ManageInsertModelPriceParams) error {
	_, err := q.db.Exec(ctx, manageInsertModelPrice,
		arg.ID,
		arg.ProviderCredentialID,
		arg.ProviderModelID,
		arg.Currency,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
		arg.EffectiveAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageInsertSubscriptionPrice = `-- name: ManageInsertSubscriptionPrice :exec
INSERT INTO provider_credential_subscription_price (
    id, provider_credential_id, currency, period_amount, billing_period,
    effective_at, created_by, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
`

type ManageInsertSubscriptionPriceParams struct {
	ID                   int64
	ProviderCredentialID int64
	Currency             string
	PeriodAmount         pgtype.Numeric
	BillingPeriod        string
	EffectiveAt          pgtype.Timestamptz
	CreatedBy            string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ManageInsertSubscriptionPrice(ctx context.Context, arg ManageInsertSubscriptionPriceParams) error {
	_, err := q.db.Exec(ctx, manageInsertSubscriptionPrice,
		arg.ID,
		arg.ProviderCredentialID,
		arg.Currency,
		arg.PeriodAmount,
		arg.BillingPeriod,
		arg.EffectiveAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const manageModelPrices = `-- name: ManageModelPrices :many
SELECT id, provider_credential_id, provider_model_id, currency,
    input_price, output_price, cached_input_price, effective_at, created_at
FROM provider_credential_model_price
WHERE provider_credential_id = $1
ORDER BY provider_model_id, effective_at DESC, id DESC
`

type ManageModelPricesRow struct {
	ID                   int64
	ProviderCredentialID int64
	ProviderModelID      int64
	Currency             string
	InputPrice           pgtype.Numeric
	OutputPrice          pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	EffectiveAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ManageModelPrices(ctx context.Context, providerCredentialID int64) ([]ManageModelPricesRow, error) {
	rows, err := q.db.Query(ctx, manageModelPrices, providerCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageModelPricesRow{}
	for rows.Next() {
		var i ManageModelPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCredentialID,
			&i.ProviderModelID,
			&i.Currency,
			&i.InputPrice,
			&i.OutputPrice,
			&i.CachedInputPrice,
			&i.EffectiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageSubscriptionPrices = `-- name: ManageSubscriptionPrices :many
SELECT id, provider_credential_id, currency, period_amount,
       billing_period, effective_at, created_at
FROM provider_credential_subscription_price
WHERE provider_credential_id = $1
ORDER BY effective_at DESC, id DESC
`

type ManageSubscriptionPricesRow struct {
	ID                   int64
	ProviderCredentialID int64
	Currency             string
	PeriodAmount         pgtype.Numeric
	BillingPeriod        string
	EffectiveAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ManageSubscriptionPrices(ctx context.Context, providerCredentialID int64) ([]ManageSubscriptionPricesRow, error) {
	rows, err := q.db.Query(ctx, manageSubscriptionPrices, providerCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManageSubscriptionPricesRow{}
	for rows.Next() {
		var i ManageSubscriptionPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCredentialID,
			&i.Currency,
			&i.PeriodAmount,
			&i.BillingPeriod,
			&i.EffectiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manageUpdateModelPrice = `-- name: ManageUpdateModelPrice :execrows
UPDATE provider_credential_model_price
SET currency = $1,
    input_price = $2,
    output_price = $3,
    cached_input_price = $4,
    effective_at = $5
WHERE id = $6
  AND provider_credential_id = $7
  AND provider_model_id = $8
`

type ManageUpdateModelPriceParams struct {
	Currency             string
	InputPrice           pgtype.Numeric
	OutputPrice          pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	EffectiveAt          pgtype.Timestamptz
	ID                   int64
	ProviderCredentialID int64
	ProviderModelID      int64
}

func (q *Queries) ManageUpdateModelPrice(ctx context.Context, arg ManageUpdateModelPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, manageUpdateModelPrice,
		arg.Currency,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
		arg.EffectiveAt,
		arg.ID,
		arg.ProviderCredentialID,
		arg.ProviderModelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const manageUpdateSubscriptionPrice = `-- name: ManageUpdateSubscriptionPrice :execrows
UPDATE provider_credential_subscription_price
SET currency = $1, period_amount = $2,
    billing_period = $3, effective_at = $4
WHERE id = $5 AND provider_credential_id = $6
`

type ManageUpdateSubscriptionPriceParams struct {
	Currency             string
	PeriodAmount         pgtype.Numeric
	BillingPeriod        string
	EffectiveAt          pgtype.Timestamptz
	ID                   int64
	ProviderCredentialID int64
}

func (q *Queries) ManageUpdateSubscriptionPrice(ctx context.Context, arg ManageUpdateSubscriptionPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, manageUpdateSubscriptionPrice,
		arg.Currency,
		arg.PeriodAmount,
		arg.BillingPeriod,
		arg.EffectiveAt,
		arg.ID,
		arg.ProviderCredentialID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
