// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const quotaConfiguredGroups = `-- name: QuotaConfiguredGroups :many
SELECT id, monthly_token_limit
FROM principal_group
WHERE id=ANY($1::bigint[])
  AND NOT is_deleted
  AND monthly_token_limit IS NOT NULL
ORDER BY id
`

type QuotaConfiguredGroupsRow struct {
	ID                int64
	MonthlyTokenLimit *int64
}

func (q *Queries) QuotaConfiguredGroups(ctx context.Context, scopeIds []int64) ([]QuotaConfiguredGroupsRow, error) {
	rows, err := q.db.Query(ctx, quotaConfiguredGroups, scopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotaConfiguredGroupsRow{}
	for rows.Next() {
		var i QuotaConfiguredGroupsRow
		if err := rows.Scan(&i.ID, &i.MonthlyTokenLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quotaConfiguredPrincipals = `-- name: QuotaConfiguredPrincipals :many
SELECT id, monthly_token_limit
FROM principal
WHERE id=ANY($1::bigint[])
  AND NOT is_deleted
  AND monthly_token_limit IS NOT NULL
ORDER BY id
`

type QuotaConfiguredPrincipalsRow struct {
	ID                int64
	MonthlyTokenLimit *int64
}

func (q *Queries) QuotaConfiguredPrincipals(ctx context.Context, scopeIds []int64) ([]QuotaConfiguredPrincipalsRow, error) {
	rows, err := q.db.Query(ctx, quotaConfiguredPrincipals, scopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotaConfiguredPrincipalsRow{}
	for rows.Next() {
		var i QuotaConfiguredPrincipalsRow
		if err := rows.Scan(&i.ID, &i.MonthlyTokenLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quotaGroupUsedTokens = `-- name: QuotaGroupUsedTokens :many
SELECT requested.scope_id::bigint AS scope_id,
       COALESCE(counter.used_tokens, 0)::bigint AS used_tokens
FROM unnest($1::bigint[]) AS requested(scope_id)
LEFT JOIN monthly_token_usage counter
  ON counter.scope_type='GROUP' AND counter.scope_id=requested.scope_id
 AND counter.period_start=$2::timestamptz
ORDER BY requested.scope_id
`

type QuotaGroupUsedTokensParams struct {
	ScopeIds    []int64
	PeriodStart pgtype.Timestamptz
}

type QuotaGroupUsedTokensRow struct {
	ScopeID    int64
	UsedTokens int64
}

func (q *Queries) QuotaGroupUsedTokens(ctx context.Context, arg QuotaGroupUsedTokensParams) ([]QuotaGroupUsedTokensRow, error) {
	rows, err := q.db.Query(ctx, quotaGroupUsedTokens, arg.ScopeIds, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotaGroupUsedTokensRow{}
	for rows.Next() {
		var i QuotaGroupUsedTokensRow
		if err := rows.Scan(&i.ScopeID, &i.UsedTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quotaPrincipalUsedTokens = `-- name: QuotaPrincipalUsedTokens :many
SELECT requested.scope_id::bigint AS scope_id,
       COALESCE(counter.used_tokens, 0)::bigint AS used_tokens
FROM unnest($1::bigint[]) AS requested(scope_id)
LEFT JOIN monthly_token_usage counter
  ON counter.scope_type='PRINCIPAL' AND counter.scope_id=requested.scope_id
 AND counter.period_start=$2::timestamptz
ORDER BY requested.scope_id
`

type QuotaPrincipalUsedTokensParams struct {
	ScopeIds    []int64
	PeriodStart pgtype.Timestamptz
}

type QuotaPrincipalUsedTokensRow struct {
	ScopeID    int64
	UsedTokens int64
}

func (q *Queries) QuotaPrincipalUsedTokens(ctx context.Context, arg QuotaPrincipalUsedTokensParams) ([]QuotaPrincipalUsedTokensRow, error) {
	rows, err := q.db.Query(ctx, quotaPrincipalUsedTokens, arg.ScopeIds, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotaPrincipalUsedTokensRow{}
	for rows.Next() {
		var i QuotaPrincipalUsedTokensRow
		if err := rows.Scan(&i.ScopeID, &i.UsedTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
