// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: security.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendSecurityOperation = `-- name: AppendSecurityOperation :exec
INSERT INTO operation_log (id,operator_type,operator_id,operator_name,module,operation_type,target_type,target_id,target_name,
request_id,request_method,request_path,ip_address,user_agent,result,error_code,before_data,after_data,remark,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)
`

type AppendSecurityOperationParams struct {
	ID            int64
	OperatorType  string
	OperatorID    *int64
	OperatorName  string
	Module        string
	OperationType string
	TargetType    string
	TargetID      *int64
	TargetName    *string
	RequestID     *string
	RequestMethod *string
	RequestPath   *string
	IpAddress     *netip.Addr
	UserAgent     *string
	Result        string
	ErrorCode     *string
	BeforeData    []byte
	AfterData     []byte
	Remark        *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) AppendSecurityOperation(ctx context.Context, arg AppendSecurityOperationParams) error {
	_, err := q.db.Exec(ctx, appendSecurityOperation,
		arg.ID,
		arg.OperatorType,
		arg.OperatorID,
		arg.OperatorName,
		arg.Module,
		arg.OperationType,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.RequestID,
		arg.RequestMethod,
		arg.RequestPath,
		arg.IpAddress,
		arg.UserAgent,
		arg.Result,
		arg.ErrorCode,
		arg.BeforeData,
		arg.AfterData,
		arg.Remark,
		arg.CreatedAt,
	)
	return err
}

const authenticateAccessKey = `-- name: AuthenticateAccessKey :one
SELECT k.id,k.principal_id,k.expires_at FROM principal_access_key k
JOIN principal p ON p.id=k.principal_id
WHERE k.key_hash=$1 AND k.is_deleted=false AND k.status='ACTIVE' AND k.revoked_at IS NULL
AND (k.expires_at IS NULL OR k.expires_at > $2::timestamptz)
AND p.is_deleted=false AND p.status='ACTIVE' AND p.principal_type='MEMBER'
`

type AuthenticateAccessKeyParams struct {
	KeyHash []byte
	Now     pgtype.Timestamptz
}

type AuthenticateAccessKeyRow struct {
	ID          int64
	PrincipalID int64
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) AuthenticateAccessKey(ctx context.Context, arg AuthenticateAccessKeyParams) (AuthenticateAccessKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateAccessKey, arg.KeyHash, arg.Now)
	var i AuthenticateAccessKeyRow
	err := row.Scan(&i.ID, &i.PrincipalID, &i.ExpiresAt)
	return i, err
}

const createAccessKey = `-- name: CreateAccessKey :exec
INSERT INTO principal_access_key (id,principal_id,key_hash,masked_key,name,status,expires_at,created_by,updated_by,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,'ACTIVE',$6,$7,$7,$8,$8)
`

type CreateAccessKeyParams struct {
	ID          int64
	PrincipalID int64
	KeyHash     []byte
	MaskedKey   string
	Name        string
	ExpiresAt   pgtype.Timestamptz
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateAccessKey(ctx context.Context, arg CreateAccessKeyParams) error {
	_, err := q.db.Exec(ctx, createAccessKey,
		arg.ID,
		arg.PrincipalID,
		arg.KeyHash,
		arg.MaskedKey,
		arg.Name,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createInitialAdmin = `-- name: CreateInitialAdmin :exec
INSERT INTO admin_user (id,username,password_hash,display_name,status,created_by,updated_by,created_at,updated_at)
VALUES ($1,$2,$3,$2,'ACTIVE','system','system',$4,$4)
`

type CreateInitialAdminParams struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateInitialAdmin(ctx context.Context, arg CreateInitialAdminParams) error {
	_, err := q.db.Exec(ctx, createInitialAdmin,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const deleteUnrecoverableResource = `-- name: DeleteUnrecoverableResource :exec
UPDATE provider_credential SET is_deleted=true,updated_by='system',updated_at=$2 WHERE id=$1 AND is_deleted=false
`

type DeleteUnrecoverableResourceParams struct {
	ID        int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) DeleteUnrecoverableResource(ctx context.Context, arg DeleteUnrecoverableResourceParams) error {
	_, err := q.db.Exec(ctx, deleteUnrecoverableResource, arg.ID, arg.UpdatedAt)
	return err
}

const getActiveAdmin = `-- name: GetActiveAdmin :one
SELECT id,username,display_name,credential_version FROM admin_user
WHERE id=$1 AND is_deleted=false AND status='ACTIVE'
`

type GetActiveAdminRow struct {
	ID                int64
	Username          string
	DisplayName       string
	CredentialVersion int64
}

func (q *Queries) GetActiveAdmin(ctx context.Context, id int64) (GetActiveAdminRow, error) {
	row := q.db.QueryRow(ctx, getActiveAdmin, id)
	var i GetActiveAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CredentialVersion,
	)
	return i, err
}

const getAdminForLogin = `-- name: GetAdminForLogin :one
SELECT id, is_deleted, status, username, password_hash, display_name, failed_login_count, locked_until, last_login_at, credential_version, created_by, updated_by, created_at, updated_at FROM admin_user
WHERE username=$1 AND is_deleted=false
FOR UPDATE
`

func (q *Queries) GetAdminForLogin(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminForLogin, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CredentialVersion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKeyForRevoke = `-- name: GetKeyForRevoke :one
SELECT id, is_deleted, status, principal_id, key_hash, masked_key, name, expires_at, last_used_at, revoked_at, created_by, updated_by, created_at, updated_at FROM principal_access_key WHERE id=$1 AND is_deleted=false FOR UPDATE
`

func (q *Queries) GetKeyForRevoke(ctx context.Context, id int64) (PrincipalAccessKey, error) {
	row := q.db.QueryRow(ctx, getKeyForRevoke, id)
	var i PrincipalAccessKey
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.PrincipalID,
		&i.KeyHash,
		&i.MaskedKey,
		&i.Name,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberForKey = `-- name: GetMemberForKey :one
SELECT id, is_deleted, status, principal_type, name, remark, created_by, updated_by, created_at, updated_at FROM principal
WHERE id=$1 AND principal_type='MEMBER' AND is_deleted=false FOR UPDATE
`

func (q *Queries) GetMemberForKey(ctx context.Context, id int64) (Principal, error) {
	row := q.db.QueryRow(ctx, getMemberForKey, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.Status,
		&i.PrincipalType,
		&i.Name,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveAdmin = `-- name: HasActiveAdmin :one
SELECT EXISTS (SELECT 1 FROM admin_user WHERE is_deleted=false AND status='ACTIVE')
`

func (q *Queries) HasActiveAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAdmin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasAnyAdmin = `-- name: HasAnyAdmin :one
SELECT EXISTS (SELECT 1 FROM admin_user)
`

func (q *Queries) HasAnyAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyAdmin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listResourcesForCredentialCheck = `-- name: ListResourcesForCredentialCheck :many
SELECT id, is_deleted, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, created_by, updated_by, created_at, updated_at, runtime_status, blocked_reason, blocked_at, last_error_at, last_http_status, last_error_code, auth_type, auth_adapter, subscription_type, plan_code, external_account_ref, priority, effective_at, expires_at, quota_status, quota_checked_at, quota_resets_at, credential_refreshed_at, credential_expires_at FROM provider_credential WHERE is_deleted=false ORDER BY id FOR UPDATE
`

func (q *Queries) ListResourcesForCredentialCheck(ctx context.Context) ([]ProviderCredential, error) {
	rows, err := q.db.Query(ctx, listResourcesForCredentialCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCredential{}
	for rows.Next() {
		var i ProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.ProviderID,
			&i.ResourceName,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.KeyVersion,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuntimeStatus,
			&i.BlockedReason,
			&i.BlockedAt,
			&i.LastErrorAt,
			&i.LastHttpStatus,
			&i.LastErrorCode,
			&i.AuthType,
			&i.AuthAdapter,
			&i.SubscriptionType,
			&i.PlanCode,
			&i.ExternalAccountRef,
			&i.Priority,
			&i.EffectiveAt,
			&i.ExpiresAt,
			&i.QuotaStatus,
			&i.QuotaCheckedAt,
			&i.QuotaResetsAt,
			&i.CredentialRefreshedAt,
			&i.CredentialExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAdminPassword = `-- name: ResetAdminPassword :execrows
UPDATE admin_user SET password_hash=$2,failed_login_count=0,locked_until=NULL,
credential_version=credential_version+1,updated_by=$4,updated_at=$3
WHERE id=$1 AND is_deleted=false AND status='ACTIVE'
`

type ResetAdminPasswordParams struct {
	ID           int64
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    string
}

func (q *Queries) ResetAdminPassword(ctx context.Context, arg ResetAdminPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetAdminPassword,
		arg.ID,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessKey = `-- name: RevokeAccessKey :exec
UPDATE principal_access_key SET status='REVOKED',revoked_at=$2,updated_by=$3,updated_at=$2
WHERE id=$1 AND is_deleted=false
`

type RevokeAccessKeyParams struct {
	ID        int64
	RevokedAt pgtype.Timestamptz
	UpdatedBy string
}

func (q *Queries) RevokeAccessKey(ctx context.Context, arg RevokeAccessKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAccessKey, arg.ID, arg.RevokedAt, arg.UpdatedBy)
	return err
}

const saveAdminLoginState = `-- name: SaveAdminLoginState :exec
UPDATE admin_user SET failed_login_count=$2,locked_until=$3,last_login_at=$4,updated_by=$5,updated_at=$6
WHERE id=$1 AND is_deleted=false
`

type SaveAdminLoginStateParams struct {
	ID               int64
	FailedLoginCount int64
	LockedUntil      pgtype.Timestamptz
	LastLoginAt      pgtype.Timestamptz
	UpdatedBy        string
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) SaveAdminLoginState(ctx context.Context, arg SaveAdminLoginStateParams) error {
	_, err := q.db.Exec(ctx, saveAdminLoginState,
		arg.ID,
		arg.FailedLoginCount,
		arg.LockedUntil,
		arg.LastLoginAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
