// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: security.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendSecurityOperation = `-- name: AppendSecurityOperation :exec
INSERT INTO operation_log (id,organization_id,operator_type,operator_id,operator_name,module,operation_type,target_type,target_id,target_name,
request_id,request_method,request_path,ip_address,user_agent,result,error_code,before_data,after_data,remark,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
`

type AppendSecurityOperationParams struct {
	ID             int64
	OrganizationID int64
	OperatorType   string
	OperatorID     *int64
	OperatorName   string
	Module         string
	OperationType  string
	TargetType     string
	TargetID       *int64
	TargetName     *string
	RequestID      *string
	RequestMethod  *string
	RequestPath    *string
	IpAddress      *netip.Addr
	UserAgent      *string
	Result         string
	ErrorCode      *string
	BeforeData     []byte
	AfterData      []byte
	Remark         *string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) AppendSecurityOperation(ctx context.Context, arg AppendSecurityOperationParams) error {
	_, err := q.db.Exec(ctx, appendSecurityOperation,
		arg.ID,
		arg.OrganizationID,
		arg.OperatorType,
		arg.OperatorID,
		arg.OperatorName,
		arg.Module,
		arg.OperationType,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.RequestID,
		arg.RequestMethod,
		arg.RequestPath,
		arg.IpAddress,
		arg.UserAgent,
		arg.Result,
		arg.ErrorCode,
		arg.BeforeData,
		arg.AfterData,
		arg.Remark,
		arg.CreatedAt,
	)
	return err
}

const authenticateAccessKey = `-- name: AuthenticateAccessKey :one
SELECT k.id,k.organization_id,k.principal_id FROM access_key k
JOIN principal p ON p.id=k.principal_id AND p.organization_id=k.organization_id
JOIN organization o ON o.id=k.organization_id
WHERE k.key_hash=$1 AND k.is_deleted=false AND k.status='ACTIVE' AND k.revoked_at IS NULL
AND (k.expires_at IS NULL OR k.expires_at > $2::timestamptz)
AND p.is_deleted=false AND p.status='ACTIVE' AND p.principal_type='MEMBER'
AND o.is_deleted=false AND o.status='ACTIVE'
`

type AuthenticateAccessKeyParams struct {
	KeyHash []byte
	Now     pgtype.Timestamptz
}

type AuthenticateAccessKeyRow struct {
	ID             int64
	OrganizationID int64
	PrincipalID    int64
}

func (q *Queries) AuthenticateAccessKey(ctx context.Context, arg AuthenticateAccessKeyParams) (AuthenticateAccessKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateAccessKey, arg.KeyHash, arg.Now)
	var i AuthenticateAccessKeyRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.PrincipalID)
	return i, err
}

const createAccessKey = `-- name: CreateAccessKey :exec
INSERT INTO access_key (id,organization_id,principal_id,key_hash,key_prefix,name,status,expires_at,created_by,updated_by,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,'ACTIVE',$7,$8,$8,$9,$9)
`

type CreateAccessKeyParams struct {
	ID             int64
	OrganizationID int64
	PrincipalID    int64
	KeyHash        []byte
	KeyPrefix      string
	Name           string
	ExpiresAt      pgtype.Timestamptz
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateAccessKey(ctx context.Context, arg CreateAccessKeyParams) error {
	_, err := q.db.Exec(ctx, createAccessKey,
		arg.ID,
		arg.OrganizationID,
		arg.PrincipalID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createInitialAdmin = `-- name: CreateInitialAdmin :exec
INSERT INTO admin_user (id,organization_id,username,password_hash,display_name,status,created_by,updated_by,created_at,updated_at)
VALUES ($1,$2,$3,$4,$3,'ACTIVE','system','system',$5,$5)
`

type CreateInitialAdminParams struct {
	ID             int64
	OrganizationID int64
	Username       string
	PasswordHash   string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateInitialAdmin(ctx context.Context, arg CreateInitialAdminParams) error {
	_, err := q.db.Exec(ctx, createInitialAdmin,
		arg.ID,
		arg.OrganizationID,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const disableUnrecoverableResource = `-- name: DisableUnrecoverableResource :exec
UPDATE ai_resource SET status='DISABLED',updated_by='system',updated_at=$2 WHERE id=$1 AND is_deleted=false
`

type DisableUnrecoverableResourceParams struct {
	ID        int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) DisableUnrecoverableResource(ctx context.Context, arg DisableUnrecoverableResourceParams) error {
	_, err := q.db.Exec(ctx, disableUnrecoverableResource, arg.ID, arg.UpdatedAt)
	return err
}

const getActiveAdmin = `-- name: GetActiveAdmin :one
SELECT a.id,a.organization_id,a.username,a.display_name,a.credential_version FROM admin_user a JOIN organization o ON o.id=a.organization_id
WHERE a.organization_id=$1 AND a.id=$2 AND a.is_deleted=false AND a.status='ACTIVE'
AND o.is_deleted=false AND o.status='ACTIVE'
`

type GetActiveAdminParams struct {
	OrganizationID int64
	ID             int64
}

type GetActiveAdminRow struct {
	ID                int64
	OrganizationID    int64
	Username          string
	DisplayName       string
	CredentialVersion int64
}

func (q *Queries) GetActiveAdmin(ctx context.Context, arg GetActiveAdminParams) (GetActiveAdminRow, error) {
	row := q.db.QueryRow(ctx, getActiveAdmin, arg.OrganizationID, arg.ID)
	var i GetActiveAdminRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.DisplayName,
		&i.CredentialVersion,
	)
	return i, err
}

const getActiveOrganization = `-- name: GetActiveOrganization :one
SELECT id, is_deleted, organization_code, organization_name, status, remark, created_by, updated_by, created_at, updated_at FROM organization WHERE is_deleted=false AND status='ACTIVE'
`

func (q *Queries) GetActiveOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getActiveOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationCode,
		&i.OrganizationName,
		&i.Status,
		&i.Remark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminForLogin = `-- name: GetAdminForLogin :one
SELECT a.id, a.is_deleted, a.organization_id, a.username, a.password_hash, a.display_name, a.status, a.failed_login_count, a.locked_until, a.last_login_at, a.created_by, a.updated_by, a.created_at, a.updated_at, a.credential_version, (o.status='ACTIVE') AS organization_active
FROM admin_user a JOIN organization o ON o.id=a.organization_id
WHERE a.username=$1 AND a.is_deleted=false AND o.is_deleted=false
FOR UPDATE OF a
`

type GetAdminForLoginRow struct {
	ID                 int64
	IsDeleted          bool
	OrganizationID     int64
	Username           string
	PasswordHash       string
	DisplayName        string
	Status             string
	FailedLoginCount   int64
	LockedUntil        pgtype.Timestamptz
	LastLoginAt        pgtype.Timestamptz
	CreatedBy          string
	UpdatedBy          string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CredentialVersion  int64
	OrganizationActive bool
}

func (q *Queries) GetAdminForLogin(ctx context.Context, username string) (GetAdminForLoginRow, error) {
	row := q.db.QueryRow(ctx, getAdminForLogin, username)
	var i GetAdminForLoginRow
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.OrganizationActive,
	)
	return i, err
}

const getKeyForRevoke = `-- name: GetKeyForRevoke :one
SELECT id, is_deleted, organization_id, principal_id, key_hash, key_prefix, name, status, expires_at, last_used_at, revoked_at, created_by, updated_by, created_at, updated_at FROM access_key WHERE organization_id=$1 AND id=$2 AND is_deleted=false FOR UPDATE
`

type GetKeyForRevokeParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) GetKeyForRevoke(ctx context.Context, arg GetKeyForRevokeParams) (AccessKey, error) {
	row := q.db.QueryRow(ctx, getKeyForRevoke, arg.OrganizationID, arg.ID)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.PrincipalID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Name,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberForKey = `-- name: GetMemberForKey :one
SELECT p.id, p.is_deleted, p.organization_id, p.principal_type, p.name, p.remark, p.status, p.created_by, p.updated_by, p.created_at, p.updated_at FROM principal p JOIN organization o ON o.id=p.organization_id
WHERE p.organization_id=$1 AND p.id=$2 AND p.principal_type='MEMBER' AND p.is_deleted=false
AND p.status='ACTIVE' AND o.status='ACTIVE' AND o.is_deleted=false FOR UPDATE OF p
`

type GetMemberForKeyParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) GetMemberForKey(ctx context.Context, arg GetMemberForKeyParams) (Principal, error) {
	row := q.db.QueryRow(ctx, getMemberForKey, arg.OrganizationID, arg.ID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.IsDeleted,
		&i.OrganizationID,
		&i.PrincipalType,
		&i.Name,
		&i.Remark,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveAdmin = `-- name: HasActiveAdmin :one
SELECT EXISTS (SELECT 1 FROM admin_user a JOIN organization o ON o.id=a.organization_id
WHERE a.is_deleted=false AND a.status='ACTIVE' AND o.is_deleted=false AND o.status='ACTIVE')
`

func (q *Queries) HasActiveAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAdmin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasAnyAdmin = `-- name: HasAnyAdmin :one
SELECT EXISTS (SELECT 1 FROM admin_user)
`

func (q *Queries) HasAnyAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyAdmin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listResourcesForCredentialCheck = `-- name: ListResourcesForCredentialCheck :many
SELECT id, is_deleted, organization_id, provider_id, resource_name, credential_ciphertext, credential_nonce, key_version, status, last_active_at, created_by, updated_by, created_at, updated_at FROM ai_resource WHERE is_deleted=false AND status='ACTIVE' ORDER BY id FOR UPDATE
`

func (q *Queries) ListResourcesForCredentialCheck(ctx context.Context) ([]AiResource, error) {
	rows, err := q.db.Query(ctx, listResourcesForCredentialCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiResource{}
	for rows.Next() {
		var i AiResource
		if err := rows.Scan(
			&i.ID,
			&i.IsDeleted,
			&i.OrganizationID,
			&i.ProviderID,
			&i.ResourceName,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.KeyVersion,
			&i.Status,
			&i.LastActiveAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAdminPassword = `-- name: ResetAdminPassword :execrows
UPDATE admin_user SET password_hash=$3,failed_login_count=0,locked_until=NULL,
credential_version=credential_version+1,updated_by=$5,updated_at=$4
WHERE organization_id=$1 AND id=$2 AND is_deleted=false AND status='ACTIVE'
`

type ResetAdminPasswordParams struct {
	OrganizationID int64
	ID             int64
	PasswordHash   string
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      string
}

func (q *Queries) ResetAdminPassword(ctx context.Context, arg ResetAdminPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetAdminPassword,
		arg.OrganizationID,
		arg.ID,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessKey = `-- name: RevokeAccessKey :exec
UPDATE access_key SET status='REVOKED',revoked_at=$3,updated_by=$4,updated_at=$3
WHERE organization_id=$1 AND id=$2 AND is_deleted=false
`

type RevokeAccessKeyParams struct {
	OrganizationID int64
	ID             int64
	RevokedAt      pgtype.Timestamptz
	UpdatedBy      string
}

func (q *Queries) RevokeAccessKey(ctx context.Context, arg RevokeAccessKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAccessKey,
		arg.OrganizationID,
		arg.ID,
		arg.RevokedAt,
		arg.UpdatedBy,
	)
	return err
}

const saveAdminLoginState = `-- name: SaveAdminLoginState :exec
UPDATE admin_user SET failed_login_count=$3,locked_until=$4,last_login_at=$5,updated_by=$6,updated_at=$7
WHERE organization_id=$1 AND id=$2 AND is_deleted=false
`

type SaveAdminLoginStateParams struct {
	OrganizationID   int64
	ID               int64
	FailedLoginCount int64
	LockedUntil      pgtype.Timestamptz
	LastLoginAt      pgtype.Timestamptz
	UpdatedBy        string
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) SaveAdminLoginState(ctx context.Context, arg SaveAdminLoginStateParams) error {
	_, err := q.db.Exec(ctx, saveAdminLoginState,
		arg.OrganizationID,
		arg.ID,
		arg.FailedLoginCount,
		arg.LockedUntil,
		arg.LastLoginAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
