// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsageAttempts = `-- name: InsertUsageAttempts :exec
INSERT INTO usage_record(id,organization_id,request_id,attempt_no,principal_id,provider_id,provider_model_id,resource_id,model_id,usage_scene,input_tokens,output_tokens,cached_input_tokens,billing_unit,started_at,completed_at,latency_ms,status,error_type,created_at)
SELECT id,organization_id,request_id,1,principal_id,provider_id,provider_model_id,resource_id,model_id,'MODEL_GATEWAY',input_tokens,output_tokens,cached_input_tokens,'TOKEN',started_at,completed_at,latency_ms,status,error_type,completed_at
FROM jsonb_to_recordset($1::jsonb) AS x(id bigint,organization_id bigint,request_id text,principal_id bigint,provider_id bigint,provider_model_id bigint,resource_id bigint,model_id bigint,input_tokens bigint,output_tokens bigint,cached_input_tokens bigint,started_at timestamptz,completed_at timestamptz,latency_ms bigint,status text,error_type text)
ON CONFLICT(request_id,attempt_no) DO NOTHING
`

func (q *Queries) InsertUsageAttempts(ctx context.Context, payload []byte) error {
	_, err := q.db.Exec(ctx, insertUsageAttempts, payload)
	return err
}

const insertUsageRequests = `-- name: InsertUsageRequests :exec
INSERT INTO ai_request(id,organization_id,request_id,principal_id,model_id,usage_scene,client_protocol,request_at,completed_at,latency_ms,status,error_type,created_at)
SELECT id,organization_id,request_id,principal_id,model_id,'MODEL_GATEWAY',client_protocol,request_at,completed_at,latency_ms,status,error_type,completed_at
FROM jsonb_to_recordset($1::jsonb) AS x(id bigint,organization_id bigint,request_id text,principal_id bigint,model_id bigint,client_protocol text,request_at timestamptz,completed_at timestamptz,latency_ms bigint,status text,error_type text)
ON CONFLICT(request_id) DO NOTHING
`

func (q *Queries) InsertUsageRequests(ctx context.Context, payload []byte) error {
	_, err := q.db.Exec(ctx, insertUsageRequests, payload)
	return err
}

const queryUsage = `-- name: QueryUsage :many
SELECT r.id,r.request_id,r.client_protocol,r.principal_id,r.model_id,r.request_at,r.completed_at,r.latency_ms,r.status,r.error_type,
u.id AS usage_id,u.attempt_no,u.provider_id,u.provider_model_id,u.resource_id,u.input_tokens,u.output_tokens,u.cached_input_tokens,u.status AS attempt_status,u.error_type AS attempt_error_type
FROM ai_request r LEFT JOIN usage_record u ON u.request_id=r.request_id AND u.organization_id=r.organization_id
WHERE r.organization_id=$1
AND r.id>$2::bigint
AND r.request_at>=$3::timestamptz AND r.request_at<$4::timestamptz
AND ($5::bigint IS NULL OR r.principal_id=$5)
AND ($6::bigint IS NULL OR r.model_id=$6)
AND ($7::bigint IS NULL OR u.resource_id=$7)
ORDER BY r.id LIMIT $8::int
`

type QueryUsageParams struct {
	OrganizationID int64
	AfterID        int64
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PrincipalID    *int64
	ModelID        *int64
	ResourceID     *int64
	PageLimit      int32
}

type QueryUsageRow struct {
	ID                int64
	RequestID         string
	ClientProtocol    string
	PrincipalID       int64
	ModelID           *int64
	RequestAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	LatencyMs         int64
	Status            string
	ErrorType         *string
	UsageID           *int64
	AttemptNo         *int64
	ProviderID        *int64
	ProviderModelID   *int64
	ResourceID        *int64
	InputTokens       *int64
	OutputTokens      *int64
	CachedInputTokens *int64
	AttemptStatus     *string
	AttemptErrorType  *string
}

func (q *Queries) QueryUsage(ctx context.Context, arg QueryUsageParams) ([]QueryUsageRow, error) {
	rows, err := q.db.Query(ctx, queryUsage,
		arg.OrganizationID,
		arg.AfterID,
		arg.FromTime,
		arg.ToTime,
		arg.PrincipalID,
		arg.ModelID,
		arg.ResourceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryUsageRow{}
	for rows.Next() {
		var i QueryUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ClientProtocol,
			&i.PrincipalID,
			&i.ModelID,
			&i.RequestAt,
			&i.CompletedAt,
			&i.LatencyMs,
			&i.Status,
			&i.ErrorType,
			&i.UsageID,
			&i.AttemptNo,
			&i.ProviderID,
			&i.ProviderModelID,
			&i.ResourceID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.AttemptStatus,
			&i.AttemptErrorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
