// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsage = `-- name: CountUsage :one
SELECT COUNT(*)::bigint
FROM usage_record u
WHERE u.started_at>=$1::timestamptz AND u.started_at<$2::timestamptz
AND ($3::bigint IS NULL OR u.principal_id=$3)
AND ($4::bigint IS NULL OR u.model_id=$4)
AND ($5::bigint IS NULL OR u.provider_id=$5)
AND ($6::bigint IS NULL OR u.provider_credential_id=$6)
`

type CountUsageParams struct {
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	PrincipalID *int64
	ModelID     *int64
	ProviderID  *int64
	ResourceID  *int64
}

func (q *Queries) CountUsage(ctx context.Context, arg CountUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsage,
		arg.FromTime,
		arg.ToTime,
		arg.PrincipalID,
		arg.ModelID,
		arg.ProviderID,
		arg.ResourceID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertUsageAttempts = `-- name: InsertUsageAttempts :exec
INSERT INTO usage_record(id,request_id,attempt_no,principal_id,provider_id,provider_model_id,provider_credential_id,model_id,usage_scene,client_protocol,input_tokens,output_tokens,cached_input_tokens,billing_unit,started_at,completed_at,latency_ms,status,error_type,created_at)
SELECT nextval('zentrola_global_id_seq'),request_id,attempt_no,principal_id,provider_id,provider_model_id,provider_credential_id,model_id,'MODEL_GATEWAY',client_protocol,input_tokens,output_tokens,cached_input_tokens,'TOKEN',started_at,completed_at,latency_ms,status,error_type,completed_at
FROM jsonb_to_recordset($1::jsonb) AS x(request_id text,attempt_no integer,client_protocol text,principal_id bigint,provider_id bigint,provider_model_id bigint,provider_credential_id bigint,model_id bigint,input_tokens bigint,output_tokens bigint,cached_input_tokens bigint,started_at timestamptz,completed_at timestamptz,latency_ms bigint,status text,error_type text)
ON CONFLICT(request_id,attempt_no) DO NOTHING
`

func (q *Queries) InsertUsageAttempts(ctx context.Context, payload []byte) error {
	_, err := q.db.Exec(ctx, insertUsageAttempts, payload)
	return err
}

const queryUsage = `-- name: QueryUsage :many
SELECT u.id,u.request_id,u.client_protocol,u.principal_id,p.name AS principal_name,u.model_id,u.started_at,u.completed_at,u.latency_ms,u.status,u.error_type,
attempt_no,provider_id,provider_model_id,provider_credential_id AS resource_id,input_tokens,output_tokens,cached_input_tokens
FROM usage_record u
JOIN principal p ON p.id=u.principal_id
WHERE (u.id<$1::bigint OR $1::bigint=0)
AND u.started_at>=$2::timestamptz AND u.started_at<$3::timestamptz
AND ($4::bigint IS NULL OR u.principal_id=$4)
AND ($5::bigint IS NULL OR u.model_id=$5)
AND ($6::bigint IS NULL OR u.provider_id=$6)
AND ($7::bigint IS NULL OR u.provider_credential_id=$7)
ORDER BY u.id DESC LIMIT $8::int
`

type QueryUsageParams struct {
	AfterID     int64
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	PrincipalID *int64
	ModelID     *int64
	ProviderID  *int64
	ResourceID  *int64
	PageLimit   int32
}

type QueryUsageRow struct {
	ID                int64
	RequestID         string
	ClientProtocol    string
	PrincipalID       int64
	PrincipalName     string
	ModelID           int64
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	LatencyMs         int64
	Status            string
	ErrorType         *string
	AttemptNo         int64
	ProviderID        int64
	ProviderModelID   int64
	ResourceID        int64
	InputTokens       *int64
	OutputTokens      *int64
	CachedInputTokens *int64
}

func (q *Queries) QueryUsage(ctx context.Context, arg QueryUsageParams) ([]QueryUsageRow, error) {
	rows, err := q.db.Query(ctx, queryUsage,
		arg.AfterID,
		arg.FromTime,
		arg.ToTime,
		arg.PrincipalID,
		arg.ModelID,
		arg.ProviderID,
		arg.ResourceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryUsageRow{}
	for rows.Next() {
		var i QueryUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ClientProtocol,
			&i.PrincipalID,
			&i.PrincipalName,
			&i.ModelID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LatencyMs,
			&i.Status,
			&i.ErrorType,
			&i.AttemptNo,
			&i.ProviderID,
			&i.ProviderModelID,
			&i.ResourceID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageClientModelRanking = `-- name: UsageClientModelRanking :many
SELECT m.id AS model_id,
       m.model_code,
       m.display_name AS model_name,
       COUNT(DISTINCT u.request_id)::bigint AS requests,
       COALESCE(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)), 0)::bigint AS tokens
FROM usage_record u
JOIN model m ON m.id=u.model_id
WHERE u.started_at>=$1::timestamptz
  AND u.started_at<$2::timestamptz
GROUP BY m.id, m.model_code, m.display_name
ORDER BY requests DESC, tokens DESC, m.id DESC
LIMIT 10
`

type UsageClientModelRankingParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type UsageClientModelRankingRow struct {
	ModelID   int64
	ModelCode string
	ModelName string
	Requests  int64
	Tokens    int64
}

func (q *Queries) UsageClientModelRanking(ctx context.Context, arg UsageClientModelRankingParams) ([]UsageClientModelRankingRow, error) {
	rows, err := q.db.Query(ctx, usageClientModelRanking, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageClientModelRankingRow{}
	for rows.Next() {
		var i UsageClientModelRankingRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ModelCode,
			&i.ModelName,
			&i.Requests,
			&i.Tokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageDashboardCounts = `-- name: UsageDashboardCounts :one
SELECT
    (SELECT COUNT(*)::bigint FROM principal p
     WHERE p.principal_type='MEMBER' AND p.is_deleted=false AND p.status='ACTIVE') AS active_member_count,
    (SELECT COUNT(*)::bigint FROM model WHERE is_deleted=false AND status='ACTIVE') AS model_count,
    (SELECT COUNT(*)::bigint FROM provider WHERE is_deleted=false AND status='ACTIVE') AS provider_count,
    COALESCE((
        SELECT SUM(COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0))::bigint
        FROM usage_record u
        WHERE u.started_at>=$1::timestamptz
          AND u.started_at<$2::timestamptz
    ), 0)::bigint AS total_tokens
`

type UsageDashboardCountsParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type UsageDashboardCountsRow struct {
	ActiveMemberCount int64
	ModelCount        int64
	ProviderCount     int64
	TotalTokens       int64
}

func (q *Queries) UsageDashboardCounts(ctx context.Context, arg UsageDashboardCountsParams) (UsageDashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, usageDashboardCounts, arg.FromTime, arg.ToTime)
	var i UsageDashboardCountsRow
	err := row.Scan(
		&i.ActiveMemberCount,
		&i.ModelCount,
		&i.ProviderCount,
		&i.TotalTokens,
	)
	return i, err
}

const usageMemberStatistics = `-- name: UsageMemberStatistics :many
SELECT u.principal_id AS entity_id,
       p.name,
       ''::text AS code,
       COUNT(DISTINCT u.request_id)::bigint AS metric_count,
       COUNT(DISTINCT u.request_id) FILTER (WHERE u.status='SUCCESS') AS successful,
       COALESCE(SUM(u.input_tokens), 0)::bigint AS input_tokens,
       COALESCE(SUM(u.output_tokens), 0)::bigint AS output_tokens,
       COALESCE(SUM(u.cached_input_tokens), 0)::bigint AS cached_input_tokens,
       COALESCE(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)), 0)::bigint AS tokens,
       SUM(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0))) OVER ()::bigint AS overall_tokens,
       COALESCE(ROUND(AVG(u.latency_ms)), 0)::bigint AS average_latency_ms,
       COUNT(*) OVER ()::bigint AS total_count
FROM usage_record u
JOIN principal p ON p.id=u.principal_id
WHERE u.started_at>=$1::timestamptz
  AND u.started_at<$2::timestamptz
GROUP BY u.principal_id, p.name
ORDER BY tokens DESC, metric_count DESC, u.principal_id DESC
LIMIT $4::int OFFSET $3::bigint
`

type UsageMemberStatisticsParams struct {
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int64
	PageLimit  int32
}

type UsageMemberStatisticsRow struct {
	EntityID          int64
	Name              string
	Code              string
	MetricCount       int64
	Successful        int64
	InputTokens       int64
	OutputTokens      int64
	CachedInputTokens int64
	Tokens            int64
	OverallTokens     int64
	AverageLatencyMs  int64
	TotalCount        int64
}

func (q *Queries) UsageMemberStatistics(ctx context.Context, arg UsageMemberStatisticsParams) ([]UsageMemberStatisticsRow, error) {
	rows, err := q.db.Query(ctx, usageMemberStatistics,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageMemberStatisticsRow{}
	for rows.Next() {
		var i UsageMemberStatisticsRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Code,
			&i.MetricCount,
			&i.Successful,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.Tokens,
			&i.OverallTokens,
			&i.AverageLatencyMs,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageModelStatistics = `-- name: UsageModelStatistics :many
SELECT m.id AS entity_id,
       m.display_name AS name,
       m.model_code AS code,
       COUNT(DISTINCT u.request_id)::bigint AS metric_count,
       COUNT(DISTINCT u.request_id) FILTER (WHERE u.status='SUCCESS') AS successful,
       COALESCE(SUM(u.input_tokens), 0)::bigint AS input_tokens,
       COALESCE(SUM(u.output_tokens), 0)::bigint AS output_tokens,
       COALESCE(SUM(u.cached_input_tokens), 0)::bigint AS cached_input_tokens,
       COALESCE(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)), 0)::bigint AS tokens,
       SUM(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0))) OVER ()::bigint AS overall_tokens,
       COALESCE(ROUND(AVG(u.latency_ms)), 0)::bigint AS average_latency_ms,
       COUNT(*) OVER ()::bigint AS total_count
FROM usage_record u
JOIN model m ON m.id=u.model_id
WHERE u.started_at>=$1::timestamptz
  AND u.started_at<$2::timestamptz
GROUP BY m.id, m.display_name, m.model_code
ORDER BY metric_count DESC, tokens DESC, m.id DESC
LIMIT $4::int OFFSET $3::bigint
`

type UsageModelStatisticsParams struct {
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int64
	PageLimit  int32
}

type UsageModelStatisticsRow struct {
	EntityID          int64
	Name              string
	Code              string
	MetricCount       int64
	Successful        int64
	InputTokens       int64
	OutputTokens      int64
	CachedInputTokens int64
	Tokens            int64
	OverallTokens     int64
	AverageLatencyMs  int64
	TotalCount        int64
}

func (q *Queries) UsageModelStatistics(ctx context.Context, arg UsageModelStatisticsParams) ([]UsageModelStatisticsRow, error) {
	rows, err := q.db.Query(ctx, usageModelStatistics,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageModelStatisticsRow{}
	for rows.Next() {
		var i UsageModelStatisticsRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Code,
			&i.MetricCount,
			&i.Successful,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.Tokens,
			&i.OverallTokens,
			&i.AverageLatencyMs,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageProviderRanking = `-- name: UsageProviderRanking :many
SELECT p.id AS provider_id,
       p.provider_name,
       COUNT(*)::bigint AS calls,
       COALESCE(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)), 0)::bigint AS tokens
FROM usage_record u
JOIN provider p ON p.id=u.provider_id
WHERE u.started_at>=$1::timestamptz
  AND u.started_at<$2::timestamptz
GROUP BY p.id, p.provider_name
ORDER BY calls DESC, tokens DESC, p.id DESC
LIMIT 10
`

type UsageProviderRankingParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type UsageProviderRankingRow struct {
	ProviderID   int64
	ProviderName string
	Calls        int64
	Tokens       int64
}

func (q *Queries) UsageProviderRanking(ctx context.Context, arg UsageProviderRankingParams) ([]UsageProviderRankingRow, error) {
	rows, err := q.db.Query(ctx, usageProviderRanking, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageProviderRankingRow{}
	for rows.Next() {
		var i UsageProviderRankingRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.Calls,
			&i.Tokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageProviderStatistics = `-- name: UsageProviderStatistics :many
SELECT p.id AS entity_id,
       p.provider_name AS name,
       p.provider_code AS code,
       COUNT(*)::bigint AS metric_count,
       COUNT(*) FILTER (WHERE u.status='SUCCESS') AS successful,
       COALESCE(SUM(u.input_tokens), 0)::bigint AS input_tokens,
       COALESCE(SUM(u.output_tokens), 0)::bigint AS output_tokens,
       COALESCE(SUM(u.cached_input_tokens), 0)::bigint AS cached_input_tokens,
       COALESCE(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)), 0)::bigint AS tokens,
       SUM(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0))) OVER ()::bigint AS overall_tokens,
       COALESCE(ROUND(AVG(u.latency_ms)), 0)::bigint AS average_latency_ms,
       COUNT(*) OVER ()::bigint AS total_count
FROM usage_record u
JOIN provider p ON p.id=u.provider_id
WHERE u.started_at>=$1::timestamptz
  AND u.started_at<$2::timestamptz
GROUP BY p.id, p.provider_name, p.provider_code
ORDER BY metric_count DESC, tokens DESC, p.id DESC
LIMIT $4::int OFFSET $3::bigint
`

type UsageProviderStatisticsParams struct {
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int64
	PageLimit  int32
}

type UsageProviderStatisticsRow struct {
	EntityID          int64
	Name              string
	Code              string
	MetricCount       int64
	Successful        int64
	InputTokens       int64
	OutputTokens      int64
	CachedInputTokens int64
	Tokens            int64
	OverallTokens     int64
	AverageLatencyMs  int64
	TotalCount        int64
}

func (q *Queries) UsageProviderStatistics(ctx context.Context, arg UsageProviderStatisticsParams) ([]UsageProviderStatisticsRow, error) {
	rows, err := q.db.Query(ctx, usageProviderStatistics,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageProviderStatisticsRow{}
	for rows.Next() {
		var i UsageProviderStatisticsRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Code,
			&i.MetricCount,
			&i.Successful,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.Tokens,
			&i.OverallTokens,
			&i.AverageLatencyMs,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageTokenRanking = `-- name: UsageTokenRanking :many
SELECT u.principal_id, p.name,
       SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0))::bigint AS tokens
FROM usage_record u
JOIN principal p ON p.id=u.principal_id
WHERE u.started_at>=$1::timestamptz
  AND u.started_at<$2::timestamptz
GROUP BY u.principal_id, p.name
HAVING SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)) > 0
ORDER BY tokens DESC, u.principal_id DESC
LIMIT 10
`

type UsageTokenRankingParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type UsageTokenRankingRow struct {
	PrincipalID int64
	Name        string
	Tokens      int64
}

func (q *Queries) UsageTokenRanking(ctx context.Context, arg UsageTokenRankingParams) ([]UsageTokenRankingRow, error) {
	rows, err := q.db.Query(ctx, usageTokenRanking, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageTokenRankingRow{}
	for rows.Next() {
		var i UsageTokenRankingRow
		if err := rows.Scan(&i.PrincipalID, &i.Name, &i.Tokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
