-- +goose Up
ALTER TABLE principal
    ADD COLUMN monthly_token_limit BIGINT
    CONSTRAINT principal_monthly_token_limit_check
    CHECK (monthly_token_limit IS NULL OR monthly_token_limit > 0);

ALTER TABLE principal_group
    ADD COLUMN monthly_token_limit BIGINT
    CONSTRAINT principal_group_monthly_token_limit_check
    CHECK (monthly_token_limit IS NULL OR monthly_token_limit > 0);

COMMENT ON COLUMN principal.monthly_token_limit IS '主体每个 UTC 自然月允许使用的 Token 上限；NULL 表示不限制';
COMMENT ON COLUMN principal_group.monthly_token_limit IS '分组内授权模型共享的每个 UTC 自然月 Token 上限；NULL 表示不限制';

ALTER TABLE operation_log DROP CONSTRAINT operation_log_operation_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_operation_type_check CHECK (operation_type IN (
    'ADMIN_INITIALIZE','ADMIN_PASSWORD_RESET',
    'MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','MEMBER_STATUS_CHANGE',
    'APPLICATION_CREATE','APPLICATION_UPDATE','APPLICATION_DELETE','APPLICATION_STATUS_CHANGE',
    'PRINCIPAL_TOKEN_QUOTA_ADD',
    'ACCESS_KEY_CREATE','ACCESS_KEY_REVOKE',
    'GROUP_CREATE','GROUP_UPDATE','GROUP_STATUS_CHANGE','GROUP_DELETE','GROUP_TOKEN_QUOTA_ADD',
    'GROUP_MEMBER_ADD','GROUP_MEMBER_REMOVE','GROUP_APPLICATION_ADD','GROUP_APPLICATION_REMOVE',
    'GROUP_MODEL_GRANT','GROUP_MODEL_REVOKE',
    'MODEL_CREATE','MODEL_UPDATE','MODEL_DELETE','MODEL_STATUS_CHANGE','MODEL_CATALOG_SYNC',
    'PROVIDER_CREATE','PROVIDER_UPDATE','PROVIDER_DELETE','PROVIDER_STATUS_CHANGE',
    'RESOURCE_CREATE','RESOURCE_CREDENTIAL_UPDATE','RESOURCE_CREDENTIAL_EXPORT','RESOURCE_STATUS_CHANGE',
    'RESOURCE_DELETE','RESOURCE_CONNECTION_TEST','RESOURCE_RATE_LIMIT_RESET','RESOURCE_PRICE_UPDATE',
    'LOGIN_SUCCESS','LOGIN_FAILED','LOGIN_LOCKED'
));

-- +goose Down
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM operation_log
        WHERE operation_type IN ('PRINCIPAL_TOKEN_QUOTA_ADD', 'GROUP_TOKEN_QUOTA_ADD')
    ) THEN
        RAISE EXCEPTION 'Cannot remove token quota audit types while quota operation logs exist';
    END IF;
END $$;
-- +goose StatementEnd

ALTER TABLE operation_log DROP CONSTRAINT operation_log_operation_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_operation_type_check CHECK (operation_type IN (
    'ADMIN_INITIALIZE','ADMIN_PASSWORD_RESET',
    'MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','MEMBER_STATUS_CHANGE',
    'APPLICATION_CREATE','APPLICATION_UPDATE','APPLICATION_DELETE','APPLICATION_STATUS_CHANGE',
    'ACCESS_KEY_CREATE','ACCESS_KEY_REVOKE',
    'GROUP_CREATE','GROUP_UPDATE','GROUP_STATUS_CHANGE','GROUP_DELETE',
    'GROUP_MEMBER_ADD','GROUP_MEMBER_REMOVE','GROUP_APPLICATION_ADD','GROUP_APPLICATION_REMOVE',
    'GROUP_MODEL_GRANT','GROUP_MODEL_REVOKE',
    'MODEL_CREATE','MODEL_UPDATE','MODEL_DELETE','MODEL_STATUS_CHANGE','MODEL_CATALOG_SYNC',
    'PROVIDER_CREATE','PROVIDER_UPDATE','PROVIDER_DELETE','PROVIDER_STATUS_CHANGE',
    'RESOURCE_CREATE','RESOURCE_CREDENTIAL_UPDATE','RESOURCE_CREDENTIAL_EXPORT','RESOURCE_STATUS_CHANGE',
    'RESOURCE_DELETE','RESOURCE_CONNECTION_TEST','RESOURCE_RATE_LIMIT_RESET','RESOURCE_PRICE_UPDATE',
    'LOGIN_SUCCESS','LOGIN_FAILED','LOGIN_LOCKED'
));

ALTER TABLE principal_group DROP COLUMN monthly_token_limit;
ALTER TABLE principal DROP COLUMN monthly_token_limit;
