-- +goose Up
ALTER TABLE operation_log DROP CONSTRAINT operation_log_module_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_module_check
    CHECK (module IN ('MEMBER','APPLICATION','ACCESS_KEY','GROUP','MODEL','PROVIDER','RESOURCE','AUTH'));

ALTER TABLE operation_log DROP CONSTRAINT operation_log_target_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_target_type_check
    CHECK (target_type IN ('PRINCIPAL','APPLICATION','ACCESS_KEY','GROUP','MODEL','PROVIDER','RESOURCE','ADMIN_USER'));

ALTER TABLE operation_log DROP CONSTRAINT operation_log_operation_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_operation_type_check CHECK (operation_type IN (
    'ADMIN_INITIALIZE','ADMIN_PASSWORD_RESET',
    'MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','MEMBER_STATUS_CHANGE',
    'APPLICATION_CREATE','APPLICATION_UPDATE','APPLICATION_DELETE','APPLICATION_STATUS_CHANGE',
    'ACCESS_KEY_CREATE','ACCESS_KEY_REVOKE',
    'GROUP_CREATE','GROUP_UPDATE','GROUP_STATUS_CHANGE','GROUP_DELETE',
    'GROUP_MEMBER_ADD','GROUP_MEMBER_REMOVE','GROUP_APPLICATION_ADD','GROUP_APPLICATION_REMOVE',
    'GROUP_MODEL_GRANT','GROUP_MODEL_REVOKE',
    'MODEL_CREATE','MODEL_UPDATE','MODEL_DELETE','MODEL_STATUS_CHANGE','MODEL_CATALOG_SYNC',
    'PROVIDER_CREATE','PROVIDER_UPDATE','PROVIDER_DELETE','PROVIDER_STATUS_CHANGE',
    'RESOURCE_CREATE','RESOURCE_CREDENTIAL_UPDATE','RESOURCE_CREDENTIAL_EXPORT','RESOURCE_STATUS_CHANGE',
    'RESOURCE_DELETE','RESOURCE_CONNECTION_TEST','RESOURCE_RATE_LIMIT_RESET',
    'LOGIN_SUCCESS','LOGIN_FAILED','LOGIN_LOCKED'
));

COMMENT ON COLUMN principal.principal_type IS '主体类型：MEMBER=成员；APPLICATION=应用';

-- +goose Down
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM operation_log WHERE module='APPLICATION' OR target_type='APPLICATION'
        OR operation_type IN ('APPLICATION_CREATE','APPLICATION_UPDATE','APPLICATION_DELETE','APPLICATION_STATUS_CHANGE',
                              'GROUP_APPLICATION_ADD','GROUP_APPLICATION_REMOVE')) THEN
        RAISE EXCEPTION 'Cannot remove Application audit types while Application operation logs exist';
    END IF;
END $$;
-- +goose StatementEnd

ALTER TABLE operation_log DROP CONSTRAINT operation_log_operation_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_operation_type_check CHECK (operation_type IN (
    'ADMIN_INITIALIZE','ADMIN_PASSWORD_RESET',
    'MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','MEMBER_STATUS_CHANGE',
    'ACCESS_KEY_CREATE','ACCESS_KEY_REVOKE',
    'GROUP_CREATE','GROUP_UPDATE','GROUP_STATUS_CHANGE','GROUP_DELETE',
    'GROUP_MEMBER_ADD','GROUP_MEMBER_REMOVE','GROUP_MODEL_GRANT','GROUP_MODEL_REVOKE',
    'MODEL_CREATE','MODEL_UPDATE','MODEL_DELETE','MODEL_STATUS_CHANGE','MODEL_CATALOG_SYNC',
    'PROVIDER_CREATE','PROVIDER_UPDATE','PROVIDER_DELETE','PROVIDER_STATUS_CHANGE',
    'RESOURCE_CREATE','RESOURCE_CREDENTIAL_UPDATE','RESOURCE_CREDENTIAL_EXPORT','RESOURCE_STATUS_CHANGE',
    'RESOURCE_DELETE','RESOURCE_CONNECTION_TEST','RESOURCE_RATE_LIMIT_RESET',
    'LOGIN_SUCCESS','LOGIN_FAILED','LOGIN_LOCKED'
));
ALTER TABLE operation_log DROP CONSTRAINT operation_log_target_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_target_type_check
    CHECK (target_type IN ('PRINCIPAL','ACCESS_KEY','GROUP','MODEL','PROVIDER','RESOURCE','ADMIN_USER'));
ALTER TABLE operation_log DROP CONSTRAINT operation_log_module_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_module_check
    CHECK (module IN ('MEMBER','ACCESS_KEY','GROUP','MODEL','PROVIDER','RESOURCE','AUTH'));
COMMENT ON COLUMN principal.principal_type IS '主体类型：MEMBER=成员；APPLICATION=应用，仅预留类型';
