-- +goose Up
ALTER TABLE operation_log DROP CONSTRAINT operation_log_operation_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_operation_type_check CHECK (operation_type IN (
    'ADMIN_INITIALIZE','ADMIN_PASSWORD_RESET',
    'MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','MEMBER_STATUS_CHANGE',
    'APPLICATION_CREATE','APPLICATION_UPDATE','APPLICATION_DELETE','APPLICATION_STATUS_CHANGE',
    'PRINCIPAL_TOKEN_QUOTA_ADD','PRINCIPAL_TOKEN_QUOTA_REMOVE',
    'ACCESS_KEY_CREATE','ACCESS_KEY_REVOKE',
    'GROUP_CREATE','GROUP_UPDATE','GROUP_STATUS_CHANGE','GROUP_DELETE',
    'GROUP_TOKEN_QUOTA_ADD','GROUP_TOKEN_QUOTA_REMOVE',
    'GROUP_MEMBER_ADD','GROUP_MEMBER_REMOVE','GROUP_APPLICATION_ADD','GROUP_APPLICATION_REMOVE',
    'GROUP_MODEL_GRANT','GROUP_MODEL_REVOKE',
    'MODEL_CREATE','MODEL_UPDATE','MODEL_DELETE','MODEL_STATUS_CHANGE','MODEL_CATALOG_SYNC',
    'PROVIDER_CREATE','PROVIDER_UPDATE','PROVIDER_DELETE','PROVIDER_STATUS_CHANGE',
    'RESOURCE_CREATE','RESOURCE_CREDENTIAL_UPDATE','RESOURCE_CREDENTIAL_EXPORT','RESOURCE_STATUS_CHANGE',
    'RESOURCE_DELETE','RESOURCE_CONNECTION_TEST','RESOURCE_RATE_LIMIT_RESET','RESOURCE_PRICE_UPDATE',
    'LOGIN_SUCCESS','LOGIN_FAILED','LOGIN_LOCKED'
));

-- +goose Down
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM operation_log
        WHERE operation_type IN ('PRINCIPAL_TOKEN_QUOTA_REMOVE', 'GROUP_TOKEN_QUOTA_REMOVE')
    ) THEN
        RAISE EXCEPTION 'Cannot remove token quota audit types while quota removal logs exist';
    END IF;
END $$;
-- +goose StatementEnd

ALTER TABLE operation_log DROP CONSTRAINT operation_log_operation_type_check;
ALTER TABLE operation_log ADD CONSTRAINT operation_log_operation_type_check CHECK (operation_type IN (
    'ADMIN_INITIALIZE','ADMIN_PASSWORD_RESET',
    'MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','MEMBER_STATUS_CHANGE',
    'APPLICATION_CREATE','APPLICATION_UPDATE','APPLICATION_DELETE','APPLICATION_STATUS_CHANGE',
    'PRINCIPAL_TOKEN_QUOTA_ADD',
    'ACCESS_KEY_CREATE','ACCESS_KEY_REVOKE',
    'GROUP_CREATE','GROUP_UPDATE','GROUP_STATUS_CHANGE','GROUP_DELETE','GROUP_TOKEN_QUOTA_ADD',
    'GROUP_MEMBER_ADD','GROUP_MEMBER_REMOVE','GROUP_APPLICATION_ADD','GROUP_APPLICATION_REMOVE',
    'GROUP_MODEL_GRANT','GROUP_MODEL_REVOKE',
    'MODEL_CREATE','MODEL_UPDATE','MODEL_DELETE','MODEL_STATUS_CHANGE','MODEL_CATALOG_SYNC',
    'PROVIDER_CREATE','PROVIDER_UPDATE','PROVIDER_DELETE','PROVIDER_STATUS_CHANGE',
    'RESOURCE_CREATE','RESOURCE_CREDENTIAL_UPDATE','RESOURCE_CREDENTIAL_EXPORT','RESOURCE_STATUS_CHANGE',
    'RESOURCE_DELETE','RESOURCE_CONNECTION_TEST','RESOURCE_RATE_LIMIT_RESET','RESOURCE_PRICE_UPDATE',
    'LOGIN_SUCCESS','LOGIN_FAILED','LOGIN_LOCKED'
));
